import { beforeEach, describe, expect, it, vi } from 'vitest'
import { mount, flushPromises } from '@vue/test-utils'
import HarvestGatewayBorrowPanel from '../HarvestGatewayBorrowPanel.vue'
import AstraGatewayRuntime from '@/components/admin/AstraGatewayRuntime.vue'
import { normalizeAstraGateway, resolveAstraDependencies } from '@/api/admin/astraGateway'
const mocks = vi.hoisted(() => ({ get: vi.fn(), save: vi.fn(), list: vi.fn() }))
vi.mock('@/api/admin/astraGateway', async importOriginal => ({ ...await importOriginal<typeof import('@/api/admin/astraGateway')>(), getAstraGateway: mocks.get, saveAstraGateway: mocks.save }))
vi.mock('@/components/admin/AstraGatewayRuntime.vue', () => ({ default: { template: '<section />' } }))
vi.mock('@/components/admin/AstraGatewayHistory.vue', () => ({ default: { template: '<section />' } }))
vi.mock('@/api/admin/groups', () => ({ getAllIncludingInactive: vi.fn().mockResolvedValue([{ id: 7, name: 'Astra group' }]) }))
vi.mock('@/api/admin/accounts', () => ({ list: mocks.list }))
vi.mock('vue-i18n', async importOriginal => ({ ...await importOriginal<typeof import('vue-i18n')>(), useI18n: () => ({ t: (key: string) => key, te: () => true }) }))
vi.mock('@/components/layout/AppLayout.vue', () => ({ default: { template: '<main><slot /></main>' } }))
function value() { return { cookie_pool: { enabled: false, source_account_ids: [299], target_account_ids: [300] }, ws_session: { enabled: false, account_ids: [300] }, revision: 'one' } }
function render() { const wrapper = mount(HarvestGatewayBorrowPanel, { global: { stubs: { RouterLink: { template: '<a><slot /></a>' } } } }); void wrapper.get('[data-testid="expand-borrow"]').trigger('click'); return wrapper }
beforeEach(() => { vi.clearAllMocks(); mocks.get.mockResolvedValue(value()); mocks.list.mockResolvedValue({ items: [{ id: 299, name: 'source' }, { id: 300, name: 'target' }], pages: 1 }); mocks.save.mockImplementation(v => Promise.resolve({ ...v, revision: 'two' })) })
describe('Astra gateway configuration', () => {
  it('keeps gateway borrowing in its own collapsed card and preserves edits when collapsed', async () => {
    const w = mount(HarvestGatewayBorrowPanel, { global: { stubs: { RouterLink: true } } })
    await flushPromises()
    expect(w.text()).toContain('admin.astraGateway.borrowTitle')
    expect(w.find('form').exists()).toBe(false)
    const expand = w.get('[data-testid="expand-borrow"]')
    expect(expand.attributes('aria-expanded')).toBe('false')
    await expand.trigger('click')
    await w.get('[data-testid="cookie-toggle"]').trigger('click')
    await expand.trigger('click')
    expect(w.find('form').exists()).toBe(false)
    expect(w.text()).toContain('admin.astraGateway.unsaved')
    await expand.trigger('click')
    expect(w.get('[data-testid="cookie-toggle"]').attributes('aria-checked')).toBe('true')
    expect(mocks.save).not.toHaveBeenCalled()
    w.unmount()
  })

  it('requires selected groups and persists each scheduling mode', async () => {
    mocks.get.mockResolvedValue({ ...value(), account_scheduling: true })
    const w = render(); await flushPromises()
    expect(w.get('[data-testid="scheduling-mode"]').element).toHaveProperty('value', 'account')
    await w.get('[data-testid="scheduling-mode"]').setValue('groups'); await flushPromises()
    expect(w.get('[data-testid="save"]').attributes('disabled')).toBeDefined()
    await w.get('[data-testid="scheduling-groups"] input').setValue(true)
    await w.get('form').trigger('submit'); await flushPromises()
    expect(mocks.save).toHaveBeenLastCalledWith(expect.objectContaining({ scheduling_mode: 'groups', scheduling_group_ids: [7] }))
    await w.get('[data-testid="scheduling-mode"]').setValue('model')
    await w.get('form').trigger('submit'); await flushPromises()
    expect(mocks.save).toHaveBeenLastCalledWith(expect.objectContaining({ scheduling_mode: 'model' }))
    w.unmount()
  })
  it('shows the latest three scheduling changes from runtime refresh', async () => {
    const w = render(); await flushPromises()
    expect(w.get('[data-testid="scheduling-records"]').text()).toContain('schedulingLogEmpty')
    w.findComponent(AstraGatewayRuntime).vm.$emit('scheduling', [300, 343, 344, 345].map((id, i) => ({ account_id: id, schedulable: i === 0, checked_at: '2026-09-24T12:00:00Z', reason: 'target_candy_passed' })))
    await flushPromises()
    const log = w.get('[data-testid="scheduling-records"]')
    expect(log.findAll('li')).toHaveLength(3)
    expect(log.text()).toContain('#300')
    expect(log.text()).not.toContain('#345')
    expect(log.text()).toContain('admin.astraGateway.enabled')
    expect(log.text()).toContain('admin.astraGateway.disabled')
    w.unmount()
  })
  it('defaults scheduling off and persists it without changing route settings', async () => {
    const w = render(); await flushPromises()
    const toggle = w.get('[data-testid="account-scheduling-toggle"]')
    expect(toggle.attributes('aria-checked')).toBe('false')
    await toggle.trigger('click')
    await w.get('form').trigger('submit'); await flushPromises()
    expect(mocks.save).toHaveBeenLastCalledWith(expect.objectContaining({ account_scheduling: true, cookie_pool: expect.objectContaining({ enabled: false, target_account_ids: [300] }) }))
    expect(toggle.attributes('aria-checked')).toBe('true')
    w.unmount()
  })
  it('loads disabled defaults and saves independent switches', async () => {
    const w = render(); await flushPromises()
    expect(w.get('[data-testid="cookie-toggle"]').attributes('aria-checked')).toBe('false')
    await w.get('[data-testid="cookie-toggle"]').trigger('click')
    await w.get('form').trigger('submit'); await flushPromises()
    expect(mocks.save).toHaveBeenCalledWith(expect.objectContaining({ cookie_pool: expect.objectContaining({ enabled: true }), ws_session: expect.objectContaining({ enabled: false }) }))
    expect(w.find('[role="status"]').exists()).toBe(true); w.unmount()
  })
  it('defaults IP affinity off and preserves selections when toggling and saving', async () => {
    const w = render(); await flushPromises()
    const toggle = w.get('[data-testid="ip-affinity-toggle"]')
    expect(toggle.attributes('aria-checked')).toBe('false')
    await toggle.trigger('click')
    await w.get('form').trigger('submit'); await flushPromises()
    expect(mocks.save).toHaveBeenLastCalledWith(expect.objectContaining({ cookie_pool: expect.objectContaining({ ip_affinity: true, source_account_ids: [299], target_account_ids: [300] }) }))
    expect(toggle.attributes('aria-checked')).toBe('true')
    await toggle.trigger('click')
    await w.get('form').trigger('submit'); await flushPromises()
    expect(mocks.save).toHaveBeenLastCalledWith(expect.objectContaining({ cookie_pool: expect.objectContaining({ ip_affinity: false, source_account_ids: [299], target_account_ids: [300] }) }))
    w.unmount()
  })
  it('loads saved IP affinity and retains the draft after a failed save', async () => {
    const data = normalizeAstraGateway(value()); data.cookie_pool.ip_affinity = true
    mocks.get.mockResolvedValue(data)
    const w = render(); await flushPromises()
    expect(w.get('[data-testid="ip-affinity-toggle"]').attributes('aria-checked')).toBe('true')
    mocks.save.mockRejectedValue(new Error('offline'))
    await w.get('[data-testid="ip-affinity-toggle"]').trigger('click')
    await w.get('form').trigger('submit'); await flushPromises()
    expect(w.get('[data-testid="ip-affinity-toggle"]').attributes('aria-checked')).toBe('false')
    expect(w.text()).toContain('admin.astraGateway.unsaved')
    w.unmount()
  })
  it('enables affinity with rotation, persists its budget and disables rotation when affinity is off', async () => {
    const w = render(); await flushPromises()
    expect(w.get('[data-testid="rotation-toggle"]').attributes('aria-checked')).toBe('false')
    await w.get('[data-testid="rotation-toggle"]').trigger('click')
    expect(w.get('[data-testid="ip-affinity-toggle"]').attributes('aria-checked')).toBe('true')
    await w.get('[data-testid="node-attempts"]').setValue('2')
    await w.get('[data-testid="node-cooldown"]').setValue('1800')
    await w.get('form').trigger('submit'); await flushPromises()
    expect(mocks.save).toHaveBeenLastCalledWith(expect.objectContaining({ cookie_pool: expect.objectContaining({ rotate_nodes: true, ip_affinity: true, max_node_attempts: 2, node_cooldown_seconds: 1800, source_account_ids: [299], target_account_ids: [300] }) }))
    await w.get('[data-testid="node-attempts"]').setValue('11')
    await w.get('form').trigger('submit'); await flushPromises()
    expect(mocks.save).toHaveBeenCalledTimes(1)
    await w.get('[data-testid="ip-affinity-toggle"]').trigger('click')
    expect(w.get('[data-testid="rotation-toggle"]').attributes('aria-checked')).toBe('false')
    w.unmount()
  })
  it('blocks overlapping source and target selections', async () => {
    const data = value(); data.cookie_pool.enabled = true; data.cookie_pool.target_account_ids = [299]; mocks.get.mockResolvedValue(data)
    const w = render(); await flushPromises()
    expect(w.text()).toContain('admin.astraGateway.overlap')
    await w.get('form').trigger('submit'); expect(mocks.save).not.toHaveBeenCalled(); w.unmount()
  })
  it('keeps edits on failed save and supports discard', async () => {
    mocks.save.mockRejectedValue(new Error('offline'))
    const w = render(); await flushPromises(); await w.get('[data-testid="ws-toggle"]').trigger('click')
    await w.get('form').trigger('submit'); await flushPromises()
    expect(w.text()).toContain('admin.astraGateway.saveError')
    expect(w.get('[data-testid="ws-toggle"]').attributes('aria-checked')).toBe('true')
    const discard = w.findAll('button').find(b => b.text() === 'admin.astraGateway.discard')!
    await discard.trigger('click'); await flushPromises()
    expect(w.get('[data-testid="ws-toggle"]').attributes('aria-checked')).toBe('false'); w.unmount()
  })
  it('automatically links the Cookie pool when enabling WS', async () => {
    const w = render(); await flushPromises(); await w.get('[data-testid="ws-toggle"]').trigger('click')
    await w.get('form').trigger('submit'); await flushPromises()
    expect(mocks.save).toHaveBeenCalledWith(expect.objectContaining({ cookie_pool: expect.objectContaining({ enabled: true, source_account_ids: [299], target_account_ids: [300] }), ws_session: expect.objectContaining({ enabled: true }) })); w.unmount()
  })
  it('normalizes null account arrays without sharing draft arrays', () => {
    const v = value(); const cloned = normalizeAstraGateway(v); cloned.cookie_pool.source_account_ids.push(1)
    expect(v.cookie_pool.source_account_ids).toEqual([299])
  })
})

describe('Automatic quality borrowing settings', () => {
  it('preserves per-model targets and independent draft arrays when settings are normalized', () => {
    const data = { ...value(), auto_quality: true, cookie_pool: { ...value().cookie_pool, models: ['gpt-6-astra', 'gpt-6.1-sol'], target_models: { '300': ['gpt-6.1-sol'] } } }
    const draft = normalizeAstraGateway(data)
    expect(draft.auto_quality).toBe(true)
    draft.cookie_pool.models!.push('other')
    draft.cookie_pool.target_models!['300'].push('gpt-6-astra')
    expect(data.cookie_pool.models).toEqual(['gpt-6-astra', 'gpt-6.1-sol'])
    expect(data.cookie_pool.target_models['300']).toEqual(['gpt-6.1-sol'])
  })

  it('saves automatic fields without exposing legacy account or group scheduling controls', async () => {
    const data = { ...value(), auto_quality: true, account_scheduling: true, scheduling_mode: 'groups', scheduling_group_ids: [7], cookie_pool: { ...value().cookie_pool, enabled: true, models: ['gpt-6-astra', 'gpt-6.1-sol'], target_models: { '300': ['gpt-6.1-sol'] } } }
    mocks.get.mockResolvedValue(data)
    const w = render(); await flushPromises()
    expect(w.get('[data-testid="automatic-accounts"]').text()).toContain('#300 · gpt-6.1-sol')
    expect(w.find('[data-testid="manual-accounts"]').exists()).toBe(false)
    expect(w.find('[data-testid="manual-scheduling"]').exists()).toBe(false)
    expect(w.find('[data-testid="ws-toggle"]').exists()).toBe(false)
    expect(w.get('[data-testid="cookie-toggle"]').attributes('disabled')).toBeDefined()
    await w.get('[data-testid="ip-affinity-toggle"]').trigger('click')
    await w.get('form').trigger('submit'); await flushPromises()
    expect(mocks.save).toHaveBeenCalledWith(expect.objectContaining({ auto_quality: true, account_scheduling: true, scheduling_group_ids: [7], cookie_pool: expect.objectContaining({ models: ['gpt-6-astra', 'gpt-6.1-sol'], target_models: { '300': ['gpt-6.1-sol'] }, source_account_ids: [299], target_account_ids: [300] }) }))
    w.unmount()
  })

  it('can enable automatic mode before quality checks have populated any sources or targets', async () => {
    mocks.get.mockResolvedValue({ ...value(), cookie_pool: { enabled: false, source_account_ids: [], target_account_ids: [] } })
    const w = render(); await flushPromises()
    await w.get('[data-testid="auto-quality-toggle"]').trigger('click')
    expect(w.get('[data-testid="auto-model-scope"]').text()).toContain('autoModelScope')
    expect(w.get('[data-testid="save"]').attributes('disabled')).toBeUndefined()
    await w.get('form').trigger('submit'); await flushPromises()
    expect(mocks.save).toHaveBeenCalledWith(expect.objectContaining({ auto_quality: true, cookie_pool: expect.objectContaining({ enabled: true, models: ['gpt-6-astra', 'gpt-6.1-sol'], source_account_ids: [], target_account_ids: [] }) }))
    w.unmount()
  })

  it('does not merge hidden legacy WS participants into automatic targets', () => {
    const data = { ...value(), auto_quality: true, ws_session: { enabled: true, account_ids: [301] } }
    const resolved = resolveAstraDependencies(data)
    expect(resolved.cookie_pool.target_account_ids).toEqual([300])
    expect(resolved.ws_session.account_ids).toEqual([301])
  })

  it('requires a selected manual model instead of silently reverting to Astra', async () => {
    const data = normalizeAstraGateway(value()); data.cookie_pool.enabled = true
    mocks.get.mockResolvedValue(data)
    const w = render(); await flushPromises()
    await w.get('[data-testid="borrow-models"] input').setValue(false)
    expect(w.text()).toContain('chooseModels')
    await w.get('form').trigger('submit'); expect(mocks.save).not.toHaveBeenCalled()
    w.unmount()
  })
})

describe('Scheduled quality task ownership', () => {
  it('keeps saved automatic quality mode read-only and preserves protected model scopes', async () => {
    mocks.get.mockResolvedValue({ ...value(), auto_quality: true, cookie_pool: { ...value().cookie_pool, enabled: true, models: ['gpt-6-astra', 'gpt-6.1-sol'], target_models: { '300': ['gpt-6.1-sol'] } } })
    const w = render(); await flushPromises()
    const toggle = w.get('[data-testid="auto-quality-toggle"]')
    expect(toggle.attributes('disabled')).toBeDefined()
    expect(w.get('[data-testid="auto-managed-hint"]').text()).toContain('autoManagedHint')
    await toggle.trigger('click'); await flushPromises()
    expect(toggle.attributes('aria-checked')).toBe('true')
    expect(w.find('[data-testid="manual-accounts"]').exists()).toBe(false)
    await w.get('[data-testid="ip-affinity-toggle"]').trigger('click')
    await w.get('form').trigger('submit'); await flushPromises()
    expect(mocks.save).toHaveBeenLastCalledWith(expect.objectContaining({ auto_quality: true, cookie_pool: expect.objectContaining({ target_models: { '300': ['gpt-6.1-sol'] } }) }))
    w.unmount()
  })

  it('allows enabling an unsaved manual mode, then locks it once automatic settings are saved', async () => {
    const w = render(); await flushPromises()
    const toggle = w.get('[data-testid="auto-quality-toggle"]')
    expect(toggle.attributes('disabled')).toBeUndefined()
    await toggle.trigger('click'); await flushPromises()
    expect(toggle.attributes('aria-checked')).toBe('true')
    expect(toggle.attributes('disabled')).toBeUndefined()
    await w.get('form').trigger('submit'); await flushPromises()
    expect(toggle.attributes('disabled')).toBeDefined()
    await toggle.trigger('click'); await flushPromises()
    expect(toggle.attributes('aria-checked')).toBe('true')
    expect(mocks.save).toHaveBeenCalledTimes(1)
    w.unmount()
  })
})
