// Code generated by ent, DO NOT EDIT.

package paymentexternalorder

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldLTE(FieldID, id))
}

// ProviderKey applies equality check predicate on the "provider_key" field. It's identical to ProviderKeyEQ.
func ProviderKey(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldEQ(FieldProviderKey, v))
}

// WebsiteID applies equality check predicate on the "website_id" field. It's identical to WebsiteIDEQ.
func WebsiteID(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldEQ(FieldWebsiteID, v))
}

// ExternalOrderID applies equality check predicate on the "external_order_id" field. It's identical to ExternalOrderIDEQ.
func ExternalOrderID(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldEQ(FieldExternalOrderID, v))
}

// OrderNumber applies equality check predicate on the "order_number" field. It's identical to OrderNumberEQ.
func OrderNumber(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldEQ(FieldOrderNumber, v))
}

// BindingMethod applies equality check predicate on the "binding_method" field. It's identical to BindingMethodEQ.
func BindingMethod(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldEQ(FieldBindingMethod, v))
}

// QuoteHash applies equality check predicate on the "quote_hash" field. It's identical to QuoteHashEQ.
func QuoteHash(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldEQ(FieldQuoteHash, v))
}

// LocalOrderID applies equality check predicate on the "local_order_id" field. It's identical to LocalOrderIDEQ.
func LocalOrderID(v int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldEQ(FieldLocalOrderID, v))
}

// CheckoutReference applies equality check predicate on the "checkout_reference" field. It's identical to CheckoutReferenceEQ.
func CheckoutReference(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldEQ(FieldCheckoutReference, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldEQ(FieldCurrency, v))
}

// TotalMinor applies equality check predicate on the "total_minor" field. It's identical to TotalMinorEQ.
func TotalMinor(v int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldEQ(FieldTotalMinor, v))
}

// RefundedMinor applies equality check predicate on the "refunded_minor" field. It's identical to RefundedMinorEQ.
func RefundedMinor(v int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldEQ(FieldRefundedMinor, v))
}

// CreditedUsdUnits applies equality check predicate on the "credited_usd_units" field. It's identical to CreditedUsdUnitsEQ.
func CreditedUsdUnits(v int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldEQ(FieldCreditedUsdUnits, v))
}

// RefundTargetUsdUnits applies equality check predicate on the "refund_target_usd_units" field. It's identical to RefundTargetUsdUnitsEQ.
func RefundTargetUsdUnits(v int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldEQ(FieldRefundTargetUsdUnits, v))
}

// RecoveredUsdUnits applies equality check predicate on the "recovered_usd_units" field. It's identical to RecoveredUsdUnitsEQ.
func RecoveredUsdUnits(v int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldEQ(FieldRecoveredUsdUnits, v))
}

// DebtUsdUnits applies equality check predicate on the "debt_usd_units" field. It's identical to DebtUsdUnitsEQ.
func DebtUsdUnits(v int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldEQ(FieldDebtUsdUnits, v))
}

// PaymentState applies equality check predicate on the "payment_state" field. It's identical to PaymentStateEQ.
func PaymentState(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldEQ(FieldPaymentState, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldEQ(FieldStatus, v))
}

// AnomalyCode applies equality check predicate on the "anomaly_code" field. It's identical to AnomalyCodeEQ.
func AnomalyCode(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldEQ(FieldAnomalyCode, v))
}

// PaidAt applies equality check predicate on the "paid_at" field. It's identical to PaidAtEQ.
func PaidAt(v time.Time) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldEQ(FieldPaidAt, v))
}

// ProviderModifiedAt applies equality check predicate on the "provider_modified_at" field. It's identical to ProviderModifiedAtEQ.
func ProviderModifiedAt(v time.Time) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldEQ(FieldProviderModifiedAt, v))
}

// LastSeenAt applies equality check predicate on the "last_seen_at" field. It's identical to LastSeenAtEQ.
func LastSeenAt(v time.Time) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldEQ(FieldLastSeenAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldEQ(FieldUpdatedAt, v))
}

// ProviderKeyEQ applies the EQ predicate on the "provider_key" field.
func ProviderKeyEQ(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldEQ(FieldProviderKey, v))
}

// ProviderKeyNEQ applies the NEQ predicate on the "provider_key" field.
func ProviderKeyNEQ(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldNEQ(FieldProviderKey, v))
}

// ProviderKeyIn applies the In predicate on the "provider_key" field.
func ProviderKeyIn(vs ...string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldIn(FieldProviderKey, vs...))
}

// ProviderKeyNotIn applies the NotIn predicate on the "provider_key" field.
func ProviderKeyNotIn(vs ...string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldNotIn(FieldProviderKey, vs...))
}

// ProviderKeyGT applies the GT predicate on the "provider_key" field.
func ProviderKeyGT(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldGT(FieldProviderKey, v))
}

// ProviderKeyGTE applies the GTE predicate on the "provider_key" field.
func ProviderKeyGTE(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldGTE(FieldProviderKey, v))
}

// ProviderKeyLT applies the LT predicate on the "provider_key" field.
func ProviderKeyLT(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldLT(FieldProviderKey, v))
}

// ProviderKeyLTE applies the LTE predicate on the "provider_key" field.
func ProviderKeyLTE(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldLTE(FieldProviderKey, v))
}

// ProviderKeyContains applies the Contains predicate on the "provider_key" field.
func ProviderKeyContains(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldContains(FieldProviderKey, v))
}

// ProviderKeyHasPrefix applies the HasPrefix predicate on the "provider_key" field.
func ProviderKeyHasPrefix(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldHasPrefix(FieldProviderKey, v))
}

// ProviderKeyHasSuffix applies the HasSuffix predicate on the "provider_key" field.
func ProviderKeyHasSuffix(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldHasSuffix(FieldProviderKey, v))
}

// ProviderKeyEqualFold applies the EqualFold predicate on the "provider_key" field.
func ProviderKeyEqualFold(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldEqualFold(FieldProviderKey, v))
}

// ProviderKeyContainsFold applies the ContainsFold predicate on the "provider_key" field.
func ProviderKeyContainsFold(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldContainsFold(FieldProviderKey, v))
}

// WebsiteIDEQ applies the EQ predicate on the "website_id" field.
func WebsiteIDEQ(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldEQ(FieldWebsiteID, v))
}

// WebsiteIDNEQ applies the NEQ predicate on the "website_id" field.
func WebsiteIDNEQ(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldNEQ(FieldWebsiteID, v))
}

// WebsiteIDIn applies the In predicate on the "website_id" field.
func WebsiteIDIn(vs ...string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldIn(FieldWebsiteID, vs...))
}

// WebsiteIDNotIn applies the NotIn predicate on the "website_id" field.
func WebsiteIDNotIn(vs ...string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldNotIn(FieldWebsiteID, vs...))
}

// WebsiteIDGT applies the GT predicate on the "website_id" field.
func WebsiteIDGT(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldGT(FieldWebsiteID, v))
}

// WebsiteIDGTE applies the GTE predicate on the "website_id" field.
func WebsiteIDGTE(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldGTE(FieldWebsiteID, v))
}

// WebsiteIDLT applies the LT predicate on the "website_id" field.
func WebsiteIDLT(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldLT(FieldWebsiteID, v))
}

// WebsiteIDLTE applies the LTE predicate on the "website_id" field.
func WebsiteIDLTE(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldLTE(FieldWebsiteID, v))
}

// WebsiteIDContains applies the Contains predicate on the "website_id" field.
func WebsiteIDContains(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldContains(FieldWebsiteID, v))
}

// WebsiteIDHasPrefix applies the HasPrefix predicate on the "website_id" field.
func WebsiteIDHasPrefix(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldHasPrefix(FieldWebsiteID, v))
}

// WebsiteIDHasSuffix applies the HasSuffix predicate on the "website_id" field.
func WebsiteIDHasSuffix(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldHasSuffix(FieldWebsiteID, v))
}

// WebsiteIDEqualFold applies the EqualFold predicate on the "website_id" field.
func WebsiteIDEqualFold(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldEqualFold(FieldWebsiteID, v))
}

// WebsiteIDContainsFold applies the ContainsFold predicate on the "website_id" field.
func WebsiteIDContainsFold(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldContainsFold(FieldWebsiteID, v))
}

// ExternalOrderIDEQ applies the EQ predicate on the "external_order_id" field.
func ExternalOrderIDEQ(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldEQ(FieldExternalOrderID, v))
}

// ExternalOrderIDNEQ applies the NEQ predicate on the "external_order_id" field.
func ExternalOrderIDNEQ(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldNEQ(FieldExternalOrderID, v))
}

// ExternalOrderIDIn applies the In predicate on the "external_order_id" field.
func ExternalOrderIDIn(vs ...string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldIn(FieldExternalOrderID, vs...))
}

// ExternalOrderIDNotIn applies the NotIn predicate on the "external_order_id" field.
func ExternalOrderIDNotIn(vs ...string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldNotIn(FieldExternalOrderID, vs...))
}

// ExternalOrderIDGT applies the GT predicate on the "external_order_id" field.
func ExternalOrderIDGT(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldGT(FieldExternalOrderID, v))
}

// ExternalOrderIDGTE applies the GTE predicate on the "external_order_id" field.
func ExternalOrderIDGTE(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldGTE(FieldExternalOrderID, v))
}

// ExternalOrderIDLT applies the LT predicate on the "external_order_id" field.
func ExternalOrderIDLT(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldLT(FieldExternalOrderID, v))
}

// ExternalOrderIDLTE applies the LTE predicate on the "external_order_id" field.
func ExternalOrderIDLTE(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldLTE(FieldExternalOrderID, v))
}

// ExternalOrderIDContains applies the Contains predicate on the "external_order_id" field.
func ExternalOrderIDContains(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldContains(FieldExternalOrderID, v))
}

// ExternalOrderIDHasPrefix applies the HasPrefix predicate on the "external_order_id" field.
func ExternalOrderIDHasPrefix(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldHasPrefix(FieldExternalOrderID, v))
}

// ExternalOrderIDHasSuffix applies the HasSuffix predicate on the "external_order_id" field.
func ExternalOrderIDHasSuffix(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldHasSuffix(FieldExternalOrderID, v))
}

// ExternalOrderIDEqualFold applies the EqualFold predicate on the "external_order_id" field.
func ExternalOrderIDEqualFold(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldEqualFold(FieldExternalOrderID, v))
}

// ExternalOrderIDContainsFold applies the ContainsFold predicate on the "external_order_id" field.
func ExternalOrderIDContainsFold(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldContainsFold(FieldExternalOrderID, v))
}

// OrderNumberEQ applies the EQ predicate on the "order_number" field.
func OrderNumberEQ(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldEQ(FieldOrderNumber, v))
}

// OrderNumberNEQ applies the NEQ predicate on the "order_number" field.
func OrderNumberNEQ(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldNEQ(FieldOrderNumber, v))
}

// OrderNumberIn applies the In predicate on the "order_number" field.
func OrderNumberIn(vs ...string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldIn(FieldOrderNumber, vs...))
}

// OrderNumberNotIn applies the NotIn predicate on the "order_number" field.
func OrderNumberNotIn(vs ...string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldNotIn(FieldOrderNumber, vs...))
}

// OrderNumberGT applies the GT predicate on the "order_number" field.
func OrderNumberGT(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldGT(FieldOrderNumber, v))
}

// OrderNumberGTE applies the GTE predicate on the "order_number" field.
func OrderNumberGTE(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldGTE(FieldOrderNumber, v))
}

// OrderNumberLT applies the LT predicate on the "order_number" field.
func OrderNumberLT(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldLT(FieldOrderNumber, v))
}

// OrderNumberLTE applies the LTE predicate on the "order_number" field.
func OrderNumberLTE(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldLTE(FieldOrderNumber, v))
}

// OrderNumberContains applies the Contains predicate on the "order_number" field.
func OrderNumberContains(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldContains(FieldOrderNumber, v))
}

// OrderNumberHasPrefix applies the HasPrefix predicate on the "order_number" field.
func OrderNumberHasPrefix(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldHasPrefix(FieldOrderNumber, v))
}

// OrderNumberHasSuffix applies the HasSuffix predicate on the "order_number" field.
func OrderNumberHasSuffix(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldHasSuffix(FieldOrderNumber, v))
}

// OrderNumberEqualFold applies the EqualFold predicate on the "order_number" field.
func OrderNumberEqualFold(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldEqualFold(FieldOrderNumber, v))
}

// OrderNumberContainsFold applies the ContainsFold predicate on the "order_number" field.
func OrderNumberContainsFold(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldContainsFold(FieldOrderNumber, v))
}

// BindingMethodEQ applies the EQ predicate on the "binding_method" field.
func BindingMethodEQ(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldEQ(FieldBindingMethod, v))
}

// BindingMethodNEQ applies the NEQ predicate on the "binding_method" field.
func BindingMethodNEQ(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldNEQ(FieldBindingMethod, v))
}

// BindingMethodIn applies the In predicate on the "binding_method" field.
func BindingMethodIn(vs ...string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldIn(FieldBindingMethod, vs...))
}

// BindingMethodNotIn applies the NotIn predicate on the "binding_method" field.
func BindingMethodNotIn(vs ...string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldNotIn(FieldBindingMethod, vs...))
}

// BindingMethodGT applies the GT predicate on the "binding_method" field.
func BindingMethodGT(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldGT(FieldBindingMethod, v))
}

// BindingMethodGTE applies the GTE predicate on the "binding_method" field.
func BindingMethodGTE(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldGTE(FieldBindingMethod, v))
}

// BindingMethodLT applies the LT predicate on the "binding_method" field.
func BindingMethodLT(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldLT(FieldBindingMethod, v))
}

// BindingMethodLTE applies the LTE predicate on the "binding_method" field.
func BindingMethodLTE(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldLTE(FieldBindingMethod, v))
}

// BindingMethodContains applies the Contains predicate on the "binding_method" field.
func BindingMethodContains(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldContains(FieldBindingMethod, v))
}

// BindingMethodHasPrefix applies the HasPrefix predicate on the "binding_method" field.
func BindingMethodHasPrefix(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldHasPrefix(FieldBindingMethod, v))
}

// BindingMethodHasSuffix applies the HasSuffix predicate on the "binding_method" field.
func BindingMethodHasSuffix(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldHasSuffix(FieldBindingMethod, v))
}

// BindingMethodEqualFold applies the EqualFold predicate on the "binding_method" field.
func BindingMethodEqualFold(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldEqualFold(FieldBindingMethod, v))
}

// BindingMethodContainsFold applies the ContainsFold predicate on the "binding_method" field.
func BindingMethodContainsFold(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldContainsFold(FieldBindingMethod, v))
}

// QuoteHashEQ applies the EQ predicate on the "quote_hash" field.
func QuoteHashEQ(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldEQ(FieldQuoteHash, v))
}

// QuoteHashNEQ applies the NEQ predicate on the "quote_hash" field.
func QuoteHashNEQ(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldNEQ(FieldQuoteHash, v))
}

// QuoteHashIn applies the In predicate on the "quote_hash" field.
func QuoteHashIn(vs ...string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldIn(FieldQuoteHash, vs...))
}

// QuoteHashNotIn applies the NotIn predicate on the "quote_hash" field.
func QuoteHashNotIn(vs ...string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldNotIn(FieldQuoteHash, vs...))
}

// QuoteHashGT applies the GT predicate on the "quote_hash" field.
func QuoteHashGT(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldGT(FieldQuoteHash, v))
}

// QuoteHashGTE applies the GTE predicate on the "quote_hash" field.
func QuoteHashGTE(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldGTE(FieldQuoteHash, v))
}

// QuoteHashLT applies the LT predicate on the "quote_hash" field.
func QuoteHashLT(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldLT(FieldQuoteHash, v))
}

// QuoteHashLTE applies the LTE predicate on the "quote_hash" field.
func QuoteHashLTE(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldLTE(FieldQuoteHash, v))
}

// QuoteHashContains applies the Contains predicate on the "quote_hash" field.
func QuoteHashContains(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldContains(FieldQuoteHash, v))
}

// QuoteHashHasPrefix applies the HasPrefix predicate on the "quote_hash" field.
func QuoteHashHasPrefix(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldHasPrefix(FieldQuoteHash, v))
}

// QuoteHashHasSuffix applies the HasSuffix predicate on the "quote_hash" field.
func QuoteHashHasSuffix(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldHasSuffix(FieldQuoteHash, v))
}

// QuoteHashEqualFold applies the EqualFold predicate on the "quote_hash" field.
func QuoteHashEqualFold(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldEqualFold(FieldQuoteHash, v))
}

// QuoteHashContainsFold applies the ContainsFold predicate on the "quote_hash" field.
func QuoteHashContainsFold(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldContainsFold(FieldQuoteHash, v))
}

// LocalOrderIDEQ applies the EQ predicate on the "local_order_id" field.
func LocalOrderIDEQ(v int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldEQ(FieldLocalOrderID, v))
}

// LocalOrderIDNEQ applies the NEQ predicate on the "local_order_id" field.
func LocalOrderIDNEQ(v int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldNEQ(FieldLocalOrderID, v))
}

// LocalOrderIDIn applies the In predicate on the "local_order_id" field.
func LocalOrderIDIn(vs ...int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldIn(FieldLocalOrderID, vs...))
}

// LocalOrderIDNotIn applies the NotIn predicate on the "local_order_id" field.
func LocalOrderIDNotIn(vs ...int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldNotIn(FieldLocalOrderID, vs...))
}

// LocalOrderIDGT applies the GT predicate on the "local_order_id" field.
func LocalOrderIDGT(v int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldGT(FieldLocalOrderID, v))
}

// LocalOrderIDGTE applies the GTE predicate on the "local_order_id" field.
func LocalOrderIDGTE(v int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldGTE(FieldLocalOrderID, v))
}

// LocalOrderIDLT applies the LT predicate on the "local_order_id" field.
func LocalOrderIDLT(v int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldLT(FieldLocalOrderID, v))
}

// LocalOrderIDLTE applies the LTE predicate on the "local_order_id" field.
func LocalOrderIDLTE(v int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldLTE(FieldLocalOrderID, v))
}

// LocalOrderIDIsNil applies the IsNil predicate on the "local_order_id" field.
func LocalOrderIDIsNil() predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldIsNull(FieldLocalOrderID))
}

// LocalOrderIDNotNil applies the NotNil predicate on the "local_order_id" field.
func LocalOrderIDNotNil() predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldNotNull(FieldLocalOrderID))
}

// CheckoutReferenceEQ applies the EQ predicate on the "checkout_reference" field.
func CheckoutReferenceEQ(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldEQ(FieldCheckoutReference, v))
}

// CheckoutReferenceNEQ applies the NEQ predicate on the "checkout_reference" field.
func CheckoutReferenceNEQ(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldNEQ(FieldCheckoutReference, v))
}

// CheckoutReferenceIn applies the In predicate on the "checkout_reference" field.
func CheckoutReferenceIn(vs ...string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldIn(FieldCheckoutReference, vs...))
}

// CheckoutReferenceNotIn applies the NotIn predicate on the "checkout_reference" field.
func CheckoutReferenceNotIn(vs ...string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldNotIn(FieldCheckoutReference, vs...))
}

// CheckoutReferenceGT applies the GT predicate on the "checkout_reference" field.
func CheckoutReferenceGT(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldGT(FieldCheckoutReference, v))
}

// CheckoutReferenceGTE applies the GTE predicate on the "checkout_reference" field.
func CheckoutReferenceGTE(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldGTE(FieldCheckoutReference, v))
}

// CheckoutReferenceLT applies the LT predicate on the "checkout_reference" field.
func CheckoutReferenceLT(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldLT(FieldCheckoutReference, v))
}

// CheckoutReferenceLTE applies the LTE predicate on the "checkout_reference" field.
func CheckoutReferenceLTE(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldLTE(FieldCheckoutReference, v))
}

// CheckoutReferenceContains applies the Contains predicate on the "checkout_reference" field.
func CheckoutReferenceContains(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldContains(FieldCheckoutReference, v))
}

// CheckoutReferenceHasPrefix applies the HasPrefix predicate on the "checkout_reference" field.
func CheckoutReferenceHasPrefix(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldHasPrefix(FieldCheckoutReference, v))
}

// CheckoutReferenceHasSuffix applies the HasSuffix predicate on the "checkout_reference" field.
func CheckoutReferenceHasSuffix(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldHasSuffix(FieldCheckoutReference, v))
}

// CheckoutReferenceEqualFold applies the EqualFold predicate on the "checkout_reference" field.
func CheckoutReferenceEqualFold(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldEqualFold(FieldCheckoutReference, v))
}

// CheckoutReferenceContainsFold applies the ContainsFold predicate on the "checkout_reference" field.
func CheckoutReferenceContainsFold(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldContainsFold(FieldCheckoutReference, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldContainsFold(FieldCurrency, v))
}

// TotalMinorEQ applies the EQ predicate on the "total_minor" field.
func TotalMinorEQ(v int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldEQ(FieldTotalMinor, v))
}

// TotalMinorNEQ applies the NEQ predicate on the "total_minor" field.
func TotalMinorNEQ(v int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldNEQ(FieldTotalMinor, v))
}

// TotalMinorIn applies the In predicate on the "total_minor" field.
func TotalMinorIn(vs ...int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldIn(FieldTotalMinor, vs...))
}

// TotalMinorNotIn applies the NotIn predicate on the "total_minor" field.
func TotalMinorNotIn(vs ...int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldNotIn(FieldTotalMinor, vs...))
}

// TotalMinorGT applies the GT predicate on the "total_minor" field.
func TotalMinorGT(v int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldGT(FieldTotalMinor, v))
}

// TotalMinorGTE applies the GTE predicate on the "total_minor" field.
func TotalMinorGTE(v int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldGTE(FieldTotalMinor, v))
}

// TotalMinorLT applies the LT predicate on the "total_minor" field.
func TotalMinorLT(v int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldLT(FieldTotalMinor, v))
}

// TotalMinorLTE applies the LTE predicate on the "total_minor" field.
func TotalMinorLTE(v int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldLTE(FieldTotalMinor, v))
}

// RefundedMinorEQ applies the EQ predicate on the "refunded_minor" field.
func RefundedMinorEQ(v int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldEQ(FieldRefundedMinor, v))
}

// RefundedMinorNEQ applies the NEQ predicate on the "refunded_minor" field.
func RefundedMinorNEQ(v int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldNEQ(FieldRefundedMinor, v))
}

// RefundedMinorIn applies the In predicate on the "refunded_minor" field.
func RefundedMinorIn(vs ...int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldIn(FieldRefundedMinor, vs...))
}

// RefundedMinorNotIn applies the NotIn predicate on the "refunded_minor" field.
func RefundedMinorNotIn(vs ...int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldNotIn(FieldRefundedMinor, vs...))
}

// RefundedMinorGT applies the GT predicate on the "refunded_minor" field.
func RefundedMinorGT(v int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldGT(FieldRefundedMinor, v))
}

// RefundedMinorGTE applies the GTE predicate on the "refunded_minor" field.
func RefundedMinorGTE(v int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldGTE(FieldRefundedMinor, v))
}

// RefundedMinorLT applies the LT predicate on the "refunded_minor" field.
func RefundedMinorLT(v int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldLT(FieldRefundedMinor, v))
}

// RefundedMinorLTE applies the LTE predicate on the "refunded_minor" field.
func RefundedMinorLTE(v int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldLTE(FieldRefundedMinor, v))
}

// CreditedUsdUnitsEQ applies the EQ predicate on the "credited_usd_units" field.
func CreditedUsdUnitsEQ(v int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldEQ(FieldCreditedUsdUnits, v))
}

// CreditedUsdUnitsNEQ applies the NEQ predicate on the "credited_usd_units" field.
func CreditedUsdUnitsNEQ(v int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldNEQ(FieldCreditedUsdUnits, v))
}

// CreditedUsdUnitsIn applies the In predicate on the "credited_usd_units" field.
func CreditedUsdUnitsIn(vs ...int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldIn(FieldCreditedUsdUnits, vs...))
}

// CreditedUsdUnitsNotIn applies the NotIn predicate on the "credited_usd_units" field.
func CreditedUsdUnitsNotIn(vs ...int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldNotIn(FieldCreditedUsdUnits, vs...))
}

// CreditedUsdUnitsGT applies the GT predicate on the "credited_usd_units" field.
func CreditedUsdUnitsGT(v int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldGT(FieldCreditedUsdUnits, v))
}

// CreditedUsdUnitsGTE applies the GTE predicate on the "credited_usd_units" field.
func CreditedUsdUnitsGTE(v int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldGTE(FieldCreditedUsdUnits, v))
}

// CreditedUsdUnitsLT applies the LT predicate on the "credited_usd_units" field.
func CreditedUsdUnitsLT(v int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldLT(FieldCreditedUsdUnits, v))
}

// CreditedUsdUnitsLTE applies the LTE predicate on the "credited_usd_units" field.
func CreditedUsdUnitsLTE(v int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldLTE(FieldCreditedUsdUnits, v))
}

// RefundTargetUsdUnitsEQ applies the EQ predicate on the "refund_target_usd_units" field.
func RefundTargetUsdUnitsEQ(v int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldEQ(FieldRefundTargetUsdUnits, v))
}

// RefundTargetUsdUnitsNEQ applies the NEQ predicate on the "refund_target_usd_units" field.
func RefundTargetUsdUnitsNEQ(v int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldNEQ(FieldRefundTargetUsdUnits, v))
}

// RefundTargetUsdUnitsIn applies the In predicate on the "refund_target_usd_units" field.
func RefundTargetUsdUnitsIn(vs ...int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldIn(FieldRefundTargetUsdUnits, vs...))
}

// RefundTargetUsdUnitsNotIn applies the NotIn predicate on the "refund_target_usd_units" field.
func RefundTargetUsdUnitsNotIn(vs ...int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldNotIn(FieldRefundTargetUsdUnits, vs...))
}

// RefundTargetUsdUnitsGT applies the GT predicate on the "refund_target_usd_units" field.
func RefundTargetUsdUnitsGT(v int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldGT(FieldRefundTargetUsdUnits, v))
}

// RefundTargetUsdUnitsGTE applies the GTE predicate on the "refund_target_usd_units" field.
func RefundTargetUsdUnitsGTE(v int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldGTE(FieldRefundTargetUsdUnits, v))
}

// RefundTargetUsdUnitsLT applies the LT predicate on the "refund_target_usd_units" field.
func RefundTargetUsdUnitsLT(v int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldLT(FieldRefundTargetUsdUnits, v))
}

// RefundTargetUsdUnitsLTE applies the LTE predicate on the "refund_target_usd_units" field.
func RefundTargetUsdUnitsLTE(v int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldLTE(FieldRefundTargetUsdUnits, v))
}

// RecoveredUsdUnitsEQ applies the EQ predicate on the "recovered_usd_units" field.
func RecoveredUsdUnitsEQ(v int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldEQ(FieldRecoveredUsdUnits, v))
}

// RecoveredUsdUnitsNEQ applies the NEQ predicate on the "recovered_usd_units" field.
func RecoveredUsdUnitsNEQ(v int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldNEQ(FieldRecoveredUsdUnits, v))
}

// RecoveredUsdUnitsIn applies the In predicate on the "recovered_usd_units" field.
func RecoveredUsdUnitsIn(vs ...int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldIn(FieldRecoveredUsdUnits, vs...))
}

// RecoveredUsdUnitsNotIn applies the NotIn predicate on the "recovered_usd_units" field.
func RecoveredUsdUnitsNotIn(vs ...int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldNotIn(FieldRecoveredUsdUnits, vs...))
}

// RecoveredUsdUnitsGT applies the GT predicate on the "recovered_usd_units" field.
func RecoveredUsdUnitsGT(v int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldGT(FieldRecoveredUsdUnits, v))
}

// RecoveredUsdUnitsGTE applies the GTE predicate on the "recovered_usd_units" field.
func RecoveredUsdUnitsGTE(v int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldGTE(FieldRecoveredUsdUnits, v))
}

// RecoveredUsdUnitsLT applies the LT predicate on the "recovered_usd_units" field.
func RecoveredUsdUnitsLT(v int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldLT(FieldRecoveredUsdUnits, v))
}

// RecoveredUsdUnitsLTE applies the LTE predicate on the "recovered_usd_units" field.
func RecoveredUsdUnitsLTE(v int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldLTE(FieldRecoveredUsdUnits, v))
}

// DebtUsdUnitsEQ applies the EQ predicate on the "debt_usd_units" field.
func DebtUsdUnitsEQ(v int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldEQ(FieldDebtUsdUnits, v))
}

// DebtUsdUnitsNEQ applies the NEQ predicate on the "debt_usd_units" field.
func DebtUsdUnitsNEQ(v int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldNEQ(FieldDebtUsdUnits, v))
}

// DebtUsdUnitsIn applies the In predicate on the "debt_usd_units" field.
func DebtUsdUnitsIn(vs ...int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldIn(FieldDebtUsdUnits, vs...))
}

// DebtUsdUnitsNotIn applies the NotIn predicate on the "debt_usd_units" field.
func DebtUsdUnitsNotIn(vs ...int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldNotIn(FieldDebtUsdUnits, vs...))
}

// DebtUsdUnitsGT applies the GT predicate on the "debt_usd_units" field.
func DebtUsdUnitsGT(v int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldGT(FieldDebtUsdUnits, v))
}

// DebtUsdUnitsGTE applies the GTE predicate on the "debt_usd_units" field.
func DebtUsdUnitsGTE(v int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldGTE(FieldDebtUsdUnits, v))
}

// DebtUsdUnitsLT applies the LT predicate on the "debt_usd_units" field.
func DebtUsdUnitsLT(v int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldLT(FieldDebtUsdUnits, v))
}

// DebtUsdUnitsLTE applies the LTE predicate on the "debt_usd_units" field.
func DebtUsdUnitsLTE(v int64) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldLTE(FieldDebtUsdUnits, v))
}

// PaymentStateEQ applies the EQ predicate on the "payment_state" field.
func PaymentStateEQ(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldEQ(FieldPaymentState, v))
}

// PaymentStateNEQ applies the NEQ predicate on the "payment_state" field.
func PaymentStateNEQ(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldNEQ(FieldPaymentState, v))
}

// PaymentStateIn applies the In predicate on the "payment_state" field.
func PaymentStateIn(vs ...string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldIn(FieldPaymentState, vs...))
}

// PaymentStateNotIn applies the NotIn predicate on the "payment_state" field.
func PaymentStateNotIn(vs ...string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldNotIn(FieldPaymentState, vs...))
}

// PaymentStateGT applies the GT predicate on the "payment_state" field.
func PaymentStateGT(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldGT(FieldPaymentState, v))
}

// PaymentStateGTE applies the GTE predicate on the "payment_state" field.
func PaymentStateGTE(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldGTE(FieldPaymentState, v))
}

// PaymentStateLT applies the LT predicate on the "payment_state" field.
func PaymentStateLT(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldLT(FieldPaymentState, v))
}

// PaymentStateLTE applies the LTE predicate on the "payment_state" field.
func PaymentStateLTE(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldLTE(FieldPaymentState, v))
}

// PaymentStateContains applies the Contains predicate on the "payment_state" field.
func PaymentStateContains(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldContains(FieldPaymentState, v))
}

// PaymentStateHasPrefix applies the HasPrefix predicate on the "payment_state" field.
func PaymentStateHasPrefix(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldHasPrefix(FieldPaymentState, v))
}

// PaymentStateHasSuffix applies the HasSuffix predicate on the "payment_state" field.
func PaymentStateHasSuffix(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldHasSuffix(FieldPaymentState, v))
}

// PaymentStateEqualFold applies the EqualFold predicate on the "payment_state" field.
func PaymentStateEqualFold(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldEqualFold(FieldPaymentState, v))
}

// PaymentStateContainsFold applies the ContainsFold predicate on the "payment_state" field.
func PaymentStateContainsFold(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldContainsFold(FieldPaymentState, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldContainsFold(FieldStatus, v))
}

// AnomalyCodeEQ applies the EQ predicate on the "anomaly_code" field.
func AnomalyCodeEQ(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldEQ(FieldAnomalyCode, v))
}

// AnomalyCodeNEQ applies the NEQ predicate on the "anomaly_code" field.
func AnomalyCodeNEQ(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldNEQ(FieldAnomalyCode, v))
}

// AnomalyCodeIn applies the In predicate on the "anomaly_code" field.
func AnomalyCodeIn(vs ...string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldIn(FieldAnomalyCode, vs...))
}

// AnomalyCodeNotIn applies the NotIn predicate on the "anomaly_code" field.
func AnomalyCodeNotIn(vs ...string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldNotIn(FieldAnomalyCode, vs...))
}

// AnomalyCodeGT applies the GT predicate on the "anomaly_code" field.
func AnomalyCodeGT(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldGT(FieldAnomalyCode, v))
}

// AnomalyCodeGTE applies the GTE predicate on the "anomaly_code" field.
func AnomalyCodeGTE(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldGTE(FieldAnomalyCode, v))
}

// AnomalyCodeLT applies the LT predicate on the "anomaly_code" field.
func AnomalyCodeLT(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldLT(FieldAnomalyCode, v))
}

// AnomalyCodeLTE applies the LTE predicate on the "anomaly_code" field.
func AnomalyCodeLTE(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldLTE(FieldAnomalyCode, v))
}

// AnomalyCodeContains applies the Contains predicate on the "anomaly_code" field.
func AnomalyCodeContains(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldContains(FieldAnomalyCode, v))
}

// AnomalyCodeHasPrefix applies the HasPrefix predicate on the "anomaly_code" field.
func AnomalyCodeHasPrefix(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldHasPrefix(FieldAnomalyCode, v))
}

// AnomalyCodeHasSuffix applies the HasSuffix predicate on the "anomaly_code" field.
func AnomalyCodeHasSuffix(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldHasSuffix(FieldAnomalyCode, v))
}

// AnomalyCodeEqualFold applies the EqualFold predicate on the "anomaly_code" field.
func AnomalyCodeEqualFold(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldEqualFold(FieldAnomalyCode, v))
}

// AnomalyCodeContainsFold applies the ContainsFold predicate on the "anomaly_code" field.
func AnomalyCodeContainsFold(v string) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldContainsFold(FieldAnomalyCode, v))
}

// PaidAtEQ applies the EQ predicate on the "paid_at" field.
func PaidAtEQ(v time.Time) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldEQ(FieldPaidAt, v))
}

// PaidAtNEQ applies the NEQ predicate on the "paid_at" field.
func PaidAtNEQ(v time.Time) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldNEQ(FieldPaidAt, v))
}

// PaidAtIn applies the In predicate on the "paid_at" field.
func PaidAtIn(vs ...time.Time) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldIn(FieldPaidAt, vs...))
}

// PaidAtNotIn applies the NotIn predicate on the "paid_at" field.
func PaidAtNotIn(vs ...time.Time) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldNotIn(FieldPaidAt, vs...))
}

// PaidAtGT applies the GT predicate on the "paid_at" field.
func PaidAtGT(v time.Time) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldGT(FieldPaidAt, v))
}

// PaidAtGTE applies the GTE predicate on the "paid_at" field.
func PaidAtGTE(v time.Time) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldGTE(FieldPaidAt, v))
}

// PaidAtLT applies the LT predicate on the "paid_at" field.
func PaidAtLT(v time.Time) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldLT(FieldPaidAt, v))
}

// PaidAtLTE applies the LTE predicate on the "paid_at" field.
func PaidAtLTE(v time.Time) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldLTE(FieldPaidAt, v))
}

// PaidAtIsNil applies the IsNil predicate on the "paid_at" field.
func PaidAtIsNil() predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldIsNull(FieldPaidAt))
}

// PaidAtNotNil applies the NotNil predicate on the "paid_at" field.
func PaidAtNotNil() predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldNotNull(FieldPaidAt))
}

// ProviderModifiedAtEQ applies the EQ predicate on the "provider_modified_at" field.
func ProviderModifiedAtEQ(v time.Time) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldEQ(FieldProviderModifiedAt, v))
}

// ProviderModifiedAtNEQ applies the NEQ predicate on the "provider_modified_at" field.
func ProviderModifiedAtNEQ(v time.Time) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldNEQ(FieldProviderModifiedAt, v))
}

// ProviderModifiedAtIn applies the In predicate on the "provider_modified_at" field.
func ProviderModifiedAtIn(vs ...time.Time) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldIn(FieldProviderModifiedAt, vs...))
}

// ProviderModifiedAtNotIn applies the NotIn predicate on the "provider_modified_at" field.
func ProviderModifiedAtNotIn(vs ...time.Time) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldNotIn(FieldProviderModifiedAt, vs...))
}

// ProviderModifiedAtGT applies the GT predicate on the "provider_modified_at" field.
func ProviderModifiedAtGT(v time.Time) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldGT(FieldProviderModifiedAt, v))
}

// ProviderModifiedAtGTE applies the GTE predicate on the "provider_modified_at" field.
func ProviderModifiedAtGTE(v time.Time) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldGTE(FieldProviderModifiedAt, v))
}

// ProviderModifiedAtLT applies the LT predicate on the "provider_modified_at" field.
func ProviderModifiedAtLT(v time.Time) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldLT(FieldProviderModifiedAt, v))
}

// ProviderModifiedAtLTE applies the LTE predicate on the "provider_modified_at" field.
func ProviderModifiedAtLTE(v time.Time) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldLTE(FieldProviderModifiedAt, v))
}

// ProviderModifiedAtIsNil applies the IsNil predicate on the "provider_modified_at" field.
func ProviderModifiedAtIsNil() predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldIsNull(FieldProviderModifiedAt))
}

// ProviderModifiedAtNotNil applies the NotNil predicate on the "provider_modified_at" field.
func ProviderModifiedAtNotNil() predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldNotNull(FieldProviderModifiedAt))
}

// LastSeenAtEQ applies the EQ predicate on the "last_seen_at" field.
func LastSeenAtEQ(v time.Time) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldEQ(FieldLastSeenAt, v))
}

// LastSeenAtNEQ applies the NEQ predicate on the "last_seen_at" field.
func LastSeenAtNEQ(v time.Time) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldNEQ(FieldLastSeenAt, v))
}

// LastSeenAtIn applies the In predicate on the "last_seen_at" field.
func LastSeenAtIn(vs ...time.Time) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldIn(FieldLastSeenAt, vs...))
}

// LastSeenAtNotIn applies the NotIn predicate on the "last_seen_at" field.
func LastSeenAtNotIn(vs ...time.Time) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldNotIn(FieldLastSeenAt, vs...))
}

// LastSeenAtGT applies the GT predicate on the "last_seen_at" field.
func LastSeenAtGT(v time.Time) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldGT(FieldLastSeenAt, v))
}

// LastSeenAtGTE applies the GTE predicate on the "last_seen_at" field.
func LastSeenAtGTE(v time.Time) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldGTE(FieldLastSeenAt, v))
}

// LastSeenAtLT applies the LT predicate on the "last_seen_at" field.
func LastSeenAtLT(v time.Time) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldLT(FieldLastSeenAt, v))
}

// LastSeenAtLTE applies the LTE predicate on the "last_seen_at" field.
func LastSeenAtLTE(v time.Time) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldLTE(FieldLastSeenAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PaymentExternalOrder) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PaymentExternalOrder) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PaymentExternalOrder) predicate.PaymentExternalOrder {
	return predicate.PaymentExternalOrder(sql.NotPredicates(p))
}
