// Code generated by ent, DO NOT EDIT.

package paymentsyncstate

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the paymentsyncstate type in the database.
	Label = "payment_sync_state"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldProviderKey holds the string denoting the provider_key field in the database.
	FieldProviderKey = "provider_key"
	// FieldWebsiteID holds the string denoting the website_id field in the database.
	FieldWebsiteID = "website_id"
	// FieldOauthClientID holds the string denoting the oauth_client_id field in the database.
	FieldOauthClientID = "oauth_client_id"
	// FieldEncryptedOauthCredentials holds the string denoting the encrypted_oauth_credentials field in the database.
	FieldEncryptedOauthCredentials = "encrypted_oauth_credentials"
	// FieldEncryptedOauthTokens holds the string denoting the encrypted_oauth_tokens field in the database.
	FieldEncryptedOauthTokens = "encrypted_oauth_tokens"
	// FieldTokenVersion holds the string denoting the token_version field in the database.
	FieldTokenVersion = "token_version"
	// FieldRotationPhase holds the string denoting the rotation_phase field in the database.
	FieldRotationPhase = "rotation_phase"
	// FieldRotationStartedAt holds the string denoting the rotation_started_at field in the database.
	FieldRotationStartedAt = "rotation_started_at"
	// FieldNextCursor holds the string denoting the next_cursor field in the database.
	FieldNextCursor = "next_cursor"
	// FieldWindowStart holds the string denoting the window_start field in the database.
	FieldWindowStart = "window_start"
	// FieldWindowEnd holds the string denoting the window_end field in the database.
	FieldWindowEnd = "window_end"
	// FieldLastSyncedAt holds the string denoting the last_synced_at field in the database.
	FieldLastSyncedAt = "last_synced_at"
	// FieldRetryAt holds the string denoting the retry_at field in the database.
	FieldRetryAt = "retry_at"
	// FieldLastErrorCode holds the string denoting the last_error_code field in the database.
	FieldLastErrorCode = "last_error_code"
	// FieldLeaseOwner holds the string denoting the lease_owner field in the database.
	FieldLeaseOwner = "lease_owner"
	// FieldLeaseUntil holds the string denoting the lease_until field in the database.
	FieldLeaseUntil = "lease_until"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the paymentsyncstate in the database.
	Table = "payment_sync_states"
)

// Columns holds all SQL columns for paymentsyncstate fields.
var Columns = []string{
	FieldID,
	FieldProviderKey,
	FieldWebsiteID,
	FieldOauthClientID,
	FieldEncryptedOauthCredentials,
	FieldEncryptedOauthTokens,
	FieldTokenVersion,
	FieldRotationPhase,
	FieldRotationStartedAt,
	FieldNextCursor,
	FieldWindowStart,
	FieldWindowEnd,
	FieldLastSyncedAt,
	FieldRetryAt,
	FieldLastErrorCode,
	FieldLeaseOwner,
	FieldLeaseUntil,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ProviderKeyValidator is a validator for the "provider_key" field. It is called by the builders before save.
	ProviderKeyValidator func(string) error
	// WebsiteIDValidator is a validator for the "website_id" field. It is called by the builders before save.
	WebsiteIDValidator func(string) error
	// DefaultOauthClientID holds the default value on creation for the "oauth_client_id" field.
	DefaultOauthClientID string
	// OauthClientIDValidator is a validator for the "oauth_client_id" field. It is called by the builders before save.
	OauthClientIDValidator func(string) error
	// DefaultEncryptedOauthCredentials holds the default value on creation for the "encrypted_oauth_credentials" field.
	DefaultEncryptedOauthCredentials string
	// DefaultEncryptedOauthTokens holds the default value on creation for the "encrypted_oauth_tokens" field.
	DefaultEncryptedOauthTokens string
	// DefaultTokenVersion holds the default value on creation for the "token_version" field.
	DefaultTokenVersion int64
	// DefaultRotationPhase holds the default value on creation for the "rotation_phase" field.
	DefaultRotationPhase string
	// RotationPhaseValidator is a validator for the "rotation_phase" field. It is called by the builders before save.
	RotationPhaseValidator func(string) error
	// DefaultNextCursor holds the default value on creation for the "next_cursor" field.
	DefaultNextCursor string
	// DefaultLastErrorCode holds the default value on creation for the "last_error_code" field.
	DefaultLastErrorCode string
	// LastErrorCodeValidator is a validator for the "last_error_code" field. It is called by the builders before save.
	LastErrorCodeValidator func(string) error
	// DefaultLeaseOwner holds the default value on creation for the "lease_owner" field.
	DefaultLeaseOwner string
	// LeaseOwnerValidator is a validator for the "lease_owner" field. It is called by the builders before save.
	LeaseOwnerValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the PaymentSyncState queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByProviderKey orders the results by the provider_key field.
func ByProviderKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderKey, opts...).ToFunc()
}

// ByWebsiteID orders the results by the website_id field.
func ByWebsiteID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWebsiteID, opts...).ToFunc()
}

// ByOauthClientID orders the results by the oauth_client_id field.
func ByOauthClientID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOauthClientID, opts...).ToFunc()
}

// ByEncryptedOauthCredentials orders the results by the encrypted_oauth_credentials field.
func ByEncryptedOauthCredentials(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEncryptedOauthCredentials, opts...).ToFunc()
}

// ByEncryptedOauthTokens orders the results by the encrypted_oauth_tokens field.
func ByEncryptedOauthTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEncryptedOauthTokens, opts...).ToFunc()
}

// ByTokenVersion orders the results by the token_version field.
func ByTokenVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTokenVersion, opts...).ToFunc()
}

// ByRotationPhase orders the results by the rotation_phase field.
func ByRotationPhase(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRotationPhase, opts...).ToFunc()
}

// ByRotationStartedAt orders the results by the rotation_started_at field.
func ByRotationStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRotationStartedAt, opts...).ToFunc()
}

// ByNextCursor orders the results by the next_cursor field.
func ByNextCursor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNextCursor, opts...).ToFunc()
}

// ByWindowStart orders the results by the window_start field.
func ByWindowStart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWindowStart, opts...).ToFunc()
}

// ByWindowEnd orders the results by the window_end field.
func ByWindowEnd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWindowEnd, opts...).ToFunc()
}

// ByLastSyncedAt orders the results by the last_synced_at field.
func ByLastSyncedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSyncedAt, opts...).ToFunc()
}

// ByRetryAt orders the results by the retry_at field.
func ByRetryAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRetryAt, opts...).ToFunc()
}

// ByLastErrorCode orders the results by the last_error_code field.
func ByLastErrorCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastErrorCode, opts...).ToFunc()
}

// ByLeaseOwner orders the results by the lease_owner field.
func ByLeaseOwner(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLeaseOwner, opts...).ToFunc()
}

// ByLeaseUntil orders the results by the lease_until field.
func ByLeaseUntil(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLeaseUntil, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
