// Code generated by ent, DO NOT EDIT.

package paymentsyncstate

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldLTE(FieldID, id))
}

// ProviderKey applies equality check predicate on the "provider_key" field. It's identical to ProviderKeyEQ.
func ProviderKey(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldEQ(FieldProviderKey, v))
}

// WebsiteID applies equality check predicate on the "website_id" field. It's identical to WebsiteIDEQ.
func WebsiteID(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldEQ(FieldWebsiteID, v))
}

// OauthClientID applies equality check predicate on the "oauth_client_id" field. It's identical to OauthClientIDEQ.
func OauthClientID(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldEQ(FieldOauthClientID, v))
}

// EncryptedOauthCredentials applies equality check predicate on the "encrypted_oauth_credentials" field. It's identical to EncryptedOauthCredentialsEQ.
func EncryptedOauthCredentials(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldEQ(FieldEncryptedOauthCredentials, v))
}

// EncryptedOauthTokens applies equality check predicate on the "encrypted_oauth_tokens" field. It's identical to EncryptedOauthTokensEQ.
func EncryptedOauthTokens(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldEQ(FieldEncryptedOauthTokens, v))
}

// TokenVersion applies equality check predicate on the "token_version" field. It's identical to TokenVersionEQ.
func TokenVersion(v int64) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldEQ(FieldTokenVersion, v))
}

// RotationPhase applies equality check predicate on the "rotation_phase" field. It's identical to RotationPhaseEQ.
func RotationPhase(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldEQ(FieldRotationPhase, v))
}

// RotationStartedAt applies equality check predicate on the "rotation_started_at" field. It's identical to RotationStartedAtEQ.
func RotationStartedAt(v time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldEQ(FieldRotationStartedAt, v))
}

// NextCursor applies equality check predicate on the "next_cursor" field. It's identical to NextCursorEQ.
func NextCursor(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldEQ(FieldNextCursor, v))
}

// WindowStart applies equality check predicate on the "window_start" field. It's identical to WindowStartEQ.
func WindowStart(v time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldEQ(FieldWindowStart, v))
}

// WindowEnd applies equality check predicate on the "window_end" field. It's identical to WindowEndEQ.
func WindowEnd(v time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldEQ(FieldWindowEnd, v))
}

// LastSyncedAt applies equality check predicate on the "last_synced_at" field. It's identical to LastSyncedAtEQ.
func LastSyncedAt(v time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldEQ(FieldLastSyncedAt, v))
}

// RetryAt applies equality check predicate on the "retry_at" field. It's identical to RetryAtEQ.
func RetryAt(v time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldEQ(FieldRetryAt, v))
}

// LastErrorCode applies equality check predicate on the "last_error_code" field. It's identical to LastErrorCodeEQ.
func LastErrorCode(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldEQ(FieldLastErrorCode, v))
}

// LeaseOwner applies equality check predicate on the "lease_owner" field. It's identical to LeaseOwnerEQ.
func LeaseOwner(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldEQ(FieldLeaseOwner, v))
}

// LeaseUntil applies equality check predicate on the "lease_until" field. It's identical to LeaseUntilEQ.
func LeaseUntil(v time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldEQ(FieldLeaseUntil, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldEQ(FieldUpdatedAt, v))
}

// ProviderKeyEQ applies the EQ predicate on the "provider_key" field.
func ProviderKeyEQ(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldEQ(FieldProviderKey, v))
}

// ProviderKeyNEQ applies the NEQ predicate on the "provider_key" field.
func ProviderKeyNEQ(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldNEQ(FieldProviderKey, v))
}

// ProviderKeyIn applies the In predicate on the "provider_key" field.
func ProviderKeyIn(vs ...string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldIn(FieldProviderKey, vs...))
}

// ProviderKeyNotIn applies the NotIn predicate on the "provider_key" field.
func ProviderKeyNotIn(vs ...string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldNotIn(FieldProviderKey, vs...))
}

// ProviderKeyGT applies the GT predicate on the "provider_key" field.
func ProviderKeyGT(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldGT(FieldProviderKey, v))
}

// ProviderKeyGTE applies the GTE predicate on the "provider_key" field.
func ProviderKeyGTE(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldGTE(FieldProviderKey, v))
}

// ProviderKeyLT applies the LT predicate on the "provider_key" field.
func ProviderKeyLT(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldLT(FieldProviderKey, v))
}

// ProviderKeyLTE applies the LTE predicate on the "provider_key" field.
func ProviderKeyLTE(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldLTE(FieldProviderKey, v))
}

// ProviderKeyContains applies the Contains predicate on the "provider_key" field.
func ProviderKeyContains(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldContains(FieldProviderKey, v))
}

// ProviderKeyHasPrefix applies the HasPrefix predicate on the "provider_key" field.
func ProviderKeyHasPrefix(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldHasPrefix(FieldProviderKey, v))
}

// ProviderKeyHasSuffix applies the HasSuffix predicate on the "provider_key" field.
func ProviderKeyHasSuffix(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldHasSuffix(FieldProviderKey, v))
}

// ProviderKeyEqualFold applies the EqualFold predicate on the "provider_key" field.
func ProviderKeyEqualFold(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldEqualFold(FieldProviderKey, v))
}

// ProviderKeyContainsFold applies the ContainsFold predicate on the "provider_key" field.
func ProviderKeyContainsFold(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldContainsFold(FieldProviderKey, v))
}

// WebsiteIDEQ applies the EQ predicate on the "website_id" field.
func WebsiteIDEQ(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldEQ(FieldWebsiteID, v))
}

// WebsiteIDNEQ applies the NEQ predicate on the "website_id" field.
func WebsiteIDNEQ(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldNEQ(FieldWebsiteID, v))
}

// WebsiteIDIn applies the In predicate on the "website_id" field.
func WebsiteIDIn(vs ...string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldIn(FieldWebsiteID, vs...))
}

// WebsiteIDNotIn applies the NotIn predicate on the "website_id" field.
func WebsiteIDNotIn(vs ...string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldNotIn(FieldWebsiteID, vs...))
}

// WebsiteIDGT applies the GT predicate on the "website_id" field.
func WebsiteIDGT(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldGT(FieldWebsiteID, v))
}

// WebsiteIDGTE applies the GTE predicate on the "website_id" field.
func WebsiteIDGTE(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldGTE(FieldWebsiteID, v))
}

// WebsiteIDLT applies the LT predicate on the "website_id" field.
func WebsiteIDLT(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldLT(FieldWebsiteID, v))
}

// WebsiteIDLTE applies the LTE predicate on the "website_id" field.
func WebsiteIDLTE(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldLTE(FieldWebsiteID, v))
}

// WebsiteIDContains applies the Contains predicate on the "website_id" field.
func WebsiteIDContains(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldContains(FieldWebsiteID, v))
}

// WebsiteIDHasPrefix applies the HasPrefix predicate on the "website_id" field.
func WebsiteIDHasPrefix(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldHasPrefix(FieldWebsiteID, v))
}

// WebsiteIDHasSuffix applies the HasSuffix predicate on the "website_id" field.
func WebsiteIDHasSuffix(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldHasSuffix(FieldWebsiteID, v))
}

// WebsiteIDEqualFold applies the EqualFold predicate on the "website_id" field.
func WebsiteIDEqualFold(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldEqualFold(FieldWebsiteID, v))
}

// WebsiteIDContainsFold applies the ContainsFold predicate on the "website_id" field.
func WebsiteIDContainsFold(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldContainsFold(FieldWebsiteID, v))
}

// OauthClientIDEQ applies the EQ predicate on the "oauth_client_id" field.
func OauthClientIDEQ(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldEQ(FieldOauthClientID, v))
}

// OauthClientIDNEQ applies the NEQ predicate on the "oauth_client_id" field.
func OauthClientIDNEQ(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldNEQ(FieldOauthClientID, v))
}

// OauthClientIDIn applies the In predicate on the "oauth_client_id" field.
func OauthClientIDIn(vs ...string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldIn(FieldOauthClientID, vs...))
}

// OauthClientIDNotIn applies the NotIn predicate on the "oauth_client_id" field.
func OauthClientIDNotIn(vs ...string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldNotIn(FieldOauthClientID, vs...))
}

// OauthClientIDGT applies the GT predicate on the "oauth_client_id" field.
func OauthClientIDGT(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldGT(FieldOauthClientID, v))
}

// OauthClientIDGTE applies the GTE predicate on the "oauth_client_id" field.
func OauthClientIDGTE(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldGTE(FieldOauthClientID, v))
}

// OauthClientIDLT applies the LT predicate on the "oauth_client_id" field.
func OauthClientIDLT(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldLT(FieldOauthClientID, v))
}

// OauthClientIDLTE applies the LTE predicate on the "oauth_client_id" field.
func OauthClientIDLTE(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldLTE(FieldOauthClientID, v))
}

// OauthClientIDContains applies the Contains predicate on the "oauth_client_id" field.
func OauthClientIDContains(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldContains(FieldOauthClientID, v))
}

// OauthClientIDHasPrefix applies the HasPrefix predicate on the "oauth_client_id" field.
func OauthClientIDHasPrefix(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldHasPrefix(FieldOauthClientID, v))
}

// OauthClientIDHasSuffix applies the HasSuffix predicate on the "oauth_client_id" field.
func OauthClientIDHasSuffix(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldHasSuffix(FieldOauthClientID, v))
}

// OauthClientIDEqualFold applies the EqualFold predicate on the "oauth_client_id" field.
func OauthClientIDEqualFold(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldEqualFold(FieldOauthClientID, v))
}

// OauthClientIDContainsFold applies the ContainsFold predicate on the "oauth_client_id" field.
func OauthClientIDContainsFold(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldContainsFold(FieldOauthClientID, v))
}

// EncryptedOauthCredentialsEQ applies the EQ predicate on the "encrypted_oauth_credentials" field.
func EncryptedOauthCredentialsEQ(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldEQ(FieldEncryptedOauthCredentials, v))
}

// EncryptedOauthCredentialsNEQ applies the NEQ predicate on the "encrypted_oauth_credentials" field.
func EncryptedOauthCredentialsNEQ(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldNEQ(FieldEncryptedOauthCredentials, v))
}

// EncryptedOauthCredentialsIn applies the In predicate on the "encrypted_oauth_credentials" field.
func EncryptedOauthCredentialsIn(vs ...string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldIn(FieldEncryptedOauthCredentials, vs...))
}

// EncryptedOauthCredentialsNotIn applies the NotIn predicate on the "encrypted_oauth_credentials" field.
func EncryptedOauthCredentialsNotIn(vs ...string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldNotIn(FieldEncryptedOauthCredentials, vs...))
}

// EncryptedOauthCredentialsGT applies the GT predicate on the "encrypted_oauth_credentials" field.
func EncryptedOauthCredentialsGT(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldGT(FieldEncryptedOauthCredentials, v))
}

// EncryptedOauthCredentialsGTE applies the GTE predicate on the "encrypted_oauth_credentials" field.
func EncryptedOauthCredentialsGTE(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldGTE(FieldEncryptedOauthCredentials, v))
}

// EncryptedOauthCredentialsLT applies the LT predicate on the "encrypted_oauth_credentials" field.
func EncryptedOauthCredentialsLT(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldLT(FieldEncryptedOauthCredentials, v))
}

// EncryptedOauthCredentialsLTE applies the LTE predicate on the "encrypted_oauth_credentials" field.
func EncryptedOauthCredentialsLTE(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldLTE(FieldEncryptedOauthCredentials, v))
}

// EncryptedOauthCredentialsContains applies the Contains predicate on the "encrypted_oauth_credentials" field.
func EncryptedOauthCredentialsContains(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldContains(FieldEncryptedOauthCredentials, v))
}

// EncryptedOauthCredentialsHasPrefix applies the HasPrefix predicate on the "encrypted_oauth_credentials" field.
func EncryptedOauthCredentialsHasPrefix(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldHasPrefix(FieldEncryptedOauthCredentials, v))
}

// EncryptedOauthCredentialsHasSuffix applies the HasSuffix predicate on the "encrypted_oauth_credentials" field.
func EncryptedOauthCredentialsHasSuffix(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldHasSuffix(FieldEncryptedOauthCredentials, v))
}

// EncryptedOauthCredentialsEqualFold applies the EqualFold predicate on the "encrypted_oauth_credentials" field.
func EncryptedOauthCredentialsEqualFold(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldEqualFold(FieldEncryptedOauthCredentials, v))
}

// EncryptedOauthCredentialsContainsFold applies the ContainsFold predicate on the "encrypted_oauth_credentials" field.
func EncryptedOauthCredentialsContainsFold(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldContainsFold(FieldEncryptedOauthCredentials, v))
}

// EncryptedOauthTokensEQ applies the EQ predicate on the "encrypted_oauth_tokens" field.
func EncryptedOauthTokensEQ(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldEQ(FieldEncryptedOauthTokens, v))
}

// EncryptedOauthTokensNEQ applies the NEQ predicate on the "encrypted_oauth_tokens" field.
func EncryptedOauthTokensNEQ(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldNEQ(FieldEncryptedOauthTokens, v))
}

// EncryptedOauthTokensIn applies the In predicate on the "encrypted_oauth_tokens" field.
func EncryptedOauthTokensIn(vs ...string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldIn(FieldEncryptedOauthTokens, vs...))
}

// EncryptedOauthTokensNotIn applies the NotIn predicate on the "encrypted_oauth_tokens" field.
func EncryptedOauthTokensNotIn(vs ...string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldNotIn(FieldEncryptedOauthTokens, vs...))
}

// EncryptedOauthTokensGT applies the GT predicate on the "encrypted_oauth_tokens" field.
func EncryptedOauthTokensGT(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldGT(FieldEncryptedOauthTokens, v))
}

// EncryptedOauthTokensGTE applies the GTE predicate on the "encrypted_oauth_tokens" field.
func EncryptedOauthTokensGTE(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldGTE(FieldEncryptedOauthTokens, v))
}

// EncryptedOauthTokensLT applies the LT predicate on the "encrypted_oauth_tokens" field.
func EncryptedOauthTokensLT(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldLT(FieldEncryptedOauthTokens, v))
}

// EncryptedOauthTokensLTE applies the LTE predicate on the "encrypted_oauth_tokens" field.
func EncryptedOauthTokensLTE(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldLTE(FieldEncryptedOauthTokens, v))
}

// EncryptedOauthTokensContains applies the Contains predicate on the "encrypted_oauth_tokens" field.
func EncryptedOauthTokensContains(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldContains(FieldEncryptedOauthTokens, v))
}

// EncryptedOauthTokensHasPrefix applies the HasPrefix predicate on the "encrypted_oauth_tokens" field.
func EncryptedOauthTokensHasPrefix(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldHasPrefix(FieldEncryptedOauthTokens, v))
}

// EncryptedOauthTokensHasSuffix applies the HasSuffix predicate on the "encrypted_oauth_tokens" field.
func EncryptedOauthTokensHasSuffix(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldHasSuffix(FieldEncryptedOauthTokens, v))
}

// EncryptedOauthTokensEqualFold applies the EqualFold predicate on the "encrypted_oauth_tokens" field.
func EncryptedOauthTokensEqualFold(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldEqualFold(FieldEncryptedOauthTokens, v))
}

// EncryptedOauthTokensContainsFold applies the ContainsFold predicate on the "encrypted_oauth_tokens" field.
func EncryptedOauthTokensContainsFold(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldContainsFold(FieldEncryptedOauthTokens, v))
}

// TokenVersionEQ applies the EQ predicate on the "token_version" field.
func TokenVersionEQ(v int64) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldEQ(FieldTokenVersion, v))
}

// TokenVersionNEQ applies the NEQ predicate on the "token_version" field.
func TokenVersionNEQ(v int64) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldNEQ(FieldTokenVersion, v))
}

// TokenVersionIn applies the In predicate on the "token_version" field.
func TokenVersionIn(vs ...int64) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldIn(FieldTokenVersion, vs...))
}

// TokenVersionNotIn applies the NotIn predicate on the "token_version" field.
func TokenVersionNotIn(vs ...int64) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldNotIn(FieldTokenVersion, vs...))
}

// TokenVersionGT applies the GT predicate on the "token_version" field.
func TokenVersionGT(v int64) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldGT(FieldTokenVersion, v))
}

// TokenVersionGTE applies the GTE predicate on the "token_version" field.
func TokenVersionGTE(v int64) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldGTE(FieldTokenVersion, v))
}

// TokenVersionLT applies the LT predicate on the "token_version" field.
func TokenVersionLT(v int64) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldLT(FieldTokenVersion, v))
}

// TokenVersionLTE applies the LTE predicate on the "token_version" field.
func TokenVersionLTE(v int64) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldLTE(FieldTokenVersion, v))
}

// RotationPhaseEQ applies the EQ predicate on the "rotation_phase" field.
func RotationPhaseEQ(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldEQ(FieldRotationPhase, v))
}

// RotationPhaseNEQ applies the NEQ predicate on the "rotation_phase" field.
func RotationPhaseNEQ(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldNEQ(FieldRotationPhase, v))
}

// RotationPhaseIn applies the In predicate on the "rotation_phase" field.
func RotationPhaseIn(vs ...string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldIn(FieldRotationPhase, vs...))
}

// RotationPhaseNotIn applies the NotIn predicate on the "rotation_phase" field.
func RotationPhaseNotIn(vs ...string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldNotIn(FieldRotationPhase, vs...))
}

// RotationPhaseGT applies the GT predicate on the "rotation_phase" field.
func RotationPhaseGT(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldGT(FieldRotationPhase, v))
}

// RotationPhaseGTE applies the GTE predicate on the "rotation_phase" field.
func RotationPhaseGTE(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldGTE(FieldRotationPhase, v))
}

// RotationPhaseLT applies the LT predicate on the "rotation_phase" field.
func RotationPhaseLT(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldLT(FieldRotationPhase, v))
}

// RotationPhaseLTE applies the LTE predicate on the "rotation_phase" field.
func RotationPhaseLTE(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldLTE(FieldRotationPhase, v))
}

// RotationPhaseContains applies the Contains predicate on the "rotation_phase" field.
func RotationPhaseContains(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldContains(FieldRotationPhase, v))
}

// RotationPhaseHasPrefix applies the HasPrefix predicate on the "rotation_phase" field.
func RotationPhaseHasPrefix(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldHasPrefix(FieldRotationPhase, v))
}

// RotationPhaseHasSuffix applies the HasSuffix predicate on the "rotation_phase" field.
func RotationPhaseHasSuffix(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldHasSuffix(FieldRotationPhase, v))
}

// RotationPhaseEqualFold applies the EqualFold predicate on the "rotation_phase" field.
func RotationPhaseEqualFold(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldEqualFold(FieldRotationPhase, v))
}

// RotationPhaseContainsFold applies the ContainsFold predicate on the "rotation_phase" field.
func RotationPhaseContainsFold(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldContainsFold(FieldRotationPhase, v))
}

// RotationStartedAtEQ applies the EQ predicate on the "rotation_started_at" field.
func RotationStartedAtEQ(v time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldEQ(FieldRotationStartedAt, v))
}

// RotationStartedAtNEQ applies the NEQ predicate on the "rotation_started_at" field.
func RotationStartedAtNEQ(v time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldNEQ(FieldRotationStartedAt, v))
}

// RotationStartedAtIn applies the In predicate on the "rotation_started_at" field.
func RotationStartedAtIn(vs ...time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldIn(FieldRotationStartedAt, vs...))
}

// RotationStartedAtNotIn applies the NotIn predicate on the "rotation_started_at" field.
func RotationStartedAtNotIn(vs ...time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldNotIn(FieldRotationStartedAt, vs...))
}

// RotationStartedAtGT applies the GT predicate on the "rotation_started_at" field.
func RotationStartedAtGT(v time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldGT(FieldRotationStartedAt, v))
}

// RotationStartedAtGTE applies the GTE predicate on the "rotation_started_at" field.
func RotationStartedAtGTE(v time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldGTE(FieldRotationStartedAt, v))
}

// RotationStartedAtLT applies the LT predicate on the "rotation_started_at" field.
func RotationStartedAtLT(v time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldLT(FieldRotationStartedAt, v))
}

// RotationStartedAtLTE applies the LTE predicate on the "rotation_started_at" field.
func RotationStartedAtLTE(v time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldLTE(FieldRotationStartedAt, v))
}

// RotationStartedAtIsNil applies the IsNil predicate on the "rotation_started_at" field.
func RotationStartedAtIsNil() predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldIsNull(FieldRotationStartedAt))
}

// RotationStartedAtNotNil applies the NotNil predicate on the "rotation_started_at" field.
func RotationStartedAtNotNil() predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldNotNull(FieldRotationStartedAt))
}

// NextCursorEQ applies the EQ predicate on the "next_cursor" field.
func NextCursorEQ(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldEQ(FieldNextCursor, v))
}

// NextCursorNEQ applies the NEQ predicate on the "next_cursor" field.
func NextCursorNEQ(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldNEQ(FieldNextCursor, v))
}

// NextCursorIn applies the In predicate on the "next_cursor" field.
func NextCursorIn(vs ...string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldIn(FieldNextCursor, vs...))
}

// NextCursorNotIn applies the NotIn predicate on the "next_cursor" field.
func NextCursorNotIn(vs ...string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldNotIn(FieldNextCursor, vs...))
}

// NextCursorGT applies the GT predicate on the "next_cursor" field.
func NextCursorGT(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldGT(FieldNextCursor, v))
}

// NextCursorGTE applies the GTE predicate on the "next_cursor" field.
func NextCursorGTE(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldGTE(FieldNextCursor, v))
}

// NextCursorLT applies the LT predicate on the "next_cursor" field.
func NextCursorLT(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldLT(FieldNextCursor, v))
}

// NextCursorLTE applies the LTE predicate on the "next_cursor" field.
func NextCursorLTE(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldLTE(FieldNextCursor, v))
}

// NextCursorContains applies the Contains predicate on the "next_cursor" field.
func NextCursorContains(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldContains(FieldNextCursor, v))
}

// NextCursorHasPrefix applies the HasPrefix predicate on the "next_cursor" field.
func NextCursorHasPrefix(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldHasPrefix(FieldNextCursor, v))
}

// NextCursorHasSuffix applies the HasSuffix predicate on the "next_cursor" field.
func NextCursorHasSuffix(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldHasSuffix(FieldNextCursor, v))
}

// NextCursorEqualFold applies the EqualFold predicate on the "next_cursor" field.
func NextCursorEqualFold(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldEqualFold(FieldNextCursor, v))
}

// NextCursorContainsFold applies the ContainsFold predicate on the "next_cursor" field.
func NextCursorContainsFold(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldContainsFold(FieldNextCursor, v))
}

// WindowStartEQ applies the EQ predicate on the "window_start" field.
func WindowStartEQ(v time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldEQ(FieldWindowStart, v))
}

// WindowStartNEQ applies the NEQ predicate on the "window_start" field.
func WindowStartNEQ(v time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldNEQ(FieldWindowStart, v))
}

// WindowStartIn applies the In predicate on the "window_start" field.
func WindowStartIn(vs ...time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldIn(FieldWindowStart, vs...))
}

// WindowStartNotIn applies the NotIn predicate on the "window_start" field.
func WindowStartNotIn(vs ...time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldNotIn(FieldWindowStart, vs...))
}

// WindowStartGT applies the GT predicate on the "window_start" field.
func WindowStartGT(v time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldGT(FieldWindowStart, v))
}

// WindowStartGTE applies the GTE predicate on the "window_start" field.
func WindowStartGTE(v time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldGTE(FieldWindowStart, v))
}

// WindowStartLT applies the LT predicate on the "window_start" field.
func WindowStartLT(v time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldLT(FieldWindowStart, v))
}

// WindowStartLTE applies the LTE predicate on the "window_start" field.
func WindowStartLTE(v time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldLTE(FieldWindowStart, v))
}

// WindowStartIsNil applies the IsNil predicate on the "window_start" field.
func WindowStartIsNil() predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldIsNull(FieldWindowStart))
}

// WindowStartNotNil applies the NotNil predicate on the "window_start" field.
func WindowStartNotNil() predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldNotNull(FieldWindowStart))
}

// WindowEndEQ applies the EQ predicate on the "window_end" field.
func WindowEndEQ(v time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldEQ(FieldWindowEnd, v))
}

// WindowEndNEQ applies the NEQ predicate on the "window_end" field.
func WindowEndNEQ(v time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldNEQ(FieldWindowEnd, v))
}

// WindowEndIn applies the In predicate on the "window_end" field.
func WindowEndIn(vs ...time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldIn(FieldWindowEnd, vs...))
}

// WindowEndNotIn applies the NotIn predicate on the "window_end" field.
func WindowEndNotIn(vs ...time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldNotIn(FieldWindowEnd, vs...))
}

// WindowEndGT applies the GT predicate on the "window_end" field.
func WindowEndGT(v time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldGT(FieldWindowEnd, v))
}

// WindowEndGTE applies the GTE predicate on the "window_end" field.
func WindowEndGTE(v time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldGTE(FieldWindowEnd, v))
}

// WindowEndLT applies the LT predicate on the "window_end" field.
func WindowEndLT(v time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldLT(FieldWindowEnd, v))
}

// WindowEndLTE applies the LTE predicate on the "window_end" field.
func WindowEndLTE(v time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldLTE(FieldWindowEnd, v))
}

// WindowEndIsNil applies the IsNil predicate on the "window_end" field.
func WindowEndIsNil() predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldIsNull(FieldWindowEnd))
}

// WindowEndNotNil applies the NotNil predicate on the "window_end" field.
func WindowEndNotNil() predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldNotNull(FieldWindowEnd))
}

// LastSyncedAtEQ applies the EQ predicate on the "last_synced_at" field.
func LastSyncedAtEQ(v time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldEQ(FieldLastSyncedAt, v))
}

// LastSyncedAtNEQ applies the NEQ predicate on the "last_synced_at" field.
func LastSyncedAtNEQ(v time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldNEQ(FieldLastSyncedAt, v))
}

// LastSyncedAtIn applies the In predicate on the "last_synced_at" field.
func LastSyncedAtIn(vs ...time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldIn(FieldLastSyncedAt, vs...))
}

// LastSyncedAtNotIn applies the NotIn predicate on the "last_synced_at" field.
func LastSyncedAtNotIn(vs ...time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldNotIn(FieldLastSyncedAt, vs...))
}

// LastSyncedAtGT applies the GT predicate on the "last_synced_at" field.
func LastSyncedAtGT(v time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldGT(FieldLastSyncedAt, v))
}

// LastSyncedAtGTE applies the GTE predicate on the "last_synced_at" field.
func LastSyncedAtGTE(v time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldGTE(FieldLastSyncedAt, v))
}

// LastSyncedAtLT applies the LT predicate on the "last_synced_at" field.
func LastSyncedAtLT(v time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldLT(FieldLastSyncedAt, v))
}

// LastSyncedAtLTE applies the LTE predicate on the "last_synced_at" field.
func LastSyncedAtLTE(v time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldLTE(FieldLastSyncedAt, v))
}

// LastSyncedAtIsNil applies the IsNil predicate on the "last_synced_at" field.
func LastSyncedAtIsNil() predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldIsNull(FieldLastSyncedAt))
}

// LastSyncedAtNotNil applies the NotNil predicate on the "last_synced_at" field.
func LastSyncedAtNotNil() predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldNotNull(FieldLastSyncedAt))
}

// RetryAtEQ applies the EQ predicate on the "retry_at" field.
func RetryAtEQ(v time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldEQ(FieldRetryAt, v))
}

// RetryAtNEQ applies the NEQ predicate on the "retry_at" field.
func RetryAtNEQ(v time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldNEQ(FieldRetryAt, v))
}

// RetryAtIn applies the In predicate on the "retry_at" field.
func RetryAtIn(vs ...time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldIn(FieldRetryAt, vs...))
}

// RetryAtNotIn applies the NotIn predicate on the "retry_at" field.
func RetryAtNotIn(vs ...time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldNotIn(FieldRetryAt, vs...))
}

// RetryAtGT applies the GT predicate on the "retry_at" field.
func RetryAtGT(v time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldGT(FieldRetryAt, v))
}

// RetryAtGTE applies the GTE predicate on the "retry_at" field.
func RetryAtGTE(v time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldGTE(FieldRetryAt, v))
}

// RetryAtLT applies the LT predicate on the "retry_at" field.
func RetryAtLT(v time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldLT(FieldRetryAt, v))
}

// RetryAtLTE applies the LTE predicate on the "retry_at" field.
func RetryAtLTE(v time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldLTE(FieldRetryAt, v))
}

// RetryAtIsNil applies the IsNil predicate on the "retry_at" field.
func RetryAtIsNil() predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldIsNull(FieldRetryAt))
}

// RetryAtNotNil applies the NotNil predicate on the "retry_at" field.
func RetryAtNotNil() predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldNotNull(FieldRetryAt))
}

// LastErrorCodeEQ applies the EQ predicate on the "last_error_code" field.
func LastErrorCodeEQ(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldEQ(FieldLastErrorCode, v))
}

// LastErrorCodeNEQ applies the NEQ predicate on the "last_error_code" field.
func LastErrorCodeNEQ(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldNEQ(FieldLastErrorCode, v))
}

// LastErrorCodeIn applies the In predicate on the "last_error_code" field.
func LastErrorCodeIn(vs ...string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldIn(FieldLastErrorCode, vs...))
}

// LastErrorCodeNotIn applies the NotIn predicate on the "last_error_code" field.
func LastErrorCodeNotIn(vs ...string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldNotIn(FieldLastErrorCode, vs...))
}

// LastErrorCodeGT applies the GT predicate on the "last_error_code" field.
func LastErrorCodeGT(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldGT(FieldLastErrorCode, v))
}

// LastErrorCodeGTE applies the GTE predicate on the "last_error_code" field.
func LastErrorCodeGTE(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldGTE(FieldLastErrorCode, v))
}

// LastErrorCodeLT applies the LT predicate on the "last_error_code" field.
func LastErrorCodeLT(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldLT(FieldLastErrorCode, v))
}

// LastErrorCodeLTE applies the LTE predicate on the "last_error_code" field.
func LastErrorCodeLTE(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldLTE(FieldLastErrorCode, v))
}

// LastErrorCodeContains applies the Contains predicate on the "last_error_code" field.
func LastErrorCodeContains(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldContains(FieldLastErrorCode, v))
}

// LastErrorCodeHasPrefix applies the HasPrefix predicate on the "last_error_code" field.
func LastErrorCodeHasPrefix(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldHasPrefix(FieldLastErrorCode, v))
}

// LastErrorCodeHasSuffix applies the HasSuffix predicate on the "last_error_code" field.
func LastErrorCodeHasSuffix(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldHasSuffix(FieldLastErrorCode, v))
}

// LastErrorCodeEqualFold applies the EqualFold predicate on the "last_error_code" field.
func LastErrorCodeEqualFold(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldEqualFold(FieldLastErrorCode, v))
}

// LastErrorCodeContainsFold applies the ContainsFold predicate on the "last_error_code" field.
func LastErrorCodeContainsFold(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldContainsFold(FieldLastErrorCode, v))
}

// LeaseOwnerEQ applies the EQ predicate on the "lease_owner" field.
func LeaseOwnerEQ(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldEQ(FieldLeaseOwner, v))
}

// LeaseOwnerNEQ applies the NEQ predicate on the "lease_owner" field.
func LeaseOwnerNEQ(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldNEQ(FieldLeaseOwner, v))
}

// LeaseOwnerIn applies the In predicate on the "lease_owner" field.
func LeaseOwnerIn(vs ...string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldIn(FieldLeaseOwner, vs...))
}

// LeaseOwnerNotIn applies the NotIn predicate on the "lease_owner" field.
func LeaseOwnerNotIn(vs ...string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldNotIn(FieldLeaseOwner, vs...))
}

// LeaseOwnerGT applies the GT predicate on the "lease_owner" field.
func LeaseOwnerGT(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldGT(FieldLeaseOwner, v))
}

// LeaseOwnerGTE applies the GTE predicate on the "lease_owner" field.
func LeaseOwnerGTE(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldGTE(FieldLeaseOwner, v))
}

// LeaseOwnerLT applies the LT predicate on the "lease_owner" field.
func LeaseOwnerLT(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldLT(FieldLeaseOwner, v))
}

// LeaseOwnerLTE applies the LTE predicate on the "lease_owner" field.
func LeaseOwnerLTE(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldLTE(FieldLeaseOwner, v))
}

// LeaseOwnerContains applies the Contains predicate on the "lease_owner" field.
func LeaseOwnerContains(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldContains(FieldLeaseOwner, v))
}

// LeaseOwnerHasPrefix applies the HasPrefix predicate on the "lease_owner" field.
func LeaseOwnerHasPrefix(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldHasPrefix(FieldLeaseOwner, v))
}

// LeaseOwnerHasSuffix applies the HasSuffix predicate on the "lease_owner" field.
func LeaseOwnerHasSuffix(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldHasSuffix(FieldLeaseOwner, v))
}

// LeaseOwnerEqualFold applies the EqualFold predicate on the "lease_owner" field.
func LeaseOwnerEqualFold(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldEqualFold(FieldLeaseOwner, v))
}

// LeaseOwnerContainsFold applies the ContainsFold predicate on the "lease_owner" field.
func LeaseOwnerContainsFold(v string) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldContainsFold(FieldLeaseOwner, v))
}

// LeaseUntilEQ applies the EQ predicate on the "lease_until" field.
func LeaseUntilEQ(v time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldEQ(FieldLeaseUntil, v))
}

// LeaseUntilNEQ applies the NEQ predicate on the "lease_until" field.
func LeaseUntilNEQ(v time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldNEQ(FieldLeaseUntil, v))
}

// LeaseUntilIn applies the In predicate on the "lease_until" field.
func LeaseUntilIn(vs ...time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldIn(FieldLeaseUntil, vs...))
}

// LeaseUntilNotIn applies the NotIn predicate on the "lease_until" field.
func LeaseUntilNotIn(vs ...time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldNotIn(FieldLeaseUntil, vs...))
}

// LeaseUntilGT applies the GT predicate on the "lease_until" field.
func LeaseUntilGT(v time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldGT(FieldLeaseUntil, v))
}

// LeaseUntilGTE applies the GTE predicate on the "lease_until" field.
func LeaseUntilGTE(v time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldGTE(FieldLeaseUntil, v))
}

// LeaseUntilLT applies the LT predicate on the "lease_until" field.
func LeaseUntilLT(v time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldLT(FieldLeaseUntil, v))
}

// LeaseUntilLTE applies the LTE predicate on the "lease_until" field.
func LeaseUntilLTE(v time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldLTE(FieldLeaseUntil, v))
}

// LeaseUntilIsNil applies the IsNil predicate on the "lease_until" field.
func LeaseUntilIsNil() predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldIsNull(FieldLeaseUntil))
}

// LeaseUntilNotNil applies the NotNil predicate on the "lease_until" field.
func LeaseUntilNotNil() predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldNotNull(FieldLeaseUntil))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PaymentSyncState) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PaymentSyncState) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PaymentSyncState) predicate.PaymentSyncState {
	return predicate.PaymentSyncState(sql.NotPredicates(p))
}
