// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/paymentexternalorder"
)

// PaymentExternalOrderCreate is the builder for creating a PaymentExternalOrder entity.
type PaymentExternalOrderCreate struct {
	config
	mutation *PaymentExternalOrderMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetProviderKey sets the "provider_key" field.
func (_c *PaymentExternalOrderCreate) SetProviderKey(v string) *PaymentExternalOrderCreate {
	_c.mutation.SetProviderKey(v)
	return _c
}

// SetWebsiteID sets the "website_id" field.
func (_c *PaymentExternalOrderCreate) SetWebsiteID(v string) *PaymentExternalOrderCreate {
	_c.mutation.SetWebsiteID(v)
	return _c
}

// SetExternalOrderID sets the "external_order_id" field.
func (_c *PaymentExternalOrderCreate) SetExternalOrderID(v string) *PaymentExternalOrderCreate {
	_c.mutation.SetExternalOrderID(v)
	return _c
}

// SetOrderNumber sets the "order_number" field.
func (_c *PaymentExternalOrderCreate) SetOrderNumber(v string) *PaymentExternalOrderCreate {
	_c.mutation.SetOrderNumber(v)
	return _c
}

// SetNillableOrderNumber sets the "order_number" field if the given value is not nil.
func (_c *PaymentExternalOrderCreate) SetNillableOrderNumber(v *string) *PaymentExternalOrderCreate {
	if v != nil {
		_c.SetOrderNumber(*v)
	}
	return _c
}

// SetBindingMethod sets the "binding_method" field.
func (_c *PaymentExternalOrderCreate) SetBindingMethod(v string) *PaymentExternalOrderCreate {
	_c.mutation.SetBindingMethod(v)
	return _c
}

// SetNillableBindingMethod sets the "binding_method" field if the given value is not nil.
func (_c *PaymentExternalOrderCreate) SetNillableBindingMethod(v *string) *PaymentExternalOrderCreate {
	if v != nil {
		_c.SetBindingMethod(*v)
	}
	return _c
}

// SetQuoteHash sets the "quote_hash" field.
func (_c *PaymentExternalOrderCreate) SetQuoteHash(v string) *PaymentExternalOrderCreate {
	_c.mutation.SetQuoteHash(v)
	return _c
}

// SetNillableQuoteHash sets the "quote_hash" field if the given value is not nil.
func (_c *PaymentExternalOrderCreate) SetNillableQuoteHash(v *string) *PaymentExternalOrderCreate {
	if v != nil {
		_c.SetQuoteHash(*v)
	}
	return _c
}

// SetLocalOrderID sets the "local_order_id" field.
func (_c *PaymentExternalOrderCreate) SetLocalOrderID(v int64) *PaymentExternalOrderCreate {
	_c.mutation.SetLocalOrderID(v)
	return _c
}

// SetNillableLocalOrderID sets the "local_order_id" field if the given value is not nil.
func (_c *PaymentExternalOrderCreate) SetNillableLocalOrderID(v *int64) *PaymentExternalOrderCreate {
	if v != nil {
		_c.SetLocalOrderID(*v)
	}
	return _c
}

// SetCheckoutReference sets the "checkout_reference" field.
func (_c *PaymentExternalOrderCreate) SetCheckoutReference(v string) *PaymentExternalOrderCreate {
	_c.mutation.SetCheckoutReference(v)
	return _c
}

// SetNillableCheckoutReference sets the "checkout_reference" field if the given value is not nil.
func (_c *PaymentExternalOrderCreate) SetNillableCheckoutReference(v *string) *PaymentExternalOrderCreate {
	if v != nil {
		_c.SetCheckoutReference(*v)
	}
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *PaymentExternalOrderCreate) SetCurrency(v string) *PaymentExternalOrderCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_c *PaymentExternalOrderCreate) SetNillableCurrency(v *string) *PaymentExternalOrderCreate {
	if v != nil {
		_c.SetCurrency(*v)
	}
	return _c
}

// SetTotalMinor sets the "total_minor" field.
func (_c *PaymentExternalOrderCreate) SetTotalMinor(v int64) *PaymentExternalOrderCreate {
	_c.mutation.SetTotalMinor(v)
	return _c
}

// SetNillableTotalMinor sets the "total_minor" field if the given value is not nil.
func (_c *PaymentExternalOrderCreate) SetNillableTotalMinor(v *int64) *PaymentExternalOrderCreate {
	if v != nil {
		_c.SetTotalMinor(*v)
	}
	return _c
}

// SetRefundedMinor sets the "refunded_minor" field.
func (_c *PaymentExternalOrderCreate) SetRefundedMinor(v int64) *PaymentExternalOrderCreate {
	_c.mutation.SetRefundedMinor(v)
	return _c
}

// SetNillableRefundedMinor sets the "refunded_minor" field if the given value is not nil.
func (_c *PaymentExternalOrderCreate) SetNillableRefundedMinor(v *int64) *PaymentExternalOrderCreate {
	if v != nil {
		_c.SetRefundedMinor(*v)
	}
	return _c
}

// SetCreditedUsdUnits sets the "credited_usd_units" field.
func (_c *PaymentExternalOrderCreate) SetCreditedUsdUnits(v int64) *PaymentExternalOrderCreate {
	_c.mutation.SetCreditedUsdUnits(v)
	return _c
}

// SetNillableCreditedUsdUnits sets the "credited_usd_units" field if the given value is not nil.
func (_c *PaymentExternalOrderCreate) SetNillableCreditedUsdUnits(v *int64) *PaymentExternalOrderCreate {
	if v != nil {
		_c.SetCreditedUsdUnits(*v)
	}
	return _c
}

// SetRefundTargetUsdUnits sets the "refund_target_usd_units" field.
func (_c *PaymentExternalOrderCreate) SetRefundTargetUsdUnits(v int64) *PaymentExternalOrderCreate {
	_c.mutation.SetRefundTargetUsdUnits(v)
	return _c
}

// SetNillableRefundTargetUsdUnits sets the "refund_target_usd_units" field if the given value is not nil.
func (_c *PaymentExternalOrderCreate) SetNillableRefundTargetUsdUnits(v *int64) *PaymentExternalOrderCreate {
	if v != nil {
		_c.SetRefundTargetUsdUnits(*v)
	}
	return _c
}

// SetRecoveredUsdUnits sets the "recovered_usd_units" field.
func (_c *PaymentExternalOrderCreate) SetRecoveredUsdUnits(v int64) *PaymentExternalOrderCreate {
	_c.mutation.SetRecoveredUsdUnits(v)
	return _c
}

// SetNillableRecoveredUsdUnits sets the "recovered_usd_units" field if the given value is not nil.
func (_c *PaymentExternalOrderCreate) SetNillableRecoveredUsdUnits(v *int64) *PaymentExternalOrderCreate {
	if v != nil {
		_c.SetRecoveredUsdUnits(*v)
	}
	return _c
}

// SetDebtUsdUnits sets the "debt_usd_units" field.
func (_c *PaymentExternalOrderCreate) SetDebtUsdUnits(v int64) *PaymentExternalOrderCreate {
	_c.mutation.SetDebtUsdUnits(v)
	return _c
}

// SetNillableDebtUsdUnits sets the "debt_usd_units" field if the given value is not nil.
func (_c *PaymentExternalOrderCreate) SetNillableDebtUsdUnits(v *int64) *PaymentExternalOrderCreate {
	if v != nil {
		_c.SetDebtUsdUnits(*v)
	}
	return _c
}

// SetPaymentState sets the "payment_state" field.
func (_c *PaymentExternalOrderCreate) SetPaymentState(v string) *PaymentExternalOrderCreate {
	_c.mutation.SetPaymentState(v)
	return _c
}

// SetNillablePaymentState sets the "payment_state" field if the given value is not nil.
func (_c *PaymentExternalOrderCreate) SetNillablePaymentState(v *string) *PaymentExternalOrderCreate {
	if v != nil {
		_c.SetPaymentState(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *PaymentExternalOrderCreate) SetStatus(v string) *PaymentExternalOrderCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *PaymentExternalOrderCreate) SetNillableStatus(v *string) *PaymentExternalOrderCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetAnomalyCode sets the "anomaly_code" field.
func (_c *PaymentExternalOrderCreate) SetAnomalyCode(v string) *PaymentExternalOrderCreate {
	_c.mutation.SetAnomalyCode(v)
	return _c
}

// SetNillableAnomalyCode sets the "anomaly_code" field if the given value is not nil.
func (_c *PaymentExternalOrderCreate) SetNillableAnomalyCode(v *string) *PaymentExternalOrderCreate {
	if v != nil {
		_c.SetAnomalyCode(*v)
	}
	return _c
}

// SetPaidAt sets the "paid_at" field.
func (_c *PaymentExternalOrderCreate) SetPaidAt(v time.Time) *PaymentExternalOrderCreate {
	_c.mutation.SetPaidAt(v)
	return _c
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_c *PaymentExternalOrderCreate) SetNillablePaidAt(v *time.Time) *PaymentExternalOrderCreate {
	if v != nil {
		_c.SetPaidAt(*v)
	}
	return _c
}

// SetProviderModifiedAt sets the "provider_modified_at" field.
func (_c *PaymentExternalOrderCreate) SetProviderModifiedAt(v time.Time) *PaymentExternalOrderCreate {
	_c.mutation.SetProviderModifiedAt(v)
	return _c
}

// SetNillableProviderModifiedAt sets the "provider_modified_at" field if the given value is not nil.
func (_c *PaymentExternalOrderCreate) SetNillableProviderModifiedAt(v *time.Time) *PaymentExternalOrderCreate {
	if v != nil {
		_c.SetProviderModifiedAt(*v)
	}
	return _c
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_c *PaymentExternalOrderCreate) SetLastSeenAt(v time.Time) *PaymentExternalOrderCreate {
	_c.mutation.SetLastSeenAt(v)
	return _c
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_c *PaymentExternalOrderCreate) SetNillableLastSeenAt(v *time.Time) *PaymentExternalOrderCreate {
	if v != nil {
		_c.SetLastSeenAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PaymentExternalOrderCreate) SetCreatedAt(v time.Time) *PaymentExternalOrderCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PaymentExternalOrderCreate) SetNillableCreatedAt(v *time.Time) *PaymentExternalOrderCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PaymentExternalOrderCreate) SetUpdatedAt(v time.Time) *PaymentExternalOrderCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PaymentExternalOrderCreate) SetNillableUpdatedAt(v *time.Time) *PaymentExternalOrderCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the PaymentExternalOrderMutation object of the builder.
func (_c *PaymentExternalOrderCreate) Mutation() *PaymentExternalOrderMutation {
	return _c.mutation
}

// Save creates the PaymentExternalOrder in the database.
func (_c *PaymentExternalOrderCreate) Save(ctx context.Context) (*PaymentExternalOrder, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PaymentExternalOrderCreate) SaveX(ctx context.Context) *PaymentExternalOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PaymentExternalOrderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PaymentExternalOrderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PaymentExternalOrderCreate) defaults() {
	if _, ok := _c.mutation.OrderNumber(); !ok {
		v := paymentexternalorder.DefaultOrderNumber
		_c.mutation.SetOrderNumber(v)
	}
	if _, ok := _c.mutation.BindingMethod(); !ok {
		v := paymentexternalorder.DefaultBindingMethod
		_c.mutation.SetBindingMethod(v)
	}
	if _, ok := _c.mutation.QuoteHash(); !ok {
		v := paymentexternalorder.DefaultQuoteHash
		_c.mutation.SetQuoteHash(v)
	}
	if _, ok := _c.mutation.CheckoutReference(); !ok {
		v := paymentexternalorder.DefaultCheckoutReference
		_c.mutation.SetCheckoutReference(v)
	}
	if _, ok := _c.mutation.Currency(); !ok {
		v := paymentexternalorder.DefaultCurrency
		_c.mutation.SetCurrency(v)
	}
	if _, ok := _c.mutation.TotalMinor(); !ok {
		v := paymentexternalorder.DefaultTotalMinor
		_c.mutation.SetTotalMinor(v)
	}
	if _, ok := _c.mutation.RefundedMinor(); !ok {
		v := paymentexternalorder.DefaultRefundedMinor
		_c.mutation.SetRefundedMinor(v)
	}
	if _, ok := _c.mutation.CreditedUsdUnits(); !ok {
		v := paymentexternalorder.DefaultCreditedUsdUnits
		_c.mutation.SetCreditedUsdUnits(v)
	}
	if _, ok := _c.mutation.RefundTargetUsdUnits(); !ok {
		v := paymentexternalorder.DefaultRefundTargetUsdUnits
		_c.mutation.SetRefundTargetUsdUnits(v)
	}
	if _, ok := _c.mutation.RecoveredUsdUnits(); !ok {
		v := paymentexternalorder.DefaultRecoveredUsdUnits
		_c.mutation.SetRecoveredUsdUnits(v)
	}
	if _, ok := _c.mutation.DebtUsdUnits(); !ok {
		v := paymentexternalorder.DefaultDebtUsdUnits
		_c.mutation.SetDebtUsdUnits(v)
	}
	if _, ok := _c.mutation.PaymentState(); !ok {
		v := paymentexternalorder.DefaultPaymentState
		_c.mutation.SetPaymentState(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := paymentexternalorder.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.AnomalyCode(); !ok {
		v := paymentexternalorder.DefaultAnomalyCode
		_c.mutation.SetAnomalyCode(v)
	}
	if _, ok := _c.mutation.LastSeenAt(); !ok {
		v := paymentexternalorder.DefaultLastSeenAt()
		_c.mutation.SetLastSeenAt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := paymentexternalorder.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := paymentexternalorder.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PaymentExternalOrderCreate) check() error {
	if _, ok := _c.mutation.ProviderKey(); !ok {
		return &ValidationError{Name: "provider_key", err: errors.New(`ent: missing required field "PaymentExternalOrder.provider_key"`)}
	}
	if v, ok := _c.mutation.ProviderKey(); ok {
		if err := paymentexternalorder.ProviderKeyValidator(v); err != nil {
			return &ValidationError{Name: "provider_key", err: fmt.Errorf(`ent: validator failed for field "PaymentExternalOrder.provider_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.WebsiteID(); !ok {
		return &ValidationError{Name: "website_id", err: errors.New(`ent: missing required field "PaymentExternalOrder.website_id"`)}
	}
	if v, ok := _c.mutation.WebsiteID(); ok {
		if err := paymentexternalorder.WebsiteIDValidator(v); err != nil {
			return &ValidationError{Name: "website_id", err: fmt.Errorf(`ent: validator failed for field "PaymentExternalOrder.website_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExternalOrderID(); !ok {
		return &ValidationError{Name: "external_order_id", err: errors.New(`ent: missing required field "PaymentExternalOrder.external_order_id"`)}
	}
	if v, ok := _c.mutation.ExternalOrderID(); ok {
		if err := paymentexternalorder.ExternalOrderIDValidator(v); err != nil {
			return &ValidationError{Name: "external_order_id", err: fmt.Errorf(`ent: validator failed for field "PaymentExternalOrder.external_order_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OrderNumber(); !ok {
		return &ValidationError{Name: "order_number", err: errors.New(`ent: missing required field "PaymentExternalOrder.order_number"`)}
	}
	if v, ok := _c.mutation.OrderNumber(); ok {
		if err := paymentexternalorder.OrderNumberValidator(v); err != nil {
			return &ValidationError{Name: "order_number", err: fmt.Errorf(`ent: validator failed for field "PaymentExternalOrder.order_number": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BindingMethod(); !ok {
		return &ValidationError{Name: "binding_method", err: errors.New(`ent: missing required field "PaymentExternalOrder.binding_method"`)}
	}
	if v, ok := _c.mutation.BindingMethod(); ok {
		if err := paymentexternalorder.BindingMethodValidator(v); err != nil {
			return &ValidationError{Name: "binding_method", err: fmt.Errorf(`ent: validator failed for field "PaymentExternalOrder.binding_method": %w`, err)}
		}
	}
	if _, ok := _c.mutation.QuoteHash(); !ok {
		return &ValidationError{Name: "quote_hash", err: errors.New(`ent: missing required field "PaymentExternalOrder.quote_hash"`)}
	}
	if v, ok := _c.mutation.QuoteHash(); ok {
		if err := paymentexternalorder.QuoteHashValidator(v); err != nil {
			return &ValidationError{Name: "quote_hash", err: fmt.Errorf(`ent: validator failed for field "PaymentExternalOrder.quote_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CheckoutReference(); !ok {
		return &ValidationError{Name: "checkout_reference", err: errors.New(`ent: missing required field "PaymentExternalOrder.checkout_reference"`)}
	}
	if v, ok := _c.mutation.CheckoutReference(); ok {
		if err := paymentexternalorder.CheckoutReferenceValidator(v); err != nil {
			return &ValidationError{Name: "checkout_reference", err: fmt.Errorf(`ent: validator failed for field "PaymentExternalOrder.checkout_reference": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "PaymentExternalOrder.currency"`)}
	}
	if v, ok := _c.mutation.Currency(); ok {
		if err := paymentexternalorder.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "PaymentExternalOrder.currency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TotalMinor(); !ok {
		return &ValidationError{Name: "total_minor", err: errors.New(`ent: missing required field "PaymentExternalOrder.total_minor"`)}
	}
	if _, ok := _c.mutation.RefundedMinor(); !ok {
		return &ValidationError{Name: "refunded_minor", err: errors.New(`ent: missing required field "PaymentExternalOrder.refunded_minor"`)}
	}
	if _, ok := _c.mutation.CreditedUsdUnits(); !ok {
		return &ValidationError{Name: "credited_usd_units", err: errors.New(`ent: missing required field "PaymentExternalOrder.credited_usd_units"`)}
	}
	if _, ok := _c.mutation.RefundTargetUsdUnits(); !ok {
		return &ValidationError{Name: "refund_target_usd_units", err: errors.New(`ent: missing required field "PaymentExternalOrder.refund_target_usd_units"`)}
	}
	if _, ok := _c.mutation.RecoveredUsdUnits(); !ok {
		return &ValidationError{Name: "recovered_usd_units", err: errors.New(`ent: missing required field "PaymentExternalOrder.recovered_usd_units"`)}
	}
	if _, ok := _c.mutation.DebtUsdUnits(); !ok {
		return &ValidationError{Name: "debt_usd_units", err: errors.New(`ent: missing required field "PaymentExternalOrder.debt_usd_units"`)}
	}
	if _, ok := _c.mutation.PaymentState(); !ok {
		return &ValidationError{Name: "payment_state", err: errors.New(`ent: missing required field "PaymentExternalOrder.payment_state"`)}
	}
	if v, ok := _c.mutation.PaymentState(); ok {
		if err := paymentexternalorder.PaymentStateValidator(v); err != nil {
			return &ValidationError{Name: "payment_state", err: fmt.Errorf(`ent: validator failed for field "PaymentExternalOrder.payment_state": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "PaymentExternalOrder.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := paymentexternalorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PaymentExternalOrder.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AnomalyCode(); !ok {
		return &ValidationError{Name: "anomaly_code", err: errors.New(`ent: missing required field "PaymentExternalOrder.anomaly_code"`)}
	}
	if v, ok := _c.mutation.AnomalyCode(); ok {
		if err := paymentexternalorder.AnomalyCodeValidator(v); err != nil {
			return &ValidationError{Name: "anomaly_code", err: fmt.Errorf(`ent: validator failed for field "PaymentExternalOrder.anomaly_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LastSeenAt(); !ok {
		return &ValidationError{Name: "last_seen_at", err: errors.New(`ent: missing required field "PaymentExternalOrder.last_seen_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PaymentExternalOrder.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PaymentExternalOrder.updated_at"`)}
	}
	return nil
}

func (_c *PaymentExternalOrderCreate) sqlSave(ctx context.Context) (*PaymentExternalOrder, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PaymentExternalOrderCreate) createSpec() (*PaymentExternalOrder, *sqlgraph.CreateSpec) {
	var (
		_node = &PaymentExternalOrder{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(paymentexternalorder.Table, sqlgraph.NewFieldSpec(paymentexternalorder.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.ProviderKey(); ok {
		_spec.SetField(paymentexternalorder.FieldProviderKey, field.TypeString, value)
		_node.ProviderKey = value
	}
	if value, ok := _c.mutation.WebsiteID(); ok {
		_spec.SetField(paymentexternalorder.FieldWebsiteID, field.TypeString, value)
		_node.WebsiteID = value
	}
	if value, ok := _c.mutation.ExternalOrderID(); ok {
		_spec.SetField(paymentexternalorder.FieldExternalOrderID, field.TypeString, value)
		_node.ExternalOrderID = value
	}
	if value, ok := _c.mutation.OrderNumber(); ok {
		_spec.SetField(paymentexternalorder.FieldOrderNumber, field.TypeString, value)
		_node.OrderNumber = value
	}
	if value, ok := _c.mutation.BindingMethod(); ok {
		_spec.SetField(paymentexternalorder.FieldBindingMethod, field.TypeString, value)
		_node.BindingMethod = value
	}
	if value, ok := _c.mutation.QuoteHash(); ok {
		_spec.SetField(paymentexternalorder.FieldQuoteHash, field.TypeString, value)
		_node.QuoteHash = value
	}
	if value, ok := _c.mutation.LocalOrderID(); ok {
		_spec.SetField(paymentexternalorder.FieldLocalOrderID, field.TypeInt64, value)
		_node.LocalOrderID = &value
	}
	if value, ok := _c.mutation.CheckoutReference(); ok {
		_spec.SetField(paymentexternalorder.FieldCheckoutReference, field.TypeString, value)
		_node.CheckoutReference = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(paymentexternalorder.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.TotalMinor(); ok {
		_spec.SetField(paymentexternalorder.FieldTotalMinor, field.TypeInt64, value)
		_node.TotalMinor = value
	}
	if value, ok := _c.mutation.RefundedMinor(); ok {
		_spec.SetField(paymentexternalorder.FieldRefundedMinor, field.TypeInt64, value)
		_node.RefundedMinor = value
	}
	if value, ok := _c.mutation.CreditedUsdUnits(); ok {
		_spec.SetField(paymentexternalorder.FieldCreditedUsdUnits, field.TypeInt64, value)
		_node.CreditedUsdUnits = value
	}
	if value, ok := _c.mutation.RefundTargetUsdUnits(); ok {
		_spec.SetField(paymentexternalorder.FieldRefundTargetUsdUnits, field.TypeInt64, value)
		_node.RefundTargetUsdUnits = value
	}
	if value, ok := _c.mutation.RecoveredUsdUnits(); ok {
		_spec.SetField(paymentexternalorder.FieldRecoveredUsdUnits, field.TypeInt64, value)
		_node.RecoveredUsdUnits = value
	}
	if value, ok := _c.mutation.DebtUsdUnits(); ok {
		_spec.SetField(paymentexternalorder.FieldDebtUsdUnits, field.TypeInt64, value)
		_node.DebtUsdUnits = value
	}
	if value, ok := _c.mutation.PaymentState(); ok {
		_spec.SetField(paymentexternalorder.FieldPaymentState, field.TypeString, value)
		_node.PaymentState = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(paymentexternalorder.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.AnomalyCode(); ok {
		_spec.SetField(paymentexternalorder.FieldAnomalyCode, field.TypeString, value)
		_node.AnomalyCode = value
	}
	if value, ok := _c.mutation.PaidAt(); ok {
		_spec.SetField(paymentexternalorder.FieldPaidAt, field.TypeTime, value)
		_node.PaidAt = &value
	}
	if value, ok := _c.mutation.ProviderModifiedAt(); ok {
		_spec.SetField(paymentexternalorder.FieldProviderModifiedAt, field.TypeTime, value)
		_node.ProviderModifiedAt = &value
	}
	if value, ok := _c.mutation.LastSeenAt(); ok {
		_spec.SetField(paymentexternalorder.FieldLastSeenAt, field.TypeTime, value)
		_node.LastSeenAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(paymentexternalorder.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentexternalorder.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PaymentExternalOrder.Create().
//		SetProviderKey(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PaymentExternalOrderUpsert) {
//			SetProviderKey(v+v).
//		}).
//		Exec(ctx)
func (_c *PaymentExternalOrderCreate) OnConflict(opts ...sql.ConflictOption) *PaymentExternalOrderUpsertOne {
	_c.conflict = opts
	return &PaymentExternalOrderUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PaymentExternalOrder.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PaymentExternalOrderCreate) OnConflictColumns(columns ...string) *PaymentExternalOrderUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PaymentExternalOrderUpsertOne{
		create: _c,
	}
}

type (
	// PaymentExternalOrderUpsertOne is the builder for "upsert"-ing
	//  one PaymentExternalOrder node.
	PaymentExternalOrderUpsertOne struct {
		create *PaymentExternalOrderCreate
	}

	// PaymentExternalOrderUpsert is the "OnConflict" setter.
	PaymentExternalOrderUpsert struct {
		*sql.UpdateSet
	}
)

// SetProviderKey sets the "provider_key" field.
func (u *PaymentExternalOrderUpsert) SetProviderKey(v string) *PaymentExternalOrderUpsert {
	u.Set(paymentexternalorder.FieldProviderKey, v)
	return u
}

// UpdateProviderKey sets the "provider_key" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsert) UpdateProviderKey() *PaymentExternalOrderUpsert {
	u.SetExcluded(paymentexternalorder.FieldProviderKey)
	return u
}

// SetWebsiteID sets the "website_id" field.
func (u *PaymentExternalOrderUpsert) SetWebsiteID(v string) *PaymentExternalOrderUpsert {
	u.Set(paymentexternalorder.FieldWebsiteID, v)
	return u
}

// UpdateWebsiteID sets the "website_id" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsert) UpdateWebsiteID() *PaymentExternalOrderUpsert {
	u.SetExcluded(paymentexternalorder.FieldWebsiteID)
	return u
}

// SetExternalOrderID sets the "external_order_id" field.
func (u *PaymentExternalOrderUpsert) SetExternalOrderID(v string) *PaymentExternalOrderUpsert {
	u.Set(paymentexternalorder.FieldExternalOrderID, v)
	return u
}

// UpdateExternalOrderID sets the "external_order_id" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsert) UpdateExternalOrderID() *PaymentExternalOrderUpsert {
	u.SetExcluded(paymentexternalorder.FieldExternalOrderID)
	return u
}

// SetOrderNumber sets the "order_number" field.
func (u *PaymentExternalOrderUpsert) SetOrderNumber(v string) *PaymentExternalOrderUpsert {
	u.Set(paymentexternalorder.FieldOrderNumber, v)
	return u
}

// UpdateOrderNumber sets the "order_number" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsert) UpdateOrderNumber() *PaymentExternalOrderUpsert {
	u.SetExcluded(paymentexternalorder.FieldOrderNumber)
	return u
}

// SetBindingMethod sets the "binding_method" field.
func (u *PaymentExternalOrderUpsert) SetBindingMethod(v string) *PaymentExternalOrderUpsert {
	u.Set(paymentexternalorder.FieldBindingMethod, v)
	return u
}

// UpdateBindingMethod sets the "binding_method" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsert) UpdateBindingMethod() *PaymentExternalOrderUpsert {
	u.SetExcluded(paymentexternalorder.FieldBindingMethod)
	return u
}

// SetQuoteHash sets the "quote_hash" field.
func (u *PaymentExternalOrderUpsert) SetQuoteHash(v string) *PaymentExternalOrderUpsert {
	u.Set(paymentexternalorder.FieldQuoteHash, v)
	return u
}

// UpdateQuoteHash sets the "quote_hash" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsert) UpdateQuoteHash() *PaymentExternalOrderUpsert {
	u.SetExcluded(paymentexternalorder.FieldQuoteHash)
	return u
}

// SetLocalOrderID sets the "local_order_id" field.
func (u *PaymentExternalOrderUpsert) SetLocalOrderID(v int64) *PaymentExternalOrderUpsert {
	u.Set(paymentexternalorder.FieldLocalOrderID, v)
	return u
}

// UpdateLocalOrderID sets the "local_order_id" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsert) UpdateLocalOrderID() *PaymentExternalOrderUpsert {
	u.SetExcluded(paymentexternalorder.FieldLocalOrderID)
	return u
}

// AddLocalOrderID adds v to the "local_order_id" field.
func (u *PaymentExternalOrderUpsert) AddLocalOrderID(v int64) *PaymentExternalOrderUpsert {
	u.Add(paymentexternalorder.FieldLocalOrderID, v)
	return u
}

// ClearLocalOrderID clears the value of the "local_order_id" field.
func (u *PaymentExternalOrderUpsert) ClearLocalOrderID() *PaymentExternalOrderUpsert {
	u.SetNull(paymentexternalorder.FieldLocalOrderID)
	return u
}

// SetCheckoutReference sets the "checkout_reference" field.
func (u *PaymentExternalOrderUpsert) SetCheckoutReference(v string) *PaymentExternalOrderUpsert {
	u.Set(paymentexternalorder.FieldCheckoutReference, v)
	return u
}

// UpdateCheckoutReference sets the "checkout_reference" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsert) UpdateCheckoutReference() *PaymentExternalOrderUpsert {
	u.SetExcluded(paymentexternalorder.FieldCheckoutReference)
	return u
}

// SetCurrency sets the "currency" field.
func (u *PaymentExternalOrderUpsert) SetCurrency(v string) *PaymentExternalOrderUpsert {
	u.Set(paymentexternalorder.FieldCurrency, v)
	return u
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsert) UpdateCurrency() *PaymentExternalOrderUpsert {
	u.SetExcluded(paymentexternalorder.FieldCurrency)
	return u
}

// SetTotalMinor sets the "total_minor" field.
func (u *PaymentExternalOrderUpsert) SetTotalMinor(v int64) *PaymentExternalOrderUpsert {
	u.Set(paymentexternalorder.FieldTotalMinor, v)
	return u
}

// UpdateTotalMinor sets the "total_minor" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsert) UpdateTotalMinor() *PaymentExternalOrderUpsert {
	u.SetExcluded(paymentexternalorder.FieldTotalMinor)
	return u
}

// AddTotalMinor adds v to the "total_minor" field.
func (u *PaymentExternalOrderUpsert) AddTotalMinor(v int64) *PaymentExternalOrderUpsert {
	u.Add(paymentexternalorder.FieldTotalMinor, v)
	return u
}

// SetRefundedMinor sets the "refunded_minor" field.
func (u *PaymentExternalOrderUpsert) SetRefundedMinor(v int64) *PaymentExternalOrderUpsert {
	u.Set(paymentexternalorder.FieldRefundedMinor, v)
	return u
}

// UpdateRefundedMinor sets the "refunded_minor" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsert) UpdateRefundedMinor() *PaymentExternalOrderUpsert {
	u.SetExcluded(paymentexternalorder.FieldRefundedMinor)
	return u
}

// AddRefundedMinor adds v to the "refunded_minor" field.
func (u *PaymentExternalOrderUpsert) AddRefundedMinor(v int64) *PaymentExternalOrderUpsert {
	u.Add(paymentexternalorder.FieldRefundedMinor, v)
	return u
}

// SetCreditedUsdUnits sets the "credited_usd_units" field.
func (u *PaymentExternalOrderUpsert) SetCreditedUsdUnits(v int64) *PaymentExternalOrderUpsert {
	u.Set(paymentexternalorder.FieldCreditedUsdUnits, v)
	return u
}

// UpdateCreditedUsdUnits sets the "credited_usd_units" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsert) UpdateCreditedUsdUnits() *PaymentExternalOrderUpsert {
	u.SetExcluded(paymentexternalorder.FieldCreditedUsdUnits)
	return u
}

// AddCreditedUsdUnits adds v to the "credited_usd_units" field.
func (u *PaymentExternalOrderUpsert) AddCreditedUsdUnits(v int64) *PaymentExternalOrderUpsert {
	u.Add(paymentexternalorder.FieldCreditedUsdUnits, v)
	return u
}

// SetRefundTargetUsdUnits sets the "refund_target_usd_units" field.
func (u *PaymentExternalOrderUpsert) SetRefundTargetUsdUnits(v int64) *PaymentExternalOrderUpsert {
	u.Set(paymentexternalorder.FieldRefundTargetUsdUnits, v)
	return u
}

// UpdateRefundTargetUsdUnits sets the "refund_target_usd_units" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsert) UpdateRefundTargetUsdUnits() *PaymentExternalOrderUpsert {
	u.SetExcluded(paymentexternalorder.FieldRefundTargetUsdUnits)
	return u
}

// AddRefundTargetUsdUnits adds v to the "refund_target_usd_units" field.
func (u *PaymentExternalOrderUpsert) AddRefundTargetUsdUnits(v int64) *PaymentExternalOrderUpsert {
	u.Add(paymentexternalorder.FieldRefundTargetUsdUnits, v)
	return u
}

// SetRecoveredUsdUnits sets the "recovered_usd_units" field.
func (u *PaymentExternalOrderUpsert) SetRecoveredUsdUnits(v int64) *PaymentExternalOrderUpsert {
	u.Set(paymentexternalorder.FieldRecoveredUsdUnits, v)
	return u
}

// UpdateRecoveredUsdUnits sets the "recovered_usd_units" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsert) UpdateRecoveredUsdUnits() *PaymentExternalOrderUpsert {
	u.SetExcluded(paymentexternalorder.FieldRecoveredUsdUnits)
	return u
}

// AddRecoveredUsdUnits adds v to the "recovered_usd_units" field.
func (u *PaymentExternalOrderUpsert) AddRecoveredUsdUnits(v int64) *PaymentExternalOrderUpsert {
	u.Add(paymentexternalorder.FieldRecoveredUsdUnits, v)
	return u
}

// SetDebtUsdUnits sets the "debt_usd_units" field.
func (u *PaymentExternalOrderUpsert) SetDebtUsdUnits(v int64) *PaymentExternalOrderUpsert {
	u.Set(paymentexternalorder.FieldDebtUsdUnits, v)
	return u
}

// UpdateDebtUsdUnits sets the "debt_usd_units" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsert) UpdateDebtUsdUnits() *PaymentExternalOrderUpsert {
	u.SetExcluded(paymentexternalorder.FieldDebtUsdUnits)
	return u
}

// AddDebtUsdUnits adds v to the "debt_usd_units" field.
func (u *PaymentExternalOrderUpsert) AddDebtUsdUnits(v int64) *PaymentExternalOrderUpsert {
	u.Add(paymentexternalorder.FieldDebtUsdUnits, v)
	return u
}

// SetPaymentState sets the "payment_state" field.
func (u *PaymentExternalOrderUpsert) SetPaymentState(v string) *PaymentExternalOrderUpsert {
	u.Set(paymentexternalorder.FieldPaymentState, v)
	return u
}

// UpdatePaymentState sets the "payment_state" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsert) UpdatePaymentState() *PaymentExternalOrderUpsert {
	u.SetExcluded(paymentexternalorder.FieldPaymentState)
	return u
}

// SetStatus sets the "status" field.
func (u *PaymentExternalOrderUpsert) SetStatus(v string) *PaymentExternalOrderUpsert {
	u.Set(paymentexternalorder.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsert) UpdateStatus() *PaymentExternalOrderUpsert {
	u.SetExcluded(paymentexternalorder.FieldStatus)
	return u
}

// SetAnomalyCode sets the "anomaly_code" field.
func (u *PaymentExternalOrderUpsert) SetAnomalyCode(v string) *PaymentExternalOrderUpsert {
	u.Set(paymentexternalorder.FieldAnomalyCode, v)
	return u
}

// UpdateAnomalyCode sets the "anomaly_code" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsert) UpdateAnomalyCode() *PaymentExternalOrderUpsert {
	u.SetExcluded(paymentexternalorder.FieldAnomalyCode)
	return u
}

// SetPaidAt sets the "paid_at" field.
func (u *PaymentExternalOrderUpsert) SetPaidAt(v time.Time) *PaymentExternalOrderUpsert {
	u.Set(paymentexternalorder.FieldPaidAt, v)
	return u
}

// UpdatePaidAt sets the "paid_at" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsert) UpdatePaidAt() *PaymentExternalOrderUpsert {
	u.SetExcluded(paymentexternalorder.FieldPaidAt)
	return u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (u *PaymentExternalOrderUpsert) ClearPaidAt() *PaymentExternalOrderUpsert {
	u.SetNull(paymentexternalorder.FieldPaidAt)
	return u
}

// SetProviderModifiedAt sets the "provider_modified_at" field.
func (u *PaymentExternalOrderUpsert) SetProviderModifiedAt(v time.Time) *PaymentExternalOrderUpsert {
	u.Set(paymentexternalorder.FieldProviderModifiedAt, v)
	return u
}

// UpdateProviderModifiedAt sets the "provider_modified_at" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsert) UpdateProviderModifiedAt() *PaymentExternalOrderUpsert {
	u.SetExcluded(paymentexternalorder.FieldProviderModifiedAt)
	return u
}

// ClearProviderModifiedAt clears the value of the "provider_modified_at" field.
func (u *PaymentExternalOrderUpsert) ClearProviderModifiedAt() *PaymentExternalOrderUpsert {
	u.SetNull(paymentexternalorder.FieldProviderModifiedAt)
	return u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (u *PaymentExternalOrderUpsert) SetLastSeenAt(v time.Time) *PaymentExternalOrderUpsert {
	u.Set(paymentexternalorder.FieldLastSeenAt, v)
	return u
}

// UpdateLastSeenAt sets the "last_seen_at" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsert) UpdateLastSeenAt() *PaymentExternalOrderUpsert {
	u.SetExcluded(paymentexternalorder.FieldLastSeenAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PaymentExternalOrderUpsert) SetUpdatedAt(v time.Time) *PaymentExternalOrderUpsert {
	u.Set(paymentexternalorder.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsert) UpdateUpdatedAt() *PaymentExternalOrderUpsert {
	u.SetExcluded(paymentexternalorder.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.PaymentExternalOrder.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PaymentExternalOrderUpsertOne) UpdateNewValues() *PaymentExternalOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(paymentexternalorder.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PaymentExternalOrder.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PaymentExternalOrderUpsertOne) Ignore() *PaymentExternalOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PaymentExternalOrderUpsertOne) DoNothing() *PaymentExternalOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PaymentExternalOrderCreate.OnConflict
// documentation for more info.
func (u *PaymentExternalOrderUpsertOne) Update(set func(*PaymentExternalOrderUpsert)) *PaymentExternalOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PaymentExternalOrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetProviderKey sets the "provider_key" field.
func (u *PaymentExternalOrderUpsertOne) SetProviderKey(v string) *PaymentExternalOrderUpsertOne {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.SetProviderKey(v)
	})
}

// UpdateProviderKey sets the "provider_key" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsertOne) UpdateProviderKey() *PaymentExternalOrderUpsertOne {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.UpdateProviderKey()
	})
}

// SetWebsiteID sets the "website_id" field.
func (u *PaymentExternalOrderUpsertOne) SetWebsiteID(v string) *PaymentExternalOrderUpsertOne {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.SetWebsiteID(v)
	})
}

// UpdateWebsiteID sets the "website_id" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsertOne) UpdateWebsiteID() *PaymentExternalOrderUpsertOne {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.UpdateWebsiteID()
	})
}

// SetExternalOrderID sets the "external_order_id" field.
func (u *PaymentExternalOrderUpsertOne) SetExternalOrderID(v string) *PaymentExternalOrderUpsertOne {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.SetExternalOrderID(v)
	})
}

// UpdateExternalOrderID sets the "external_order_id" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsertOne) UpdateExternalOrderID() *PaymentExternalOrderUpsertOne {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.UpdateExternalOrderID()
	})
}

// SetOrderNumber sets the "order_number" field.
func (u *PaymentExternalOrderUpsertOne) SetOrderNumber(v string) *PaymentExternalOrderUpsertOne {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.SetOrderNumber(v)
	})
}

// UpdateOrderNumber sets the "order_number" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsertOne) UpdateOrderNumber() *PaymentExternalOrderUpsertOne {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.UpdateOrderNumber()
	})
}

// SetBindingMethod sets the "binding_method" field.
func (u *PaymentExternalOrderUpsertOne) SetBindingMethod(v string) *PaymentExternalOrderUpsertOne {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.SetBindingMethod(v)
	})
}

// UpdateBindingMethod sets the "binding_method" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsertOne) UpdateBindingMethod() *PaymentExternalOrderUpsertOne {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.UpdateBindingMethod()
	})
}

// SetQuoteHash sets the "quote_hash" field.
func (u *PaymentExternalOrderUpsertOne) SetQuoteHash(v string) *PaymentExternalOrderUpsertOne {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.SetQuoteHash(v)
	})
}

// UpdateQuoteHash sets the "quote_hash" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsertOne) UpdateQuoteHash() *PaymentExternalOrderUpsertOne {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.UpdateQuoteHash()
	})
}

// SetLocalOrderID sets the "local_order_id" field.
func (u *PaymentExternalOrderUpsertOne) SetLocalOrderID(v int64) *PaymentExternalOrderUpsertOne {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.SetLocalOrderID(v)
	})
}

// AddLocalOrderID adds v to the "local_order_id" field.
func (u *PaymentExternalOrderUpsertOne) AddLocalOrderID(v int64) *PaymentExternalOrderUpsertOne {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.AddLocalOrderID(v)
	})
}

// UpdateLocalOrderID sets the "local_order_id" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsertOne) UpdateLocalOrderID() *PaymentExternalOrderUpsertOne {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.UpdateLocalOrderID()
	})
}

// ClearLocalOrderID clears the value of the "local_order_id" field.
func (u *PaymentExternalOrderUpsertOne) ClearLocalOrderID() *PaymentExternalOrderUpsertOne {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.ClearLocalOrderID()
	})
}

// SetCheckoutReference sets the "checkout_reference" field.
func (u *PaymentExternalOrderUpsertOne) SetCheckoutReference(v string) *PaymentExternalOrderUpsertOne {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.SetCheckoutReference(v)
	})
}

// UpdateCheckoutReference sets the "checkout_reference" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsertOne) UpdateCheckoutReference() *PaymentExternalOrderUpsertOne {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.UpdateCheckoutReference()
	})
}

// SetCurrency sets the "currency" field.
func (u *PaymentExternalOrderUpsertOne) SetCurrency(v string) *PaymentExternalOrderUpsertOne {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsertOne) UpdateCurrency() *PaymentExternalOrderUpsertOne {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.UpdateCurrency()
	})
}

// SetTotalMinor sets the "total_minor" field.
func (u *PaymentExternalOrderUpsertOne) SetTotalMinor(v int64) *PaymentExternalOrderUpsertOne {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.SetTotalMinor(v)
	})
}

// AddTotalMinor adds v to the "total_minor" field.
func (u *PaymentExternalOrderUpsertOne) AddTotalMinor(v int64) *PaymentExternalOrderUpsertOne {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.AddTotalMinor(v)
	})
}

// UpdateTotalMinor sets the "total_minor" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsertOne) UpdateTotalMinor() *PaymentExternalOrderUpsertOne {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.UpdateTotalMinor()
	})
}

// SetRefundedMinor sets the "refunded_minor" field.
func (u *PaymentExternalOrderUpsertOne) SetRefundedMinor(v int64) *PaymentExternalOrderUpsertOne {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.SetRefundedMinor(v)
	})
}

// AddRefundedMinor adds v to the "refunded_minor" field.
func (u *PaymentExternalOrderUpsertOne) AddRefundedMinor(v int64) *PaymentExternalOrderUpsertOne {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.AddRefundedMinor(v)
	})
}

// UpdateRefundedMinor sets the "refunded_minor" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsertOne) UpdateRefundedMinor() *PaymentExternalOrderUpsertOne {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.UpdateRefundedMinor()
	})
}

// SetCreditedUsdUnits sets the "credited_usd_units" field.
func (u *PaymentExternalOrderUpsertOne) SetCreditedUsdUnits(v int64) *PaymentExternalOrderUpsertOne {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.SetCreditedUsdUnits(v)
	})
}

// AddCreditedUsdUnits adds v to the "credited_usd_units" field.
func (u *PaymentExternalOrderUpsertOne) AddCreditedUsdUnits(v int64) *PaymentExternalOrderUpsertOne {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.AddCreditedUsdUnits(v)
	})
}

// UpdateCreditedUsdUnits sets the "credited_usd_units" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsertOne) UpdateCreditedUsdUnits() *PaymentExternalOrderUpsertOne {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.UpdateCreditedUsdUnits()
	})
}

// SetRefundTargetUsdUnits sets the "refund_target_usd_units" field.
func (u *PaymentExternalOrderUpsertOne) SetRefundTargetUsdUnits(v int64) *PaymentExternalOrderUpsertOne {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.SetRefundTargetUsdUnits(v)
	})
}

// AddRefundTargetUsdUnits adds v to the "refund_target_usd_units" field.
func (u *PaymentExternalOrderUpsertOne) AddRefundTargetUsdUnits(v int64) *PaymentExternalOrderUpsertOne {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.AddRefundTargetUsdUnits(v)
	})
}

// UpdateRefundTargetUsdUnits sets the "refund_target_usd_units" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsertOne) UpdateRefundTargetUsdUnits() *PaymentExternalOrderUpsertOne {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.UpdateRefundTargetUsdUnits()
	})
}

// SetRecoveredUsdUnits sets the "recovered_usd_units" field.
func (u *PaymentExternalOrderUpsertOne) SetRecoveredUsdUnits(v int64) *PaymentExternalOrderUpsertOne {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.SetRecoveredUsdUnits(v)
	})
}

// AddRecoveredUsdUnits adds v to the "recovered_usd_units" field.
func (u *PaymentExternalOrderUpsertOne) AddRecoveredUsdUnits(v int64) *PaymentExternalOrderUpsertOne {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.AddRecoveredUsdUnits(v)
	})
}

// UpdateRecoveredUsdUnits sets the "recovered_usd_units" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsertOne) UpdateRecoveredUsdUnits() *PaymentExternalOrderUpsertOne {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.UpdateRecoveredUsdUnits()
	})
}

// SetDebtUsdUnits sets the "debt_usd_units" field.
func (u *PaymentExternalOrderUpsertOne) SetDebtUsdUnits(v int64) *PaymentExternalOrderUpsertOne {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.SetDebtUsdUnits(v)
	})
}

// AddDebtUsdUnits adds v to the "debt_usd_units" field.
func (u *PaymentExternalOrderUpsertOne) AddDebtUsdUnits(v int64) *PaymentExternalOrderUpsertOne {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.AddDebtUsdUnits(v)
	})
}

// UpdateDebtUsdUnits sets the "debt_usd_units" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsertOne) UpdateDebtUsdUnits() *PaymentExternalOrderUpsertOne {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.UpdateDebtUsdUnits()
	})
}

// SetPaymentState sets the "payment_state" field.
func (u *PaymentExternalOrderUpsertOne) SetPaymentState(v string) *PaymentExternalOrderUpsertOne {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.SetPaymentState(v)
	})
}

// UpdatePaymentState sets the "payment_state" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsertOne) UpdatePaymentState() *PaymentExternalOrderUpsertOne {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.UpdatePaymentState()
	})
}

// SetStatus sets the "status" field.
func (u *PaymentExternalOrderUpsertOne) SetStatus(v string) *PaymentExternalOrderUpsertOne {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsertOne) UpdateStatus() *PaymentExternalOrderUpsertOne {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.UpdateStatus()
	})
}

// SetAnomalyCode sets the "anomaly_code" field.
func (u *PaymentExternalOrderUpsertOne) SetAnomalyCode(v string) *PaymentExternalOrderUpsertOne {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.SetAnomalyCode(v)
	})
}

// UpdateAnomalyCode sets the "anomaly_code" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsertOne) UpdateAnomalyCode() *PaymentExternalOrderUpsertOne {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.UpdateAnomalyCode()
	})
}

// SetPaidAt sets the "paid_at" field.
func (u *PaymentExternalOrderUpsertOne) SetPaidAt(v time.Time) *PaymentExternalOrderUpsertOne {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.SetPaidAt(v)
	})
}

// UpdatePaidAt sets the "paid_at" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsertOne) UpdatePaidAt() *PaymentExternalOrderUpsertOne {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.UpdatePaidAt()
	})
}

// ClearPaidAt clears the value of the "paid_at" field.
func (u *PaymentExternalOrderUpsertOne) ClearPaidAt() *PaymentExternalOrderUpsertOne {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.ClearPaidAt()
	})
}

// SetProviderModifiedAt sets the "provider_modified_at" field.
func (u *PaymentExternalOrderUpsertOne) SetProviderModifiedAt(v time.Time) *PaymentExternalOrderUpsertOne {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.SetProviderModifiedAt(v)
	})
}

// UpdateProviderModifiedAt sets the "provider_modified_at" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsertOne) UpdateProviderModifiedAt() *PaymentExternalOrderUpsertOne {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.UpdateProviderModifiedAt()
	})
}

// ClearProviderModifiedAt clears the value of the "provider_modified_at" field.
func (u *PaymentExternalOrderUpsertOne) ClearProviderModifiedAt() *PaymentExternalOrderUpsertOne {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.ClearProviderModifiedAt()
	})
}

// SetLastSeenAt sets the "last_seen_at" field.
func (u *PaymentExternalOrderUpsertOne) SetLastSeenAt(v time.Time) *PaymentExternalOrderUpsertOne {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.SetLastSeenAt(v)
	})
}

// UpdateLastSeenAt sets the "last_seen_at" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsertOne) UpdateLastSeenAt() *PaymentExternalOrderUpsertOne {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.UpdateLastSeenAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PaymentExternalOrderUpsertOne) SetUpdatedAt(v time.Time) *PaymentExternalOrderUpsertOne {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsertOne) UpdateUpdatedAt() *PaymentExternalOrderUpsertOne {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PaymentExternalOrderUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PaymentExternalOrderCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PaymentExternalOrderUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PaymentExternalOrderUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PaymentExternalOrderUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PaymentExternalOrderCreateBulk is the builder for creating many PaymentExternalOrder entities in bulk.
type PaymentExternalOrderCreateBulk struct {
	config
	err      error
	builders []*PaymentExternalOrderCreate
	conflict []sql.ConflictOption
}

// Save creates the PaymentExternalOrder entities in the database.
func (_c *PaymentExternalOrderCreateBulk) Save(ctx context.Context) ([]*PaymentExternalOrder, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PaymentExternalOrder, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PaymentExternalOrderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PaymentExternalOrderCreateBulk) SaveX(ctx context.Context) []*PaymentExternalOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PaymentExternalOrderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PaymentExternalOrderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PaymentExternalOrder.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PaymentExternalOrderUpsert) {
//			SetProviderKey(v+v).
//		}).
//		Exec(ctx)
func (_c *PaymentExternalOrderCreateBulk) OnConflict(opts ...sql.ConflictOption) *PaymentExternalOrderUpsertBulk {
	_c.conflict = opts
	return &PaymentExternalOrderUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PaymentExternalOrder.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PaymentExternalOrderCreateBulk) OnConflictColumns(columns ...string) *PaymentExternalOrderUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PaymentExternalOrderUpsertBulk{
		create: _c,
	}
}

// PaymentExternalOrderUpsertBulk is the builder for "upsert"-ing
// a bulk of PaymentExternalOrder nodes.
type PaymentExternalOrderUpsertBulk struct {
	create *PaymentExternalOrderCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PaymentExternalOrder.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PaymentExternalOrderUpsertBulk) UpdateNewValues() *PaymentExternalOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(paymentexternalorder.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PaymentExternalOrder.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PaymentExternalOrderUpsertBulk) Ignore() *PaymentExternalOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PaymentExternalOrderUpsertBulk) DoNothing() *PaymentExternalOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PaymentExternalOrderCreateBulk.OnConflict
// documentation for more info.
func (u *PaymentExternalOrderUpsertBulk) Update(set func(*PaymentExternalOrderUpsert)) *PaymentExternalOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PaymentExternalOrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetProviderKey sets the "provider_key" field.
func (u *PaymentExternalOrderUpsertBulk) SetProviderKey(v string) *PaymentExternalOrderUpsertBulk {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.SetProviderKey(v)
	})
}

// UpdateProviderKey sets the "provider_key" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsertBulk) UpdateProviderKey() *PaymentExternalOrderUpsertBulk {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.UpdateProviderKey()
	})
}

// SetWebsiteID sets the "website_id" field.
func (u *PaymentExternalOrderUpsertBulk) SetWebsiteID(v string) *PaymentExternalOrderUpsertBulk {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.SetWebsiteID(v)
	})
}

// UpdateWebsiteID sets the "website_id" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsertBulk) UpdateWebsiteID() *PaymentExternalOrderUpsertBulk {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.UpdateWebsiteID()
	})
}

// SetExternalOrderID sets the "external_order_id" field.
func (u *PaymentExternalOrderUpsertBulk) SetExternalOrderID(v string) *PaymentExternalOrderUpsertBulk {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.SetExternalOrderID(v)
	})
}

// UpdateExternalOrderID sets the "external_order_id" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsertBulk) UpdateExternalOrderID() *PaymentExternalOrderUpsertBulk {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.UpdateExternalOrderID()
	})
}

// SetOrderNumber sets the "order_number" field.
func (u *PaymentExternalOrderUpsertBulk) SetOrderNumber(v string) *PaymentExternalOrderUpsertBulk {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.SetOrderNumber(v)
	})
}

// UpdateOrderNumber sets the "order_number" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsertBulk) UpdateOrderNumber() *PaymentExternalOrderUpsertBulk {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.UpdateOrderNumber()
	})
}

// SetBindingMethod sets the "binding_method" field.
func (u *PaymentExternalOrderUpsertBulk) SetBindingMethod(v string) *PaymentExternalOrderUpsertBulk {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.SetBindingMethod(v)
	})
}

// UpdateBindingMethod sets the "binding_method" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsertBulk) UpdateBindingMethod() *PaymentExternalOrderUpsertBulk {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.UpdateBindingMethod()
	})
}

// SetQuoteHash sets the "quote_hash" field.
func (u *PaymentExternalOrderUpsertBulk) SetQuoteHash(v string) *PaymentExternalOrderUpsertBulk {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.SetQuoteHash(v)
	})
}

// UpdateQuoteHash sets the "quote_hash" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsertBulk) UpdateQuoteHash() *PaymentExternalOrderUpsertBulk {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.UpdateQuoteHash()
	})
}

// SetLocalOrderID sets the "local_order_id" field.
func (u *PaymentExternalOrderUpsertBulk) SetLocalOrderID(v int64) *PaymentExternalOrderUpsertBulk {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.SetLocalOrderID(v)
	})
}

// AddLocalOrderID adds v to the "local_order_id" field.
func (u *PaymentExternalOrderUpsertBulk) AddLocalOrderID(v int64) *PaymentExternalOrderUpsertBulk {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.AddLocalOrderID(v)
	})
}

// UpdateLocalOrderID sets the "local_order_id" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsertBulk) UpdateLocalOrderID() *PaymentExternalOrderUpsertBulk {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.UpdateLocalOrderID()
	})
}

// ClearLocalOrderID clears the value of the "local_order_id" field.
func (u *PaymentExternalOrderUpsertBulk) ClearLocalOrderID() *PaymentExternalOrderUpsertBulk {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.ClearLocalOrderID()
	})
}

// SetCheckoutReference sets the "checkout_reference" field.
func (u *PaymentExternalOrderUpsertBulk) SetCheckoutReference(v string) *PaymentExternalOrderUpsertBulk {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.SetCheckoutReference(v)
	})
}

// UpdateCheckoutReference sets the "checkout_reference" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsertBulk) UpdateCheckoutReference() *PaymentExternalOrderUpsertBulk {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.UpdateCheckoutReference()
	})
}

// SetCurrency sets the "currency" field.
func (u *PaymentExternalOrderUpsertBulk) SetCurrency(v string) *PaymentExternalOrderUpsertBulk {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsertBulk) UpdateCurrency() *PaymentExternalOrderUpsertBulk {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.UpdateCurrency()
	})
}

// SetTotalMinor sets the "total_minor" field.
func (u *PaymentExternalOrderUpsertBulk) SetTotalMinor(v int64) *PaymentExternalOrderUpsertBulk {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.SetTotalMinor(v)
	})
}

// AddTotalMinor adds v to the "total_minor" field.
func (u *PaymentExternalOrderUpsertBulk) AddTotalMinor(v int64) *PaymentExternalOrderUpsertBulk {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.AddTotalMinor(v)
	})
}

// UpdateTotalMinor sets the "total_minor" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsertBulk) UpdateTotalMinor() *PaymentExternalOrderUpsertBulk {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.UpdateTotalMinor()
	})
}

// SetRefundedMinor sets the "refunded_minor" field.
func (u *PaymentExternalOrderUpsertBulk) SetRefundedMinor(v int64) *PaymentExternalOrderUpsertBulk {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.SetRefundedMinor(v)
	})
}

// AddRefundedMinor adds v to the "refunded_minor" field.
func (u *PaymentExternalOrderUpsertBulk) AddRefundedMinor(v int64) *PaymentExternalOrderUpsertBulk {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.AddRefundedMinor(v)
	})
}

// UpdateRefundedMinor sets the "refunded_minor" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsertBulk) UpdateRefundedMinor() *PaymentExternalOrderUpsertBulk {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.UpdateRefundedMinor()
	})
}

// SetCreditedUsdUnits sets the "credited_usd_units" field.
func (u *PaymentExternalOrderUpsertBulk) SetCreditedUsdUnits(v int64) *PaymentExternalOrderUpsertBulk {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.SetCreditedUsdUnits(v)
	})
}

// AddCreditedUsdUnits adds v to the "credited_usd_units" field.
func (u *PaymentExternalOrderUpsertBulk) AddCreditedUsdUnits(v int64) *PaymentExternalOrderUpsertBulk {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.AddCreditedUsdUnits(v)
	})
}

// UpdateCreditedUsdUnits sets the "credited_usd_units" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsertBulk) UpdateCreditedUsdUnits() *PaymentExternalOrderUpsertBulk {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.UpdateCreditedUsdUnits()
	})
}

// SetRefundTargetUsdUnits sets the "refund_target_usd_units" field.
func (u *PaymentExternalOrderUpsertBulk) SetRefundTargetUsdUnits(v int64) *PaymentExternalOrderUpsertBulk {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.SetRefundTargetUsdUnits(v)
	})
}

// AddRefundTargetUsdUnits adds v to the "refund_target_usd_units" field.
func (u *PaymentExternalOrderUpsertBulk) AddRefundTargetUsdUnits(v int64) *PaymentExternalOrderUpsertBulk {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.AddRefundTargetUsdUnits(v)
	})
}

// UpdateRefundTargetUsdUnits sets the "refund_target_usd_units" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsertBulk) UpdateRefundTargetUsdUnits() *PaymentExternalOrderUpsertBulk {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.UpdateRefundTargetUsdUnits()
	})
}

// SetRecoveredUsdUnits sets the "recovered_usd_units" field.
func (u *PaymentExternalOrderUpsertBulk) SetRecoveredUsdUnits(v int64) *PaymentExternalOrderUpsertBulk {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.SetRecoveredUsdUnits(v)
	})
}

// AddRecoveredUsdUnits adds v to the "recovered_usd_units" field.
func (u *PaymentExternalOrderUpsertBulk) AddRecoveredUsdUnits(v int64) *PaymentExternalOrderUpsertBulk {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.AddRecoveredUsdUnits(v)
	})
}

// UpdateRecoveredUsdUnits sets the "recovered_usd_units" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsertBulk) UpdateRecoveredUsdUnits() *PaymentExternalOrderUpsertBulk {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.UpdateRecoveredUsdUnits()
	})
}

// SetDebtUsdUnits sets the "debt_usd_units" field.
func (u *PaymentExternalOrderUpsertBulk) SetDebtUsdUnits(v int64) *PaymentExternalOrderUpsertBulk {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.SetDebtUsdUnits(v)
	})
}

// AddDebtUsdUnits adds v to the "debt_usd_units" field.
func (u *PaymentExternalOrderUpsertBulk) AddDebtUsdUnits(v int64) *PaymentExternalOrderUpsertBulk {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.AddDebtUsdUnits(v)
	})
}

// UpdateDebtUsdUnits sets the "debt_usd_units" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsertBulk) UpdateDebtUsdUnits() *PaymentExternalOrderUpsertBulk {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.UpdateDebtUsdUnits()
	})
}

// SetPaymentState sets the "payment_state" field.
func (u *PaymentExternalOrderUpsertBulk) SetPaymentState(v string) *PaymentExternalOrderUpsertBulk {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.SetPaymentState(v)
	})
}

// UpdatePaymentState sets the "payment_state" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsertBulk) UpdatePaymentState() *PaymentExternalOrderUpsertBulk {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.UpdatePaymentState()
	})
}

// SetStatus sets the "status" field.
func (u *PaymentExternalOrderUpsertBulk) SetStatus(v string) *PaymentExternalOrderUpsertBulk {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsertBulk) UpdateStatus() *PaymentExternalOrderUpsertBulk {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.UpdateStatus()
	})
}

// SetAnomalyCode sets the "anomaly_code" field.
func (u *PaymentExternalOrderUpsertBulk) SetAnomalyCode(v string) *PaymentExternalOrderUpsertBulk {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.SetAnomalyCode(v)
	})
}

// UpdateAnomalyCode sets the "anomaly_code" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsertBulk) UpdateAnomalyCode() *PaymentExternalOrderUpsertBulk {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.UpdateAnomalyCode()
	})
}

// SetPaidAt sets the "paid_at" field.
func (u *PaymentExternalOrderUpsertBulk) SetPaidAt(v time.Time) *PaymentExternalOrderUpsertBulk {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.SetPaidAt(v)
	})
}

// UpdatePaidAt sets the "paid_at" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsertBulk) UpdatePaidAt() *PaymentExternalOrderUpsertBulk {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.UpdatePaidAt()
	})
}

// ClearPaidAt clears the value of the "paid_at" field.
func (u *PaymentExternalOrderUpsertBulk) ClearPaidAt() *PaymentExternalOrderUpsertBulk {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.ClearPaidAt()
	})
}

// SetProviderModifiedAt sets the "provider_modified_at" field.
func (u *PaymentExternalOrderUpsertBulk) SetProviderModifiedAt(v time.Time) *PaymentExternalOrderUpsertBulk {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.SetProviderModifiedAt(v)
	})
}

// UpdateProviderModifiedAt sets the "provider_modified_at" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsertBulk) UpdateProviderModifiedAt() *PaymentExternalOrderUpsertBulk {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.UpdateProviderModifiedAt()
	})
}

// ClearProviderModifiedAt clears the value of the "provider_modified_at" field.
func (u *PaymentExternalOrderUpsertBulk) ClearProviderModifiedAt() *PaymentExternalOrderUpsertBulk {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.ClearProviderModifiedAt()
	})
}

// SetLastSeenAt sets the "last_seen_at" field.
func (u *PaymentExternalOrderUpsertBulk) SetLastSeenAt(v time.Time) *PaymentExternalOrderUpsertBulk {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.SetLastSeenAt(v)
	})
}

// UpdateLastSeenAt sets the "last_seen_at" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsertBulk) UpdateLastSeenAt() *PaymentExternalOrderUpsertBulk {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.UpdateLastSeenAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PaymentExternalOrderUpsertBulk) SetUpdatedAt(v time.Time) *PaymentExternalOrderUpsertBulk {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PaymentExternalOrderUpsertBulk) UpdateUpdatedAt() *PaymentExternalOrderUpsertBulk {
	return u.Update(func(s *PaymentExternalOrderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PaymentExternalOrderUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PaymentExternalOrderCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PaymentExternalOrderCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PaymentExternalOrderUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
