// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/paymentexternalpayment"
)

// PaymentExternalPayment is the model entity for the PaymentExternalPayment schema.
type PaymentExternalPayment struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// ProviderKey holds the value of the "provider_key" field.
	ProviderKey string `json:"provider_key,omitempty"`
	// WebsiteID holds the value of the "website_id" field.
	WebsiteID string `json:"website_id,omitempty"`
	// PaymentID holds the value of the "payment_id" field.
	PaymentID string `json:"payment_id,omitempty"`
	// ExternalOrderLedgerID holds the value of the "external_order_ledger_id" field.
	ExternalOrderLedgerID int64 `json:"external_order_ledger_id,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// AmountMinor holds the value of the "amount_minor" field.
	AmountMinor int64 `json:"amount_minor,omitempty"`
	// RefundedMinor holds the value of the "refunded_minor" field.
	RefundedMinor int64 `json:"refunded_minor,omitempty"`
	// PaidAt holds the value of the "paid_at" field.
	PaidAt time.Time `json:"paid_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PaymentExternalPayment) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case paymentexternalpayment.FieldID, paymentexternalpayment.FieldExternalOrderLedgerID, paymentexternalpayment.FieldAmountMinor, paymentexternalpayment.FieldRefundedMinor:
			values[i] = new(sql.NullInt64)
		case paymentexternalpayment.FieldProviderKey, paymentexternalpayment.FieldWebsiteID, paymentexternalpayment.FieldPaymentID, paymentexternalpayment.FieldCurrency:
			values[i] = new(sql.NullString)
		case paymentexternalpayment.FieldPaidAt, paymentexternalpayment.FieldCreatedAt, paymentexternalpayment.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PaymentExternalPayment fields.
func (_m *PaymentExternalPayment) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case paymentexternalpayment.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case paymentexternalpayment.FieldProviderKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_key", values[i])
			} else if value.Valid {
				_m.ProviderKey = value.String
			}
		case paymentexternalpayment.FieldWebsiteID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field website_id", values[i])
			} else if value.Valid {
				_m.WebsiteID = value.String
			}
		case paymentexternalpayment.FieldPaymentID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payment_id", values[i])
			} else if value.Valid {
				_m.PaymentID = value.String
			}
		case paymentexternalpayment.FieldExternalOrderLedgerID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field external_order_ledger_id", values[i])
			} else if value.Valid {
				_m.ExternalOrderLedgerID = value.Int64
			}
		case paymentexternalpayment.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case paymentexternalpayment.FieldAmountMinor:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field amount_minor", values[i])
			} else if value.Valid {
				_m.AmountMinor = value.Int64
			}
		case paymentexternalpayment.FieldRefundedMinor:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field refunded_minor", values[i])
			} else if value.Valid {
				_m.RefundedMinor = value.Int64
			}
		case paymentexternalpayment.FieldPaidAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field paid_at", values[i])
			} else if value.Valid {
				_m.PaidAt = value.Time
			}
		case paymentexternalpayment.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case paymentexternalpayment.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PaymentExternalPayment.
// This includes values selected through modifiers, order, etc.
func (_m *PaymentExternalPayment) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this PaymentExternalPayment.
// Note that you need to call PaymentExternalPayment.Unwrap() before calling this method if this PaymentExternalPayment
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PaymentExternalPayment) Update() *PaymentExternalPaymentUpdateOne {
	return NewPaymentExternalPaymentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PaymentExternalPayment entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PaymentExternalPayment) Unwrap() *PaymentExternalPayment {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PaymentExternalPayment is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PaymentExternalPayment) String() string {
	var builder strings.Builder
	builder.WriteString("PaymentExternalPayment(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("provider_key=")
	builder.WriteString(_m.ProviderKey)
	builder.WriteString(", ")
	builder.WriteString("website_id=")
	builder.WriteString(_m.WebsiteID)
	builder.WriteString(", ")
	builder.WriteString("payment_id=")
	builder.WriteString(_m.PaymentID)
	builder.WriteString(", ")
	builder.WriteString("external_order_ledger_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExternalOrderLedgerID))
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	builder.WriteString("amount_minor=")
	builder.WriteString(fmt.Sprintf("%v", _m.AmountMinor))
	builder.WriteString(", ")
	builder.WriteString("refunded_minor=")
	builder.WriteString(fmt.Sprintf("%v", _m.RefundedMinor))
	builder.WriteString(", ")
	builder.WriteString("paid_at=")
	builder.WriteString(_m.PaidAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PaymentExternalPayments is a parsable slice of PaymentExternalPayment.
type PaymentExternalPayments []*PaymentExternalPayment
