// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/paymentexternalpayment"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// PaymentExternalPaymentUpdate is the builder for updating PaymentExternalPayment entities.
type PaymentExternalPaymentUpdate struct {
	config
	hooks    []Hook
	mutation *PaymentExternalPaymentMutation
}

// Where appends a list predicates to the PaymentExternalPaymentUpdate builder.
func (_u *PaymentExternalPaymentUpdate) Where(ps ...predicate.PaymentExternalPayment) *PaymentExternalPaymentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProviderKey sets the "provider_key" field.
func (_u *PaymentExternalPaymentUpdate) SetProviderKey(v string) *PaymentExternalPaymentUpdate {
	_u.mutation.SetProviderKey(v)
	return _u
}

// SetNillableProviderKey sets the "provider_key" field if the given value is not nil.
func (_u *PaymentExternalPaymentUpdate) SetNillableProviderKey(v *string) *PaymentExternalPaymentUpdate {
	if v != nil {
		_u.SetProviderKey(*v)
	}
	return _u
}

// SetWebsiteID sets the "website_id" field.
func (_u *PaymentExternalPaymentUpdate) SetWebsiteID(v string) *PaymentExternalPaymentUpdate {
	_u.mutation.SetWebsiteID(v)
	return _u
}

// SetNillableWebsiteID sets the "website_id" field if the given value is not nil.
func (_u *PaymentExternalPaymentUpdate) SetNillableWebsiteID(v *string) *PaymentExternalPaymentUpdate {
	if v != nil {
		_u.SetWebsiteID(*v)
	}
	return _u
}

// SetPaymentID sets the "payment_id" field.
func (_u *PaymentExternalPaymentUpdate) SetPaymentID(v string) *PaymentExternalPaymentUpdate {
	_u.mutation.SetPaymentID(v)
	return _u
}

// SetNillablePaymentID sets the "payment_id" field if the given value is not nil.
func (_u *PaymentExternalPaymentUpdate) SetNillablePaymentID(v *string) *PaymentExternalPaymentUpdate {
	if v != nil {
		_u.SetPaymentID(*v)
	}
	return _u
}

// SetExternalOrderLedgerID sets the "external_order_ledger_id" field.
func (_u *PaymentExternalPaymentUpdate) SetExternalOrderLedgerID(v int64) *PaymentExternalPaymentUpdate {
	_u.mutation.ResetExternalOrderLedgerID()
	_u.mutation.SetExternalOrderLedgerID(v)
	return _u
}

// SetNillableExternalOrderLedgerID sets the "external_order_ledger_id" field if the given value is not nil.
func (_u *PaymentExternalPaymentUpdate) SetNillableExternalOrderLedgerID(v *int64) *PaymentExternalPaymentUpdate {
	if v != nil {
		_u.SetExternalOrderLedgerID(*v)
	}
	return _u
}

// AddExternalOrderLedgerID adds value to the "external_order_ledger_id" field.
func (_u *PaymentExternalPaymentUpdate) AddExternalOrderLedgerID(v int64) *PaymentExternalPaymentUpdate {
	_u.mutation.AddExternalOrderLedgerID(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *PaymentExternalPaymentUpdate) SetCurrency(v string) *PaymentExternalPaymentUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *PaymentExternalPaymentUpdate) SetNillableCurrency(v *string) *PaymentExternalPaymentUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetAmountMinor sets the "amount_minor" field.
func (_u *PaymentExternalPaymentUpdate) SetAmountMinor(v int64) *PaymentExternalPaymentUpdate {
	_u.mutation.ResetAmountMinor()
	_u.mutation.SetAmountMinor(v)
	return _u
}

// SetNillableAmountMinor sets the "amount_minor" field if the given value is not nil.
func (_u *PaymentExternalPaymentUpdate) SetNillableAmountMinor(v *int64) *PaymentExternalPaymentUpdate {
	if v != nil {
		_u.SetAmountMinor(*v)
	}
	return _u
}

// AddAmountMinor adds value to the "amount_minor" field.
func (_u *PaymentExternalPaymentUpdate) AddAmountMinor(v int64) *PaymentExternalPaymentUpdate {
	_u.mutation.AddAmountMinor(v)
	return _u
}

// SetRefundedMinor sets the "refunded_minor" field.
func (_u *PaymentExternalPaymentUpdate) SetRefundedMinor(v int64) *PaymentExternalPaymentUpdate {
	_u.mutation.ResetRefundedMinor()
	_u.mutation.SetRefundedMinor(v)
	return _u
}

// SetNillableRefundedMinor sets the "refunded_minor" field if the given value is not nil.
func (_u *PaymentExternalPaymentUpdate) SetNillableRefundedMinor(v *int64) *PaymentExternalPaymentUpdate {
	if v != nil {
		_u.SetRefundedMinor(*v)
	}
	return _u
}

// AddRefundedMinor adds value to the "refunded_minor" field.
func (_u *PaymentExternalPaymentUpdate) AddRefundedMinor(v int64) *PaymentExternalPaymentUpdate {
	_u.mutation.AddRefundedMinor(v)
	return _u
}

// SetPaidAt sets the "paid_at" field.
func (_u *PaymentExternalPaymentUpdate) SetPaidAt(v time.Time) *PaymentExternalPaymentUpdate {
	_u.mutation.SetPaidAt(v)
	return _u
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_u *PaymentExternalPaymentUpdate) SetNillablePaidAt(v *time.Time) *PaymentExternalPaymentUpdate {
	if v != nil {
		_u.SetPaidAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PaymentExternalPaymentUpdate) SetUpdatedAt(v time.Time) *PaymentExternalPaymentUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PaymentExternalPaymentMutation object of the builder.
func (_u *PaymentExternalPaymentUpdate) Mutation() *PaymentExternalPaymentMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PaymentExternalPaymentUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentExternalPaymentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PaymentExternalPaymentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentExternalPaymentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaymentExternalPaymentUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := paymentexternalpayment.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentExternalPaymentUpdate) check() error {
	if v, ok := _u.mutation.ProviderKey(); ok {
		if err := paymentexternalpayment.ProviderKeyValidator(v); err != nil {
			return &ValidationError{Name: "provider_key", err: fmt.Errorf(`ent: validator failed for field "PaymentExternalPayment.provider_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WebsiteID(); ok {
		if err := paymentexternalpayment.WebsiteIDValidator(v); err != nil {
			return &ValidationError{Name: "website_id", err: fmt.Errorf(`ent: validator failed for field "PaymentExternalPayment.website_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PaymentID(); ok {
		if err := paymentexternalpayment.PaymentIDValidator(v); err != nil {
			return &ValidationError{Name: "payment_id", err: fmt.Errorf(`ent: validator failed for field "PaymentExternalPayment.payment_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := paymentexternalpayment.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "PaymentExternalPayment.currency": %w`, err)}
		}
	}
	return nil
}

func (_u *PaymentExternalPaymentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paymentexternalpayment.Table, paymentexternalpayment.Columns, sqlgraph.NewFieldSpec(paymentexternalpayment.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProviderKey(); ok {
		_spec.SetField(paymentexternalpayment.FieldProviderKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.WebsiteID(); ok {
		_spec.SetField(paymentexternalpayment.FieldWebsiteID, field.TypeString, value)
	}
	if value, ok := _u.mutation.PaymentID(); ok {
		_spec.SetField(paymentexternalpayment.FieldPaymentID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExternalOrderLedgerID(); ok {
		_spec.SetField(paymentexternalpayment.FieldExternalOrderLedgerID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedExternalOrderLedgerID(); ok {
		_spec.AddField(paymentexternalpayment.FieldExternalOrderLedgerID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(paymentexternalpayment.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.AmountMinor(); ok {
		_spec.SetField(paymentexternalpayment.FieldAmountMinor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAmountMinor(); ok {
		_spec.AddField(paymentexternalpayment.FieldAmountMinor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RefundedMinor(); ok {
		_spec.SetField(paymentexternalpayment.FieldRefundedMinor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRefundedMinor(); ok {
		_spec.AddField(paymentexternalpayment.FieldRefundedMinor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PaidAt(); ok {
		_spec.SetField(paymentexternalpayment.FieldPaidAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentexternalpayment.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentexternalpayment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PaymentExternalPaymentUpdateOne is the builder for updating a single PaymentExternalPayment entity.
type PaymentExternalPaymentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PaymentExternalPaymentMutation
}

// SetProviderKey sets the "provider_key" field.
func (_u *PaymentExternalPaymentUpdateOne) SetProviderKey(v string) *PaymentExternalPaymentUpdateOne {
	_u.mutation.SetProviderKey(v)
	return _u
}

// SetNillableProviderKey sets the "provider_key" field if the given value is not nil.
func (_u *PaymentExternalPaymentUpdateOne) SetNillableProviderKey(v *string) *PaymentExternalPaymentUpdateOne {
	if v != nil {
		_u.SetProviderKey(*v)
	}
	return _u
}

// SetWebsiteID sets the "website_id" field.
func (_u *PaymentExternalPaymentUpdateOne) SetWebsiteID(v string) *PaymentExternalPaymentUpdateOne {
	_u.mutation.SetWebsiteID(v)
	return _u
}

// SetNillableWebsiteID sets the "website_id" field if the given value is not nil.
func (_u *PaymentExternalPaymentUpdateOne) SetNillableWebsiteID(v *string) *PaymentExternalPaymentUpdateOne {
	if v != nil {
		_u.SetWebsiteID(*v)
	}
	return _u
}

// SetPaymentID sets the "payment_id" field.
func (_u *PaymentExternalPaymentUpdateOne) SetPaymentID(v string) *PaymentExternalPaymentUpdateOne {
	_u.mutation.SetPaymentID(v)
	return _u
}

// SetNillablePaymentID sets the "payment_id" field if the given value is not nil.
func (_u *PaymentExternalPaymentUpdateOne) SetNillablePaymentID(v *string) *PaymentExternalPaymentUpdateOne {
	if v != nil {
		_u.SetPaymentID(*v)
	}
	return _u
}

// SetExternalOrderLedgerID sets the "external_order_ledger_id" field.
func (_u *PaymentExternalPaymentUpdateOne) SetExternalOrderLedgerID(v int64) *PaymentExternalPaymentUpdateOne {
	_u.mutation.ResetExternalOrderLedgerID()
	_u.mutation.SetExternalOrderLedgerID(v)
	return _u
}

// SetNillableExternalOrderLedgerID sets the "external_order_ledger_id" field if the given value is not nil.
func (_u *PaymentExternalPaymentUpdateOne) SetNillableExternalOrderLedgerID(v *int64) *PaymentExternalPaymentUpdateOne {
	if v != nil {
		_u.SetExternalOrderLedgerID(*v)
	}
	return _u
}

// AddExternalOrderLedgerID adds value to the "external_order_ledger_id" field.
func (_u *PaymentExternalPaymentUpdateOne) AddExternalOrderLedgerID(v int64) *PaymentExternalPaymentUpdateOne {
	_u.mutation.AddExternalOrderLedgerID(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *PaymentExternalPaymentUpdateOne) SetCurrency(v string) *PaymentExternalPaymentUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *PaymentExternalPaymentUpdateOne) SetNillableCurrency(v *string) *PaymentExternalPaymentUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetAmountMinor sets the "amount_minor" field.
func (_u *PaymentExternalPaymentUpdateOne) SetAmountMinor(v int64) *PaymentExternalPaymentUpdateOne {
	_u.mutation.ResetAmountMinor()
	_u.mutation.SetAmountMinor(v)
	return _u
}

// SetNillableAmountMinor sets the "amount_minor" field if the given value is not nil.
func (_u *PaymentExternalPaymentUpdateOne) SetNillableAmountMinor(v *int64) *PaymentExternalPaymentUpdateOne {
	if v != nil {
		_u.SetAmountMinor(*v)
	}
	return _u
}

// AddAmountMinor adds value to the "amount_minor" field.
func (_u *PaymentExternalPaymentUpdateOne) AddAmountMinor(v int64) *PaymentExternalPaymentUpdateOne {
	_u.mutation.AddAmountMinor(v)
	return _u
}

// SetRefundedMinor sets the "refunded_minor" field.
func (_u *PaymentExternalPaymentUpdateOne) SetRefundedMinor(v int64) *PaymentExternalPaymentUpdateOne {
	_u.mutation.ResetRefundedMinor()
	_u.mutation.SetRefundedMinor(v)
	return _u
}

// SetNillableRefundedMinor sets the "refunded_minor" field if the given value is not nil.
func (_u *PaymentExternalPaymentUpdateOne) SetNillableRefundedMinor(v *int64) *PaymentExternalPaymentUpdateOne {
	if v != nil {
		_u.SetRefundedMinor(*v)
	}
	return _u
}

// AddRefundedMinor adds value to the "refunded_minor" field.
func (_u *PaymentExternalPaymentUpdateOne) AddRefundedMinor(v int64) *PaymentExternalPaymentUpdateOne {
	_u.mutation.AddRefundedMinor(v)
	return _u
}

// SetPaidAt sets the "paid_at" field.
func (_u *PaymentExternalPaymentUpdateOne) SetPaidAt(v time.Time) *PaymentExternalPaymentUpdateOne {
	_u.mutation.SetPaidAt(v)
	return _u
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_u *PaymentExternalPaymentUpdateOne) SetNillablePaidAt(v *time.Time) *PaymentExternalPaymentUpdateOne {
	if v != nil {
		_u.SetPaidAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PaymentExternalPaymentUpdateOne) SetUpdatedAt(v time.Time) *PaymentExternalPaymentUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PaymentExternalPaymentMutation object of the builder.
func (_u *PaymentExternalPaymentUpdateOne) Mutation() *PaymentExternalPaymentMutation {
	return _u.mutation
}

// Where appends a list predicates to the PaymentExternalPaymentUpdate builder.
func (_u *PaymentExternalPaymentUpdateOne) Where(ps ...predicate.PaymentExternalPayment) *PaymentExternalPaymentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PaymentExternalPaymentUpdateOne) Select(field string, fields ...string) *PaymentExternalPaymentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PaymentExternalPayment entity.
func (_u *PaymentExternalPaymentUpdateOne) Save(ctx context.Context) (*PaymentExternalPayment, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentExternalPaymentUpdateOne) SaveX(ctx context.Context) *PaymentExternalPayment {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PaymentExternalPaymentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentExternalPaymentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaymentExternalPaymentUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := paymentexternalpayment.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentExternalPaymentUpdateOne) check() error {
	if v, ok := _u.mutation.ProviderKey(); ok {
		if err := paymentexternalpayment.ProviderKeyValidator(v); err != nil {
			return &ValidationError{Name: "provider_key", err: fmt.Errorf(`ent: validator failed for field "PaymentExternalPayment.provider_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WebsiteID(); ok {
		if err := paymentexternalpayment.WebsiteIDValidator(v); err != nil {
			return &ValidationError{Name: "website_id", err: fmt.Errorf(`ent: validator failed for field "PaymentExternalPayment.website_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PaymentID(); ok {
		if err := paymentexternalpayment.PaymentIDValidator(v); err != nil {
			return &ValidationError{Name: "payment_id", err: fmt.Errorf(`ent: validator failed for field "PaymentExternalPayment.payment_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := paymentexternalpayment.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "PaymentExternalPayment.currency": %w`, err)}
		}
	}
	return nil
}

func (_u *PaymentExternalPaymentUpdateOne) sqlSave(ctx context.Context) (_node *PaymentExternalPayment, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paymentexternalpayment.Table, paymentexternalpayment.Columns, sqlgraph.NewFieldSpec(paymentexternalpayment.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PaymentExternalPayment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, paymentexternalpayment.FieldID)
		for _, f := range fields {
			if !paymentexternalpayment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != paymentexternalpayment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProviderKey(); ok {
		_spec.SetField(paymentexternalpayment.FieldProviderKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.WebsiteID(); ok {
		_spec.SetField(paymentexternalpayment.FieldWebsiteID, field.TypeString, value)
	}
	if value, ok := _u.mutation.PaymentID(); ok {
		_spec.SetField(paymentexternalpayment.FieldPaymentID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExternalOrderLedgerID(); ok {
		_spec.SetField(paymentexternalpayment.FieldExternalOrderLedgerID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedExternalOrderLedgerID(); ok {
		_spec.AddField(paymentexternalpayment.FieldExternalOrderLedgerID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(paymentexternalpayment.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.AmountMinor(); ok {
		_spec.SetField(paymentexternalpayment.FieldAmountMinor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAmountMinor(); ok {
		_spec.AddField(paymentexternalpayment.FieldAmountMinor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RefundedMinor(); ok {
		_spec.SetField(paymentexternalpayment.FieldRefundedMinor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRefundedMinor(); ok {
		_spec.AddField(paymentexternalpayment.FieldRefundedMinor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PaidAt(); ok {
		_spec.SetField(paymentexternalpayment.FieldPaidAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentexternalpayment.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &PaymentExternalPayment{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentexternalpayment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
