// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/paymentexternalrefundjournal"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// PaymentExternalRefundJournalUpdate is the builder for updating PaymentExternalRefundJournal entities.
type PaymentExternalRefundJournalUpdate struct {
	config
	hooks    []Hook
	mutation *PaymentExternalRefundJournalMutation
}

// Where appends a list predicates to the PaymentExternalRefundJournalUpdate builder.
func (_u *PaymentExternalRefundJournalUpdate) Where(ps ...predicate.PaymentExternalRefundJournal) *PaymentExternalRefundJournalUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetExternalOrderLedgerID sets the "external_order_ledger_id" field.
func (_u *PaymentExternalRefundJournalUpdate) SetExternalOrderLedgerID(v int64) *PaymentExternalRefundJournalUpdate {
	_u.mutation.ResetExternalOrderLedgerID()
	_u.mutation.SetExternalOrderLedgerID(v)
	return _u
}

// SetNillableExternalOrderLedgerID sets the "external_order_ledger_id" field if the given value is not nil.
func (_u *PaymentExternalRefundJournalUpdate) SetNillableExternalOrderLedgerID(v *int64) *PaymentExternalRefundJournalUpdate {
	if v != nil {
		_u.SetExternalOrderLedgerID(*v)
	}
	return _u
}

// AddExternalOrderLedgerID adds value to the "external_order_ledger_id" field.
func (_u *PaymentExternalRefundJournalUpdate) AddExternalOrderLedgerID(v int64) *PaymentExternalRefundJournalUpdate {
	_u.mutation.AddExternalOrderLedgerID(v)
	return _u
}

// SetCumulativeRefundMinor sets the "cumulative_refund_minor" field.
func (_u *PaymentExternalRefundJournalUpdate) SetCumulativeRefundMinor(v int64) *PaymentExternalRefundJournalUpdate {
	_u.mutation.ResetCumulativeRefundMinor()
	_u.mutation.SetCumulativeRefundMinor(v)
	return _u
}

// SetNillableCumulativeRefundMinor sets the "cumulative_refund_minor" field if the given value is not nil.
func (_u *PaymentExternalRefundJournalUpdate) SetNillableCumulativeRefundMinor(v *int64) *PaymentExternalRefundJournalUpdate {
	if v != nil {
		_u.SetCumulativeRefundMinor(*v)
	}
	return _u
}

// AddCumulativeRefundMinor adds value to the "cumulative_refund_minor" field.
func (_u *PaymentExternalRefundJournalUpdate) AddCumulativeRefundMinor(v int64) *PaymentExternalRefundJournalUpdate {
	_u.mutation.AddCumulativeRefundMinor(v)
	return _u
}

// SetDeltaRefundMinor sets the "delta_refund_minor" field.
func (_u *PaymentExternalRefundJournalUpdate) SetDeltaRefundMinor(v int64) *PaymentExternalRefundJournalUpdate {
	_u.mutation.ResetDeltaRefundMinor()
	_u.mutation.SetDeltaRefundMinor(v)
	return _u
}

// SetNillableDeltaRefundMinor sets the "delta_refund_minor" field if the given value is not nil.
func (_u *PaymentExternalRefundJournalUpdate) SetNillableDeltaRefundMinor(v *int64) *PaymentExternalRefundJournalUpdate {
	if v != nil {
		_u.SetDeltaRefundMinor(*v)
	}
	return _u
}

// AddDeltaRefundMinor adds value to the "delta_refund_minor" field.
func (_u *PaymentExternalRefundJournalUpdate) AddDeltaRefundMinor(v int64) *PaymentExternalRefundJournalUpdate {
	_u.mutation.AddDeltaRefundMinor(v)
	return _u
}

// SetTargetUsdUnits sets the "target_usd_units" field.
func (_u *PaymentExternalRefundJournalUpdate) SetTargetUsdUnits(v int64) *PaymentExternalRefundJournalUpdate {
	_u.mutation.ResetTargetUsdUnits()
	_u.mutation.SetTargetUsdUnits(v)
	return _u
}

// SetNillableTargetUsdUnits sets the "target_usd_units" field if the given value is not nil.
func (_u *PaymentExternalRefundJournalUpdate) SetNillableTargetUsdUnits(v *int64) *PaymentExternalRefundJournalUpdate {
	if v != nil {
		_u.SetTargetUsdUnits(*v)
	}
	return _u
}

// AddTargetUsdUnits adds value to the "target_usd_units" field.
func (_u *PaymentExternalRefundJournalUpdate) AddTargetUsdUnits(v int64) *PaymentExternalRefundJournalUpdate {
	_u.mutation.AddTargetUsdUnits(v)
	return _u
}

// SetDeltaTargetUsdUnits sets the "delta_target_usd_units" field.
func (_u *PaymentExternalRefundJournalUpdate) SetDeltaTargetUsdUnits(v int64) *PaymentExternalRefundJournalUpdate {
	_u.mutation.ResetDeltaTargetUsdUnits()
	_u.mutation.SetDeltaTargetUsdUnits(v)
	return _u
}

// SetNillableDeltaTargetUsdUnits sets the "delta_target_usd_units" field if the given value is not nil.
func (_u *PaymentExternalRefundJournalUpdate) SetNillableDeltaTargetUsdUnits(v *int64) *PaymentExternalRefundJournalUpdate {
	if v != nil {
		_u.SetDeltaTargetUsdUnits(*v)
	}
	return _u
}

// AddDeltaTargetUsdUnits adds value to the "delta_target_usd_units" field.
func (_u *PaymentExternalRefundJournalUpdate) AddDeltaTargetUsdUnits(v int64) *PaymentExternalRefundJournalUpdate {
	_u.mutation.AddDeltaTargetUsdUnits(v)
	return _u
}

// SetRecoveredUsdUnits sets the "recovered_usd_units" field.
func (_u *PaymentExternalRefundJournalUpdate) SetRecoveredUsdUnits(v int64) *PaymentExternalRefundJournalUpdate {
	_u.mutation.ResetRecoveredUsdUnits()
	_u.mutation.SetRecoveredUsdUnits(v)
	return _u
}

// SetNillableRecoveredUsdUnits sets the "recovered_usd_units" field if the given value is not nil.
func (_u *PaymentExternalRefundJournalUpdate) SetNillableRecoveredUsdUnits(v *int64) *PaymentExternalRefundJournalUpdate {
	if v != nil {
		_u.SetRecoveredUsdUnits(*v)
	}
	return _u
}

// AddRecoveredUsdUnits adds value to the "recovered_usd_units" field.
func (_u *PaymentExternalRefundJournalUpdate) AddRecoveredUsdUnits(v int64) *PaymentExternalRefundJournalUpdate {
	_u.mutation.AddRecoveredUsdUnits(v)
	return _u
}

// SetDebtUsdUnits sets the "debt_usd_units" field.
func (_u *PaymentExternalRefundJournalUpdate) SetDebtUsdUnits(v int64) *PaymentExternalRefundJournalUpdate {
	_u.mutation.ResetDebtUsdUnits()
	_u.mutation.SetDebtUsdUnits(v)
	return _u
}

// SetNillableDebtUsdUnits sets the "debt_usd_units" field if the given value is not nil.
func (_u *PaymentExternalRefundJournalUpdate) SetNillableDebtUsdUnits(v *int64) *PaymentExternalRefundJournalUpdate {
	if v != nil {
		_u.SetDebtUsdUnits(*v)
	}
	return _u
}

// AddDebtUsdUnits adds value to the "debt_usd_units" field.
func (_u *PaymentExternalRefundJournalUpdate) AddDebtUsdUnits(v int64) *PaymentExternalRefundJournalUpdate {
	_u.mutation.AddDebtUsdUnits(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *PaymentExternalRefundJournalUpdate) SetStatus(v string) *PaymentExternalRefundJournalUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PaymentExternalRefundJournalUpdate) SetNillableStatus(v *string) *PaymentExternalRefundJournalUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PaymentExternalRefundJournalUpdate) SetUpdatedAt(v time.Time) *PaymentExternalRefundJournalUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PaymentExternalRefundJournalMutation object of the builder.
func (_u *PaymentExternalRefundJournalUpdate) Mutation() *PaymentExternalRefundJournalMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PaymentExternalRefundJournalUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentExternalRefundJournalUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PaymentExternalRefundJournalUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentExternalRefundJournalUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaymentExternalRefundJournalUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := paymentexternalrefundjournal.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentExternalRefundJournalUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := paymentexternalrefundjournal.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PaymentExternalRefundJournal.status": %w`, err)}
		}
	}
	return nil
}

func (_u *PaymentExternalRefundJournalUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paymentexternalrefundjournal.Table, paymentexternalrefundjournal.Columns, sqlgraph.NewFieldSpec(paymentexternalrefundjournal.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ExternalOrderLedgerID(); ok {
		_spec.SetField(paymentexternalrefundjournal.FieldExternalOrderLedgerID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedExternalOrderLedgerID(); ok {
		_spec.AddField(paymentexternalrefundjournal.FieldExternalOrderLedgerID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CumulativeRefundMinor(); ok {
		_spec.SetField(paymentexternalrefundjournal.FieldCumulativeRefundMinor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCumulativeRefundMinor(); ok {
		_spec.AddField(paymentexternalrefundjournal.FieldCumulativeRefundMinor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DeltaRefundMinor(); ok {
		_spec.SetField(paymentexternalrefundjournal.FieldDeltaRefundMinor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDeltaRefundMinor(); ok {
		_spec.AddField(paymentexternalrefundjournal.FieldDeltaRefundMinor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TargetUsdUnits(); ok {
		_spec.SetField(paymentexternalrefundjournal.FieldTargetUsdUnits, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTargetUsdUnits(); ok {
		_spec.AddField(paymentexternalrefundjournal.FieldTargetUsdUnits, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DeltaTargetUsdUnits(); ok {
		_spec.SetField(paymentexternalrefundjournal.FieldDeltaTargetUsdUnits, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDeltaTargetUsdUnits(); ok {
		_spec.AddField(paymentexternalrefundjournal.FieldDeltaTargetUsdUnits, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RecoveredUsdUnits(); ok {
		_spec.SetField(paymentexternalrefundjournal.FieldRecoveredUsdUnits, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRecoveredUsdUnits(); ok {
		_spec.AddField(paymentexternalrefundjournal.FieldRecoveredUsdUnits, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DebtUsdUnits(); ok {
		_spec.SetField(paymentexternalrefundjournal.FieldDebtUsdUnits, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDebtUsdUnits(); ok {
		_spec.AddField(paymentexternalrefundjournal.FieldDebtUsdUnits, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(paymentexternalrefundjournal.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentexternalrefundjournal.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentexternalrefundjournal.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PaymentExternalRefundJournalUpdateOne is the builder for updating a single PaymentExternalRefundJournal entity.
type PaymentExternalRefundJournalUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PaymentExternalRefundJournalMutation
}

// SetExternalOrderLedgerID sets the "external_order_ledger_id" field.
func (_u *PaymentExternalRefundJournalUpdateOne) SetExternalOrderLedgerID(v int64) *PaymentExternalRefundJournalUpdateOne {
	_u.mutation.ResetExternalOrderLedgerID()
	_u.mutation.SetExternalOrderLedgerID(v)
	return _u
}

// SetNillableExternalOrderLedgerID sets the "external_order_ledger_id" field if the given value is not nil.
func (_u *PaymentExternalRefundJournalUpdateOne) SetNillableExternalOrderLedgerID(v *int64) *PaymentExternalRefundJournalUpdateOne {
	if v != nil {
		_u.SetExternalOrderLedgerID(*v)
	}
	return _u
}

// AddExternalOrderLedgerID adds value to the "external_order_ledger_id" field.
func (_u *PaymentExternalRefundJournalUpdateOne) AddExternalOrderLedgerID(v int64) *PaymentExternalRefundJournalUpdateOne {
	_u.mutation.AddExternalOrderLedgerID(v)
	return _u
}

// SetCumulativeRefundMinor sets the "cumulative_refund_minor" field.
func (_u *PaymentExternalRefundJournalUpdateOne) SetCumulativeRefundMinor(v int64) *PaymentExternalRefundJournalUpdateOne {
	_u.mutation.ResetCumulativeRefundMinor()
	_u.mutation.SetCumulativeRefundMinor(v)
	return _u
}

// SetNillableCumulativeRefundMinor sets the "cumulative_refund_minor" field if the given value is not nil.
func (_u *PaymentExternalRefundJournalUpdateOne) SetNillableCumulativeRefundMinor(v *int64) *PaymentExternalRefundJournalUpdateOne {
	if v != nil {
		_u.SetCumulativeRefundMinor(*v)
	}
	return _u
}

// AddCumulativeRefundMinor adds value to the "cumulative_refund_minor" field.
func (_u *PaymentExternalRefundJournalUpdateOne) AddCumulativeRefundMinor(v int64) *PaymentExternalRefundJournalUpdateOne {
	_u.mutation.AddCumulativeRefundMinor(v)
	return _u
}

// SetDeltaRefundMinor sets the "delta_refund_minor" field.
func (_u *PaymentExternalRefundJournalUpdateOne) SetDeltaRefundMinor(v int64) *PaymentExternalRefundJournalUpdateOne {
	_u.mutation.ResetDeltaRefundMinor()
	_u.mutation.SetDeltaRefundMinor(v)
	return _u
}

// SetNillableDeltaRefundMinor sets the "delta_refund_minor" field if the given value is not nil.
func (_u *PaymentExternalRefundJournalUpdateOne) SetNillableDeltaRefundMinor(v *int64) *PaymentExternalRefundJournalUpdateOne {
	if v != nil {
		_u.SetDeltaRefundMinor(*v)
	}
	return _u
}

// AddDeltaRefundMinor adds value to the "delta_refund_minor" field.
func (_u *PaymentExternalRefundJournalUpdateOne) AddDeltaRefundMinor(v int64) *PaymentExternalRefundJournalUpdateOne {
	_u.mutation.AddDeltaRefundMinor(v)
	return _u
}

// SetTargetUsdUnits sets the "target_usd_units" field.
func (_u *PaymentExternalRefundJournalUpdateOne) SetTargetUsdUnits(v int64) *PaymentExternalRefundJournalUpdateOne {
	_u.mutation.ResetTargetUsdUnits()
	_u.mutation.SetTargetUsdUnits(v)
	return _u
}

// SetNillableTargetUsdUnits sets the "target_usd_units" field if the given value is not nil.
func (_u *PaymentExternalRefundJournalUpdateOne) SetNillableTargetUsdUnits(v *int64) *PaymentExternalRefundJournalUpdateOne {
	if v != nil {
		_u.SetTargetUsdUnits(*v)
	}
	return _u
}

// AddTargetUsdUnits adds value to the "target_usd_units" field.
func (_u *PaymentExternalRefundJournalUpdateOne) AddTargetUsdUnits(v int64) *PaymentExternalRefundJournalUpdateOne {
	_u.mutation.AddTargetUsdUnits(v)
	return _u
}

// SetDeltaTargetUsdUnits sets the "delta_target_usd_units" field.
func (_u *PaymentExternalRefundJournalUpdateOne) SetDeltaTargetUsdUnits(v int64) *PaymentExternalRefundJournalUpdateOne {
	_u.mutation.ResetDeltaTargetUsdUnits()
	_u.mutation.SetDeltaTargetUsdUnits(v)
	return _u
}

// SetNillableDeltaTargetUsdUnits sets the "delta_target_usd_units" field if the given value is not nil.
func (_u *PaymentExternalRefundJournalUpdateOne) SetNillableDeltaTargetUsdUnits(v *int64) *PaymentExternalRefundJournalUpdateOne {
	if v != nil {
		_u.SetDeltaTargetUsdUnits(*v)
	}
	return _u
}

// AddDeltaTargetUsdUnits adds value to the "delta_target_usd_units" field.
func (_u *PaymentExternalRefundJournalUpdateOne) AddDeltaTargetUsdUnits(v int64) *PaymentExternalRefundJournalUpdateOne {
	_u.mutation.AddDeltaTargetUsdUnits(v)
	return _u
}

// SetRecoveredUsdUnits sets the "recovered_usd_units" field.
func (_u *PaymentExternalRefundJournalUpdateOne) SetRecoveredUsdUnits(v int64) *PaymentExternalRefundJournalUpdateOne {
	_u.mutation.ResetRecoveredUsdUnits()
	_u.mutation.SetRecoveredUsdUnits(v)
	return _u
}

// SetNillableRecoveredUsdUnits sets the "recovered_usd_units" field if the given value is not nil.
func (_u *PaymentExternalRefundJournalUpdateOne) SetNillableRecoveredUsdUnits(v *int64) *PaymentExternalRefundJournalUpdateOne {
	if v != nil {
		_u.SetRecoveredUsdUnits(*v)
	}
	return _u
}

// AddRecoveredUsdUnits adds value to the "recovered_usd_units" field.
func (_u *PaymentExternalRefundJournalUpdateOne) AddRecoveredUsdUnits(v int64) *PaymentExternalRefundJournalUpdateOne {
	_u.mutation.AddRecoveredUsdUnits(v)
	return _u
}

// SetDebtUsdUnits sets the "debt_usd_units" field.
func (_u *PaymentExternalRefundJournalUpdateOne) SetDebtUsdUnits(v int64) *PaymentExternalRefundJournalUpdateOne {
	_u.mutation.ResetDebtUsdUnits()
	_u.mutation.SetDebtUsdUnits(v)
	return _u
}

// SetNillableDebtUsdUnits sets the "debt_usd_units" field if the given value is not nil.
func (_u *PaymentExternalRefundJournalUpdateOne) SetNillableDebtUsdUnits(v *int64) *PaymentExternalRefundJournalUpdateOne {
	if v != nil {
		_u.SetDebtUsdUnits(*v)
	}
	return _u
}

// AddDebtUsdUnits adds value to the "debt_usd_units" field.
func (_u *PaymentExternalRefundJournalUpdateOne) AddDebtUsdUnits(v int64) *PaymentExternalRefundJournalUpdateOne {
	_u.mutation.AddDebtUsdUnits(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *PaymentExternalRefundJournalUpdateOne) SetStatus(v string) *PaymentExternalRefundJournalUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PaymentExternalRefundJournalUpdateOne) SetNillableStatus(v *string) *PaymentExternalRefundJournalUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PaymentExternalRefundJournalUpdateOne) SetUpdatedAt(v time.Time) *PaymentExternalRefundJournalUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PaymentExternalRefundJournalMutation object of the builder.
func (_u *PaymentExternalRefundJournalUpdateOne) Mutation() *PaymentExternalRefundJournalMutation {
	return _u.mutation
}

// Where appends a list predicates to the PaymentExternalRefundJournalUpdate builder.
func (_u *PaymentExternalRefundJournalUpdateOne) Where(ps ...predicate.PaymentExternalRefundJournal) *PaymentExternalRefundJournalUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PaymentExternalRefundJournalUpdateOne) Select(field string, fields ...string) *PaymentExternalRefundJournalUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PaymentExternalRefundJournal entity.
func (_u *PaymentExternalRefundJournalUpdateOne) Save(ctx context.Context) (*PaymentExternalRefundJournal, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentExternalRefundJournalUpdateOne) SaveX(ctx context.Context) *PaymentExternalRefundJournal {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PaymentExternalRefundJournalUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentExternalRefundJournalUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaymentExternalRefundJournalUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := paymentexternalrefundjournal.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentExternalRefundJournalUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := paymentexternalrefundjournal.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PaymentExternalRefundJournal.status": %w`, err)}
		}
	}
	return nil
}

func (_u *PaymentExternalRefundJournalUpdateOne) sqlSave(ctx context.Context) (_node *PaymentExternalRefundJournal, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paymentexternalrefundjournal.Table, paymentexternalrefundjournal.Columns, sqlgraph.NewFieldSpec(paymentexternalrefundjournal.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PaymentExternalRefundJournal.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, paymentexternalrefundjournal.FieldID)
		for _, f := range fields {
			if !paymentexternalrefundjournal.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != paymentexternalrefundjournal.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ExternalOrderLedgerID(); ok {
		_spec.SetField(paymentexternalrefundjournal.FieldExternalOrderLedgerID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedExternalOrderLedgerID(); ok {
		_spec.AddField(paymentexternalrefundjournal.FieldExternalOrderLedgerID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CumulativeRefundMinor(); ok {
		_spec.SetField(paymentexternalrefundjournal.FieldCumulativeRefundMinor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCumulativeRefundMinor(); ok {
		_spec.AddField(paymentexternalrefundjournal.FieldCumulativeRefundMinor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DeltaRefundMinor(); ok {
		_spec.SetField(paymentexternalrefundjournal.FieldDeltaRefundMinor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDeltaRefundMinor(); ok {
		_spec.AddField(paymentexternalrefundjournal.FieldDeltaRefundMinor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TargetUsdUnits(); ok {
		_spec.SetField(paymentexternalrefundjournal.FieldTargetUsdUnits, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTargetUsdUnits(); ok {
		_spec.AddField(paymentexternalrefundjournal.FieldTargetUsdUnits, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DeltaTargetUsdUnits(); ok {
		_spec.SetField(paymentexternalrefundjournal.FieldDeltaTargetUsdUnits, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDeltaTargetUsdUnits(); ok {
		_spec.AddField(paymentexternalrefundjournal.FieldDeltaTargetUsdUnits, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RecoveredUsdUnits(); ok {
		_spec.SetField(paymentexternalrefundjournal.FieldRecoveredUsdUnits, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRecoveredUsdUnits(); ok {
		_spec.AddField(paymentexternalrefundjournal.FieldRecoveredUsdUnits, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DebtUsdUnits(); ok {
		_spec.SetField(paymentexternalrefundjournal.FieldDebtUsdUnits, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDebtUsdUnits(); ok {
		_spec.AddField(paymentexternalrefundjournal.FieldDebtUsdUnits, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(paymentexternalrefundjournal.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentexternalrefundjournal.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &PaymentExternalRefundJournal{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentexternalrefundjournal.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
