// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/paymentexternalorder"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// PaymentExternalOrderUpdate is the builder for updating PaymentExternalOrder entities.
type PaymentExternalOrderUpdate struct {
	config
	hooks    []Hook
	mutation *PaymentExternalOrderMutation
}

// Where appends a list predicates to the PaymentExternalOrderUpdate builder.
func (_u *PaymentExternalOrderUpdate) Where(ps ...predicate.PaymentExternalOrder) *PaymentExternalOrderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProviderKey sets the "provider_key" field.
func (_u *PaymentExternalOrderUpdate) SetProviderKey(v string) *PaymentExternalOrderUpdate {
	_u.mutation.SetProviderKey(v)
	return _u
}

// SetNillableProviderKey sets the "provider_key" field if the given value is not nil.
func (_u *PaymentExternalOrderUpdate) SetNillableProviderKey(v *string) *PaymentExternalOrderUpdate {
	if v != nil {
		_u.SetProviderKey(*v)
	}
	return _u
}

// SetWebsiteID sets the "website_id" field.
func (_u *PaymentExternalOrderUpdate) SetWebsiteID(v string) *PaymentExternalOrderUpdate {
	_u.mutation.SetWebsiteID(v)
	return _u
}

// SetNillableWebsiteID sets the "website_id" field if the given value is not nil.
func (_u *PaymentExternalOrderUpdate) SetNillableWebsiteID(v *string) *PaymentExternalOrderUpdate {
	if v != nil {
		_u.SetWebsiteID(*v)
	}
	return _u
}

// SetExternalOrderID sets the "external_order_id" field.
func (_u *PaymentExternalOrderUpdate) SetExternalOrderID(v string) *PaymentExternalOrderUpdate {
	_u.mutation.SetExternalOrderID(v)
	return _u
}

// SetNillableExternalOrderID sets the "external_order_id" field if the given value is not nil.
func (_u *PaymentExternalOrderUpdate) SetNillableExternalOrderID(v *string) *PaymentExternalOrderUpdate {
	if v != nil {
		_u.SetExternalOrderID(*v)
	}
	return _u
}

// SetOrderNumber sets the "order_number" field.
func (_u *PaymentExternalOrderUpdate) SetOrderNumber(v string) *PaymentExternalOrderUpdate {
	_u.mutation.SetOrderNumber(v)
	return _u
}

// SetNillableOrderNumber sets the "order_number" field if the given value is not nil.
func (_u *PaymentExternalOrderUpdate) SetNillableOrderNumber(v *string) *PaymentExternalOrderUpdate {
	if v != nil {
		_u.SetOrderNumber(*v)
	}
	return _u
}

// SetBindingMethod sets the "binding_method" field.
func (_u *PaymentExternalOrderUpdate) SetBindingMethod(v string) *PaymentExternalOrderUpdate {
	_u.mutation.SetBindingMethod(v)
	return _u
}

// SetNillableBindingMethod sets the "binding_method" field if the given value is not nil.
func (_u *PaymentExternalOrderUpdate) SetNillableBindingMethod(v *string) *PaymentExternalOrderUpdate {
	if v != nil {
		_u.SetBindingMethod(*v)
	}
	return _u
}

// SetQuoteHash sets the "quote_hash" field.
func (_u *PaymentExternalOrderUpdate) SetQuoteHash(v string) *PaymentExternalOrderUpdate {
	_u.mutation.SetQuoteHash(v)
	return _u
}

// SetNillableQuoteHash sets the "quote_hash" field if the given value is not nil.
func (_u *PaymentExternalOrderUpdate) SetNillableQuoteHash(v *string) *PaymentExternalOrderUpdate {
	if v != nil {
		_u.SetQuoteHash(*v)
	}
	return _u
}

// SetLocalOrderID sets the "local_order_id" field.
func (_u *PaymentExternalOrderUpdate) SetLocalOrderID(v int64) *PaymentExternalOrderUpdate {
	_u.mutation.ResetLocalOrderID()
	_u.mutation.SetLocalOrderID(v)
	return _u
}

// SetNillableLocalOrderID sets the "local_order_id" field if the given value is not nil.
func (_u *PaymentExternalOrderUpdate) SetNillableLocalOrderID(v *int64) *PaymentExternalOrderUpdate {
	if v != nil {
		_u.SetLocalOrderID(*v)
	}
	return _u
}

// AddLocalOrderID adds value to the "local_order_id" field.
func (_u *PaymentExternalOrderUpdate) AddLocalOrderID(v int64) *PaymentExternalOrderUpdate {
	_u.mutation.AddLocalOrderID(v)
	return _u
}

// ClearLocalOrderID clears the value of the "local_order_id" field.
func (_u *PaymentExternalOrderUpdate) ClearLocalOrderID() *PaymentExternalOrderUpdate {
	_u.mutation.ClearLocalOrderID()
	return _u
}

// SetCheckoutReference sets the "checkout_reference" field.
func (_u *PaymentExternalOrderUpdate) SetCheckoutReference(v string) *PaymentExternalOrderUpdate {
	_u.mutation.SetCheckoutReference(v)
	return _u
}

// SetNillableCheckoutReference sets the "checkout_reference" field if the given value is not nil.
func (_u *PaymentExternalOrderUpdate) SetNillableCheckoutReference(v *string) *PaymentExternalOrderUpdate {
	if v != nil {
		_u.SetCheckoutReference(*v)
	}
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *PaymentExternalOrderUpdate) SetCurrency(v string) *PaymentExternalOrderUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *PaymentExternalOrderUpdate) SetNillableCurrency(v *string) *PaymentExternalOrderUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetTotalMinor sets the "total_minor" field.
func (_u *PaymentExternalOrderUpdate) SetTotalMinor(v int64) *PaymentExternalOrderUpdate {
	_u.mutation.ResetTotalMinor()
	_u.mutation.SetTotalMinor(v)
	return _u
}

// SetNillableTotalMinor sets the "total_minor" field if the given value is not nil.
func (_u *PaymentExternalOrderUpdate) SetNillableTotalMinor(v *int64) *PaymentExternalOrderUpdate {
	if v != nil {
		_u.SetTotalMinor(*v)
	}
	return _u
}

// AddTotalMinor adds value to the "total_minor" field.
func (_u *PaymentExternalOrderUpdate) AddTotalMinor(v int64) *PaymentExternalOrderUpdate {
	_u.mutation.AddTotalMinor(v)
	return _u
}

// SetRefundedMinor sets the "refunded_minor" field.
func (_u *PaymentExternalOrderUpdate) SetRefundedMinor(v int64) *PaymentExternalOrderUpdate {
	_u.mutation.ResetRefundedMinor()
	_u.mutation.SetRefundedMinor(v)
	return _u
}

// SetNillableRefundedMinor sets the "refunded_minor" field if the given value is not nil.
func (_u *PaymentExternalOrderUpdate) SetNillableRefundedMinor(v *int64) *PaymentExternalOrderUpdate {
	if v != nil {
		_u.SetRefundedMinor(*v)
	}
	return _u
}

// AddRefundedMinor adds value to the "refunded_minor" field.
func (_u *PaymentExternalOrderUpdate) AddRefundedMinor(v int64) *PaymentExternalOrderUpdate {
	_u.mutation.AddRefundedMinor(v)
	return _u
}

// SetCreditedUsdUnits sets the "credited_usd_units" field.
func (_u *PaymentExternalOrderUpdate) SetCreditedUsdUnits(v int64) *PaymentExternalOrderUpdate {
	_u.mutation.ResetCreditedUsdUnits()
	_u.mutation.SetCreditedUsdUnits(v)
	return _u
}

// SetNillableCreditedUsdUnits sets the "credited_usd_units" field if the given value is not nil.
func (_u *PaymentExternalOrderUpdate) SetNillableCreditedUsdUnits(v *int64) *PaymentExternalOrderUpdate {
	if v != nil {
		_u.SetCreditedUsdUnits(*v)
	}
	return _u
}

// AddCreditedUsdUnits adds value to the "credited_usd_units" field.
func (_u *PaymentExternalOrderUpdate) AddCreditedUsdUnits(v int64) *PaymentExternalOrderUpdate {
	_u.mutation.AddCreditedUsdUnits(v)
	return _u
}

// SetRefundTargetUsdUnits sets the "refund_target_usd_units" field.
func (_u *PaymentExternalOrderUpdate) SetRefundTargetUsdUnits(v int64) *PaymentExternalOrderUpdate {
	_u.mutation.ResetRefundTargetUsdUnits()
	_u.mutation.SetRefundTargetUsdUnits(v)
	return _u
}

// SetNillableRefundTargetUsdUnits sets the "refund_target_usd_units" field if the given value is not nil.
func (_u *PaymentExternalOrderUpdate) SetNillableRefundTargetUsdUnits(v *int64) *PaymentExternalOrderUpdate {
	if v != nil {
		_u.SetRefundTargetUsdUnits(*v)
	}
	return _u
}

// AddRefundTargetUsdUnits adds value to the "refund_target_usd_units" field.
func (_u *PaymentExternalOrderUpdate) AddRefundTargetUsdUnits(v int64) *PaymentExternalOrderUpdate {
	_u.mutation.AddRefundTargetUsdUnits(v)
	return _u
}

// SetRecoveredUsdUnits sets the "recovered_usd_units" field.
func (_u *PaymentExternalOrderUpdate) SetRecoveredUsdUnits(v int64) *PaymentExternalOrderUpdate {
	_u.mutation.ResetRecoveredUsdUnits()
	_u.mutation.SetRecoveredUsdUnits(v)
	return _u
}

// SetNillableRecoveredUsdUnits sets the "recovered_usd_units" field if the given value is not nil.
func (_u *PaymentExternalOrderUpdate) SetNillableRecoveredUsdUnits(v *int64) *PaymentExternalOrderUpdate {
	if v != nil {
		_u.SetRecoveredUsdUnits(*v)
	}
	return _u
}

// AddRecoveredUsdUnits adds value to the "recovered_usd_units" field.
func (_u *PaymentExternalOrderUpdate) AddRecoveredUsdUnits(v int64) *PaymentExternalOrderUpdate {
	_u.mutation.AddRecoveredUsdUnits(v)
	return _u
}

// SetDebtUsdUnits sets the "debt_usd_units" field.
func (_u *PaymentExternalOrderUpdate) SetDebtUsdUnits(v int64) *PaymentExternalOrderUpdate {
	_u.mutation.ResetDebtUsdUnits()
	_u.mutation.SetDebtUsdUnits(v)
	return _u
}

// SetNillableDebtUsdUnits sets the "debt_usd_units" field if the given value is not nil.
func (_u *PaymentExternalOrderUpdate) SetNillableDebtUsdUnits(v *int64) *PaymentExternalOrderUpdate {
	if v != nil {
		_u.SetDebtUsdUnits(*v)
	}
	return _u
}

// AddDebtUsdUnits adds value to the "debt_usd_units" field.
func (_u *PaymentExternalOrderUpdate) AddDebtUsdUnits(v int64) *PaymentExternalOrderUpdate {
	_u.mutation.AddDebtUsdUnits(v)
	return _u
}

// SetPaymentState sets the "payment_state" field.
func (_u *PaymentExternalOrderUpdate) SetPaymentState(v string) *PaymentExternalOrderUpdate {
	_u.mutation.SetPaymentState(v)
	return _u
}

// SetNillablePaymentState sets the "payment_state" field if the given value is not nil.
func (_u *PaymentExternalOrderUpdate) SetNillablePaymentState(v *string) *PaymentExternalOrderUpdate {
	if v != nil {
		_u.SetPaymentState(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *PaymentExternalOrderUpdate) SetStatus(v string) *PaymentExternalOrderUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PaymentExternalOrderUpdate) SetNillableStatus(v *string) *PaymentExternalOrderUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAnomalyCode sets the "anomaly_code" field.
func (_u *PaymentExternalOrderUpdate) SetAnomalyCode(v string) *PaymentExternalOrderUpdate {
	_u.mutation.SetAnomalyCode(v)
	return _u
}

// SetNillableAnomalyCode sets the "anomaly_code" field if the given value is not nil.
func (_u *PaymentExternalOrderUpdate) SetNillableAnomalyCode(v *string) *PaymentExternalOrderUpdate {
	if v != nil {
		_u.SetAnomalyCode(*v)
	}
	return _u
}

// SetPaidAt sets the "paid_at" field.
func (_u *PaymentExternalOrderUpdate) SetPaidAt(v time.Time) *PaymentExternalOrderUpdate {
	_u.mutation.SetPaidAt(v)
	return _u
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_u *PaymentExternalOrderUpdate) SetNillablePaidAt(v *time.Time) *PaymentExternalOrderUpdate {
	if v != nil {
		_u.SetPaidAt(*v)
	}
	return _u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (_u *PaymentExternalOrderUpdate) ClearPaidAt() *PaymentExternalOrderUpdate {
	_u.mutation.ClearPaidAt()
	return _u
}

// SetProviderModifiedAt sets the "provider_modified_at" field.
func (_u *PaymentExternalOrderUpdate) SetProviderModifiedAt(v time.Time) *PaymentExternalOrderUpdate {
	_u.mutation.SetProviderModifiedAt(v)
	return _u
}

// SetNillableProviderModifiedAt sets the "provider_modified_at" field if the given value is not nil.
func (_u *PaymentExternalOrderUpdate) SetNillableProviderModifiedAt(v *time.Time) *PaymentExternalOrderUpdate {
	if v != nil {
		_u.SetProviderModifiedAt(*v)
	}
	return _u
}

// ClearProviderModifiedAt clears the value of the "provider_modified_at" field.
func (_u *PaymentExternalOrderUpdate) ClearProviderModifiedAt() *PaymentExternalOrderUpdate {
	_u.mutation.ClearProviderModifiedAt()
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *PaymentExternalOrderUpdate) SetLastSeenAt(v time.Time) *PaymentExternalOrderUpdate {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_u *PaymentExternalOrderUpdate) SetNillableLastSeenAt(v *time.Time) *PaymentExternalOrderUpdate {
	if v != nil {
		_u.SetLastSeenAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PaymentExternalOrderUpdate) SetUpdatedAt(v time.Time) *PaymentExternalOrderUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PaymentExternalOrderMutation object of the builder.
func (_u *PaymentExternalOrderUpdate) Mutation() *PaymentExternalOrderMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PaymentExternalOrderUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentExternalOrderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PaymentExternalOrderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentExternalOrderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaymentExternalOrderUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := paymentexternalorder.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentExternalOrderUpdate) check() error {
	if v, ok := _u.mutation.ProviderKey(); ok {
		if err := paymentexternalorder.ProviderKeyValidator(v); err != nil {
			return &ValidationError{Name: "provider_key", err: fmt.Errorf(`ent: validator failed for field "PaymentExternalOrder.provider_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WebsiteID(); ok {
		if err := paymentexternalorder.WebsiteIDValidator(v); err != nil {
			return &ValidationError{Name: "website_id", err: fmt.Errorf(`ent: validator failed for field "PaymentExternalOrder.website_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExternalOrderID(); ok {
		if err := paymentexternalorder.ExternalOrderIDValidator(v); err != nil {
			return &ValidationError{Name: "external_order_id", err: fmt.Errorf(`ent: validator failed for field "PaymentExternalOrder.external_order_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OrderNumber(); ok {
		if err := paymentexternalorder.OrderNumberValidator(v); err != nil {
			return &ValidationError{Name: "order_number", err: fmt.Errorf(`ent: validator failed for field "PaymentExternalOrder.order_number": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BindingMethod(); ok {
		if err := paymentexternalorder.BindingMethodValidator(v); err != nil {
			return &ValidationError{Name: "binding_method", err: fmt.Errorf(`ent: validator failed for field "PaymentExternalOrder.binding_method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.QuoteHash(); ok {
		if err := paymentexternalorder.QuoteHashValidator(v); err != nil {
			return &ValidationError{Name: "quote_hash", err: fmt.Errorf(`ent: validator failed for field "PaymentExternalOrder.quote_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CheckoutReference(); ok {
		if err := paymentexternalorder.CheckoutReferenceValidator(v); err != nil {
			return &ValidationError{Name: "checkout_reference", err: fmt.Errorf(`ent: validator failed for field "PaymentExternalOrder.checkout_reference": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := paymentexternalorder.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "PaymentExternalOrder.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PaymentState(); ok {
		if err := paymentexternalorder.PaymentStateValidator(v); err != nil {
			return &ValidationError{Name: "payment_state", err: fmt.Errorf(`ent: validator failed for field "PaymentExternalOrder.payment_state": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := paymentexternalorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PaymentExternalOrder.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AnomalyCode(); ok {
		if err := paymentexternalorder.AnomalyCodeValidator(v); err != nil {
			return &ValidationError{Name: "anomaly_code", err: fmt.Errorf(`ent: validator failed for field "PaymentExternalOrder.anomaly_code": %w`, err)}
		}
	}
	return nil
}

func (_u *PaymentExternalOrderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paymentexternalorder.Table, paymentexternalorder.Columns, sqlgraph.NewFieldSpec(paymentexternalorder.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProviderKey(); ok {
		_spec.SetField(paymentexternalorder.FieldProviderKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.WebsiteID(); ok {
		_spec.SetField(paymentexternalorder.FieldWebsiteID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExternalOrderID(); ok {
		_spec.SetField(paymentexternalorder.FieldExternalOrderID, field.TypeString, value)
	}
	if value, ok := _u.mutation.OrderNumber(); ok {
		_spec.SetField(paymentexternalorder.FieldOrderNumber, field.TypeString, value)
	}
	if value, ok := _u.mutation.BindingMethod(); ok {
		_spec.SetField(paymentexternalorder.FieldBindingMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.QuoteHash(); ok {
		_spec.SetField(paymentexternalorder.FieldQuoteHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.LocalOrderID(); ok {
		_spec.SetField(paymentexternalorder.FieldLocalOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLocalOrderID(); ok {
		_spec.AddField(paymentexternalorder.FieldLocalOrderID, field.TypeInt64, value)
	}
	if _u.mutation.LocalOrderIDCleared() {
		_spec.ClearField(paymentexternalorder.FieldLocalOrderID, field.TypeInt64)
	}
	if value, ok := _u.mutation.CheckoutReference(); ok {
		_spec.SetField(paymentexternalorder.FieldCheckoutReference, field.TypeString, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(paymentexternalorder.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.TotalMinor(); ok {
		_spec.SetField(paymentexternalorder.FieldTotalMinor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTotalMinor(); ok {
		_spec.AddField(paymentexternalorder.FieldTotalMinor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RefundedMinor(); ok {
		_spec.SetField(paymentexternalorder.FieldRefundedMinor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRefundedMinor(); ok {
		_spec.AddField(paymentexternalorder.FieldRefundedMinor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CreditedUsdUnits(); ok {
		_spec.SetField(paymentexternalorder.FieldCreditedUsdUnits, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreditedUsdUnits(); ok {
		_spec.AddField(paymentexternalorder.FieldCreditedUsdUnits, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RefundTargetUsdUnits(); ok {
		_spec.SetField(paymentexternalorder.FieldRefundTargetUsdUnits, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRefundTargetUsdUnits(); ok {
		_spec.AddField(paymentexternalorder.FieldRefundTargetUsdUnits, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RecoveredUsdUnits(); ok {
		_spec.SetField(paymentexternalorder.FieldRecoveredUsdUnits, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRecoveredUsdUnits(); ok {
		_spec.AddField(paymentexternalorder.FieldRecoveredUsdUnits, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DebtUsdUnits(); ok {
		_spec.SetField(paymentexternalorder.FieldDebtUsdUnits, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDebtUsdUnits(); ok {
		_spec.AddField(paymentexternalorder.FieldDebtUsdUnits, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PaymentState(); ok {
		_spec.SetField(paymentexternalorder.FieldPaymentState, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(paymentexternalorder.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.AnomalyCode(); ok {
		_spec.SetField(paymentexternalorder.FieldAnomalyCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.PaidAt(); ok {
		_spec.SetField(paymentexternalorder.FieldPaidAt, field.TypeTime, value)
	}
	if _u.mutation.PaidAtCleared() {
		_spec.ClearField(paymentexternalorder.FieldPaidAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ProviderModifiedAt(); ok {
		_spec.SetField(paymentexternalorder.FieldProviderModifiedAt, field.TypeTime, value)
	}
	if _u.mutation.ProviderModifiedAtCleared() {
		_spec.ClearField(paymentexternalorder.FieldProviderModifiedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(paymentexternalorder.FieldLastSeenAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentexternalorder.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentexternalorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PaymentExternalOrderUpdateOne is the builder for updating a single PaymentExternalOrder entity.
type PaymentExternalOrderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PaymentExternalOrderMutation
}

// SetProviderKey sets the "provider_key" field.
func (_u *PaymentExternalOrderUpdateOne) SetProviderKey(v string) *PaymentExternalOrderUpdateOne {
	_u.mutation.SetProviderKey(v)
	return _u
}

// SetNillableProviderKey sets the "provider_key" field if the given value is not nil.
func (_u *PaymentExternalOrderUpdateOne) SetNillableProviderKey(v *string) *PaymentExternalOrderUpdateOne {
	if v != nil {
		_u.SetProviderKey(*v)
	}
	return _u
}

// SetWebsiteID sets the "website_id" field.
func (_u *PaymentExternalOrderUpdateOne) SetWebsiteID(v string) *PaymentExternalOrderUpdateOne {
	_u.mutation.SetWebsiteID(v)
	return _u
}

// SetNillableWebsiteID sets the "website_id" field if the given value is not nil.
func (_u *PaymentExternalOrderUpdateOne) SetNillableWebsiteID(v *string) *PaymentExternalOrderUpdateOne {
	if v != nil {
		_u.SetWebsiteID(*v)
	}
	return _u
}

// SetExternalOrderID sets the "external_order_id" field.
func (_u *PaymentExternalOrderUpdateOne) SetExternalOrderID(v string) *PaymentExternalOrderUpdateOne {
	_u.mutation.SetExternalOrderID(v)
	return _u
}

// SetNillableExternalOrderID sets the "external_order_id" field if the given value is not nil.
func (_u *PaymentExternalOrderUpdateOne) SetNillableExternalOrderID(v *string) *PaymentExternalOrderUpdateOne {
	if v != nil {
		_u.SetExternalOrderID(*v)
	}
	return _u
}

// SetOrderNumber sets the "order_number" field.
func (_u *PaymentExternalOrderUpdateOne) SetOrderNumber(v string) *PaymentExternalOrderUpdateOne {
	_u.mutation.SetOrderNumber(v)
	return _u
}

// SetNillableOrderNumber sets the "order_number" field if the given value is not nil.
func (_u *PaymentExternalOrderUpdateOne) SetNillableOrderNumber(v *string) *PaymentExternalOrderUpdateOne {
	if v != nil {
		_u.SetOrderNumber(*v)
	}
	return _u
}

// SetBindingMethod sets the "binding_method" field.
func (_u *PaymentExternalOrderUpdateOne) SetBindingMethod(v string) *PaymentExternalOrderUpdateOne {
	_u.mutation.SetBindingMethod(v)
	return _u
}

// SetNillableBindingMethod sets the "binding_method" field if the given value is not nil.
func (_u *PaymentExternalOrderUpdateOne) SetNillableBindingMethod(v *string) *PaymentExternalOrderUpdateOne {
	if v != nil {
		_u.SetBindingMethod(*v)
	}
	return _u
}

// SetQuoteHash sets the "quote_hash" field.
func (_u *PaymentExternalOrderUpdateOne) SetQuoteHash(v string) *PaymentExternalOrderUpdateOne {
	_u.mutation.SetQuoteHash(v)
	return _u
}

// SetNillableQuoteHash sets the "quote_hash" field if the given value is not nil.
func (_u *PaymentExternalOrderUpdateOne) SetNillableQuoteHash(v *string) *PaymentExternalOrderUpdateOne {
	if v != nil {
		_u.SetQuoteHash(*v)
	}
	return _u
}

// SetLocalOrderID sets the "local_order_id" field.
func (_u *PaymentExternalOrderUpdateOne) SetLocalOrderID(v int64) *PaymentExternalOrderUpdateOne {
	_u.mutation.ResetLocalOrderID()
	_u.mutation.SetLocalOrderID(v)
	return _u
}

// SetNillableLocalOrderID sets the "local_order_id" field if the given value is not nil.
func (_u *PaymentExternalOrderUpdateOne) SetNillableLocalOrderID(v *int64) *PaymentExternalOrderUpdateOne {
	if v != nil {
		_u.SetLocalOrderID(*v)
	}
	return _u
}

// AddLocalOrderID adds value to the "local_order_id" field.
func (_u *PaymentExternalOrderUpdateOne) AddLocalOrderID(v int64) *PaymentExternalOrderUpdateOne {
	_u.mutation.AddLocalOrderID(v)
	return _u
}

// ClearLocalOrderID clears the value of the "local_order_id" field.
func (_u *PaymentExternalOrderUpdateOne) ClearLocalOrderID() *PaymentExternalOrderUpdateOne {
	_u.mutation.ClearLocalOrderID()
	return _u
}

// SetCheckoutReference sets the "checkout_reference" field.
func (_u *PaymentExternalOrderUpdateOne) SetCheckoutReference(v string) *PaymentExternalOrderUpdateOne {
	_u.mutation.SetCheckoutReference(v)
	return _u
}

// SetNillableCheckoutReference sets the "checkout_reference" field if the given value is not nil.
func (_u *PaymentExternalOrderUpdateOne) SetNillableCheckoutReference(v *string) *PaymentExternalOrderUpdateOne {
	if v != nil {
		_u.SetCheckoutReference(*v)
	}
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *PaymentExternalOrderUpdateOne) SetCurrency(v string) *PaymentExternalOrderUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *PaymentExternalOrderUpdateOne) SetNillableCurrency(v *string) *PaymentExternalOrderUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetTotalMinor sets the "total_minor" field.
func (_u *PaymentExternalOrderUpdateOne) SetTotalMinor(v int64) *PaymentExternalOrderUpdateOne {
	_u.mutation.ResetTotalMinor()
	_u.mutation.SetTotalMinor(v)
	return _u
}

// SetNillableTotalMinor sets the "total_minor" field if the given value is not nil.
func (_u *PaymentExternalOrderUpdateOne) SetNillableTotalMinor(v *int64) *PaymentExternalOrderUpdateOne {
	if v != nil {
		_u.SetTotalMinor(*v)
	}
	return _u
}

// AddTotalMinor adds value to the "total_minor" field.
func (_u *PaymentExternalOrderUpdateOne) AddTotalMinor(v int64) *PaymentExternalOrderUpdateOne {
	_u.mutation.AddTotalMinor(v)
	return _u
}

// SetRefundedMinor sets the "refunded_minor" field.
func (_u *PaymentExternalOrderUpdateOne) SetRefundedMinor(v int64) *PaymentExternalOrderUpdateOne {
	_u.mutation.ResetRefundedMinor()
	_u.mutation.SetRefundedMinor(v)
	return _u
}

// SetNillableRefundedMinor sets the "refunded_minor" field if the given value is not nil.
func (_u *PaymentExternalOrderUpdateOne) SetNillableRefundedMinor(v *int64) *PaymentExternalOrderUpdateOne {
	if v != nil {
		_u.SetRefundedMinor(*v)
	}
	return _u
}

// AddRefundedMinor adds value to the "refunded_minor" field.
func (_u *PaymentExternalOrderUpdateOne) AddRefundedMinor(v int64) *PaymentExternalOrderUpdateOne {
	_u.mutation.AddRefundedMinor(v)
	return _u
}

// SetCreditedUsdUnits sets the "credited_usd_units" field.
func (_u *PaymentExternalOrderUpdateOne) SetCreditedUsdUnits(v int64) *PaymentExternalOrderUpdateOne {
	_u.mutation.ResetCreditedUsdUnits()
	_u.mutation.SetCreditedUsdUnits(v)
	return _u
}

// SetNillableCreditedUsdUnits sets the "credited_usd_units" field if the given value is not nil.
func (_u *PaymentExternalOrderUpdateOne) SetNillableCreditedUsdUnits(v *int64) *PaymentExternalOrderUpdateOne {
	if v != nil {
		_u.SetCreditedUsdUnits(*v)
	}
	return _u
}

// AddCreditedUsdUnits adds value to the "credited_usd_units" field.
func (_u *PaymentExternalOrderUpdateOne) AddCreditedUsdUnits(v int64) *PaymentExternalOrderUpdateOne {
	_u.mutation.AddCreditedUsdUnits(v)
	return _u
}

// SetRefundTargetUsdUnits sets the "refund_target_usd_units" field.
func (_u *PaymentExternalOrderUpdateOne) SetRefundTargetUsdUnits(v int64) *PaymentExternalOrderUpdateOne {
	_u.mutation.ResetRefundTargetUsdUnits()
	_u.mutation.SetRefundTargetUsdUnits(v)
	return _u
}

// SetNillableRefundTargetUsdUnits sets the "refund_target_usd_units" field if the given value is not nil.
func (_u *PaymentExternalOrderUpdateOne) SetNillableRefundTargetUsdUnits(v *int64) *PaymentExternalOrderUpdateOne {
	if v != nil {
		_u.SetRefundTargetUsdUnits(*v)
	}
	return _u
}

// AddRefundTargetUsdUnits adds value to the "refund_target_usd_units" field.
func (_u *PaymentExternalOrderUpdateOne) AddRefundTargetUsdUnits(v int64) *PaymentExternalOrderUpdateOne {
	_u.mutation.AddRefundTargetUsdUnits(v)
	return _u
}

// SetRecoveredUsdUnits sets the "recovered_usd_units" field.
func (_u *PaymentExternalOrderUpdateOne) SetRecoveredUsdUnits(v int64) *PaymentExternalOrderUpdateOne {
	_u.mutation.ResetRecoveredUsdUnits()
	_u.mutation.SetRecoveredUsdUnits(v)
	return _u
}

// SetNillableRecoveredUsdUnits sets the "recovered_usd_units" field if the given value is not nil.
func (_u *PaymentExternalOrderUpdateOne) SetNillableRecoveredUsdUnits(v *int64) *PaymentExternalOrderUpdateOne {
	if v != nil {
		_u.SetRecoveredUsdUnits(*v)
	}
	return _u
}

// AddRecoveredUsdUnits adds value to the "recovered_usd_units" field.
func (_u *PaymentExternalOrderUpdateOne) AddRecoveredUsdUnits(v int64) *PaymentExternalOrderUpdateOne {
	_u.mutation.AddRecoveredUsdUnits(v)
	return _u
}

// SetDebtUsdUnits sets the "debt_usd_units" field.
func (_u *PaymentExternalOrderUpdateOne) SetDebtUsdUnits(v int64) *PaymentExternalOrderUpdateOne {
	_u.mutation.ResetDebtUsdUnits()
	_u.mutation.SetDebtUsdUnits(v)
	return _u
}

// SetNillableDebtUsdUnits sets the "debt_usd_units" field if the given value is not nil.
func (_u *PaymentExternalOrderUpdateOne) SetNillableDebtUsdUnits(v *int64) *PaymentExternalOrderUpdateOne {
	if v != nil {
		_u.SetDebtUsdUnits(*v)
	}
	return _u
}

// AddDebtUsdUnits adds value to the "debt_usd_units" field.
func (_u *PaymentExternalOrderUpdateOne) AddDebtUsdUnits(v int64) *PaymentExternalOrderUpdateOne {
	_u.mutation.AddDebtUsdUnits(v)
	return _u
}

// SetPaymentState sets the "payment_state" field.
func (_u *PaymentExternalOrderUpdateOne) SetPaymentState(v string) *PaymentExternalOrderUpdateOne {
	_u.mutation.SetPaymentState(v)
	return _u
}

// SetNillablePaymentState sets the "payment_state" field if the given value is not nil.
func (_u *PaymentExternalOrderUpdateOne) SetNillablePaymentState(v *string) *PaymentExternalOrderUpdateOne {
	if v != nil {
		_u.SetPaymentState(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *PaymentExternalOrderUpdateOne) SetStatus(v string) *PaymentExternalOrderUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PaymentExternalOrderUpdateOne) SetNillableStatus(v *string) *PaymentExternalOrderUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAnomalyCode sets the "anomaly_code" field.
func (_u *PaymentExternalOrderUpdateOne) SetAnomalyCode(v string) *PaymentExternalOrderUpdateOne {
	_u.mutation.SetAnomalyCode(v)
	return _u
}

// SetNillableAnomalyCode sets the "anomaly_code" field if the given value is not nil.
func (_u *PaymentExternalOrderUpdateOne) SetNillableAnomalyCode(v *string) *PaymentExternalOrderUpdateOne {
	if v != nil {
		_u.SetAnomalyCode(*v)
	}
	return _u
}

// SetPaidAt sets the "paid_at" field.
func (_u *PaymentExternalOrderUpdateOne) SetPaidAt(v time.Time) *PaymentExternalOrderUpdateOne {
	_u.mutation.SetPaidAt(v)
	return _u
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_u *PaymentExternalOrderUpdateOne) SetNillablePaidAt(v *time.Time) *PaymentExternalOrderUpdateOne {
	if v != nil {
		_u.SetPaidAt(*v)
	}
	return _u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (_u *PaymentExternalOrderUpdateOne) ClearPaidAt() *PaymentExternalOrderUpdateOne {
	_u.mutation.ClearPaidAt()
	return _u
}

// SetProviderModifiedAt sets the "provider_modified_at" field.
func (_u *PaymentExternalOrderUpdateOne) SetProviderModifiedAt(v time.Time) *PaymentExternalOrderUpdateOne {
	_u.mutation.SetProviderModifiedAt(v)
	return _u
}

// SetNillableProviderModifiedAt sets the "provider_modified_at" field if the given value is not nil.
func (_u *PaymentExternalOrderUpdateOne) SetNillableProviderModifiedAt(v *time.Time) *PaymentExternalOrderUpdateOne {
	if v != nil {
		_u.SetProviderModifiedAt(*v)
	}
	return _u
}

// ClearProviderModifiedAt clears the value of the "provider_modified_at" field.
func (_u *PaymentExternalOrderUpdateOne) ClearProviderModifiedAt() *PaymentExternalOrderUpdateOne {
	_u.mutation.ClearProviderModifiedAt()
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *PaymentExternalOrderUpdateOne) SetLastSeenAt(v time.Time) *PaymentExternalOrderUpdateOne {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_u *PaymentExternalOrderUpdateOne) SetNillableLastSeenAt(v *time.Time) *PaymentExternalOrderUpdateOne {
	if v != nil {
		_u.SetLastSeenAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PaymentExternalOrderUpdateOne) SetUpdatedAt(v time.Time) *PaymentExternalOrderUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PaymentExternalOrderMutation object of the builder.
func (_u *PaymentExternalOrderUpdateOne) Mutation() *PaymentExternalOrderMutation {
	return _u.mutation
}

// Where appends a list predicates to the PaymentExternalOrderUpdate builder.
func (_u *PaymentExternalOrderUpdateOne) Where(ps ...predicate.PaymentExternalOrder) *PaymentExternalOrderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PaymentExternalOrderUpdateOne) Select(field string, fields ...string) *PaymentExternalOrderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PaymentExternalOrder entity.
func (_u *PaymentExternalOrderUpdateOne) Save(ctx context.Context) (*PaymentExternalOrder, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentExternalOrderUpdateOne) SaveX(ctx context.Context) *PaymentExternalOrder {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PaymentExternalOrderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentExternalOrderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaymentExternalOrderUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := paymentexternalorder.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentExternalOrderUpdateOne) check() error {
	if v, ok := _u.mutation.ProviderKey(); ok {
		if err := paymentexternalorder.ProviderKeyValidator(v); err != nil {
			return &ValidationError{Name: "provider_key", err: fmt.Errorf(`ent: validator failed for field "PaymentExternalOrder.provider_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WebsiteID(); ok {
		if err := paymentexternalorder.WebsiteIDValidator(v); err != nil {
			return &ValidationError{Name: "website_id", err: fmt.Errorf(`ent: validator failed for field "PaymentExternalOrder.website_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExternalOrderID(); ok {
		if err := paymentexternalorder.ExternalOrderIDValidator(v); err != nil {
			return &ValidationError{Name: "external_order_id", err: fmt.Errorf(`ent: validator failed for field "PaymentExternalOrder.external_order_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OrderNumber(); ok {
		if err := paymentexternalorder.OrderNumberValidator(v); err != nil {
			return &ValidationError{Name: "order_number", err: fmt.Errorf(`ent: validator failed for field "PaymentExternalOrder.order_number": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BindingMethod(); ok {
		if err := paymentexternalorder.BindingMethodValidator(v); err != nil {
			return &ValidationError{Name: "binding_method", err: fmt.Errorf(`ent: validator failed for field "PaymentExternalOrder.binding_method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.QuoteHash(); ok {
		if err := paymentexternalorder.QuoteHashValidator(v); err != nil {
			return &ValidationError{Name: "quote_hash", err: fmt.Errorf(`ent: validator failed for field "PaymentExternalOrder.quote_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CheckoutReference(); ok {
		if err := paymentexternalorder.CheckoutReferenceValidator(v); err != nil {
			return &ValidationError{Name: "checkout_reference", err: fmt.Errorf(`ent: validator failed for field "PaymentExternalOrder.checkout_reference": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := paymentexternalorder.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "PaymentExternalOrder.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PaymentState(); ok {
		if err := paymentexternalorder.PaymentStateValidator(v); err != nil {
			return &ValidationError{Name: "payment_state", err: fmt.Errorf(`ent: validator failed for field "PaymentExternalOrder.payment_state": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := paymentexternalorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PaymentExternalOrder.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AnomalyCode(); ok {
		if err := paymentexternalorder.AnomalyCodeValidator(v); err != nil {
			return &ValidationError{Name: "anomaly_code", err: fmt.Errorf(`ent: validator failed for field "PaymentExternalOrder.anomaly_code": %w`, err)}
		}
	}
	return nil
}

func (_u *PaymentExternalOrderUpdateOne) sqlSave(ctx context.Context) (_node *PaymentExternalOrder, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paymentexternalorder.Table, paymentexternalorder.Columns, sqlgraph.NewFieldSpec(paymentexternalorder.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PaymentExternalOrder.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, paymentexternalorder.FieldID)
		for _, f := range fields {
			if !paymentexternalorder.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != paymentexternalorder.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProviderKey(); ok {
		_spec.SetField(paymentexternalorder.FieldProviderKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.WebsiteID(); ok {
		_spec.SetField(paymentexternalorder.FieldWebsiteID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExternalOrderID(); ok {
		_spec.SetField(paymentexternalorder.FieldExternalOrderID, field.TypeString, value)
	}
	if value, ok := _u.mutation.OrderNumber(); ok {
		_spec.SetField(paymentexternalorder.FieldOrderNumber, field.TypeString, value)
	}
	if value, ok := _u.mutation.BindingMethod(); ok {
		_spec.SetField(paymentexternalorder.FieldBindingMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.QuoteHash(); ok {
		_spec.SetField(paymentexternalorder.FieldQuoteHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.LocalOrderID(); ok {
		_spec.SetField(paymentexternalorder.FieldLocalOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLocalOrderID(); ok {
		_spec.AddField(paymentexternalorder.FieldLocalOrderID, field.TypeInt64, value)
	}
	if _u.mutation.LocalOrderIDCleared() {
		_spec.ClearField(paymentexternalorder.FieldLocalOrderID, field.TypeInt64)
	}
	if value, ok := _u.mutation.CheckoutReference(); ok {
		_spec.SetField(paymentexternalorder.FieldCheckoutReference, field.TypeString, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(paymentexternalorder.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.TotalMinor(); ok {
		_spec.SetField(paymentexternalorder.FieldTotalMinor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTotalMinor(); ok {
		_spec.AddField(paymentexternalorder.FieldTotalMinor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RefundedMinor(); ok {
		_spec.SetField(paymentexternalorder.FieldRefundedMinor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRefundedMinor(); ok {
		_spec.AddField(paymentexternalorder.FieldRefundedMinor, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CreditedUsdUnits(); ok {
		_spec.SetField(paymentexternalorder.FieldCreditedUsdUnits, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreditedUsdUnits(); ok {
		_spec.AddField(paymentexternalorder.FieldCreditedUsdUnits, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RefundTargetUsdUnits(); ok {
		_spec.SetField(paymentexternalorder.FieldRefundTargetUsdUnits, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRefundTargetUsdUnits(); ok {
		_spec.AddField(paymentexternalorder.FieldRefundTargetUsdUnits, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RecoveredUsdUnits(); ok {
		_spec.SetField(paymentexternalorder.FieldRecoveredUsdUnits, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRecoveredUsdUnits(); ok {
		_spec.AddField(paymentexternalorder.FieldRecoveredUsdUnits, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DebtUsdUnits(); ok {
		_spec.SetField(paymentexternalorder.FieldDebtUsdUnits, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDebtUsdUnits(); ok {
		_spec.AddField(paymentexternalorder.FieldDebtUsdUnits, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PaymentState(); ok {
		_spec.SetField(paymentexternalorder.FieldPaymentState, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(paymentexternalorder.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.AnomalyCode(); ok {
		_spec.SetField(paymentexternalorder.FieldAnomalyCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.PaidAt(); ok {
		_spec.SetField(paymentexternalorder.FieldPaidAt, field.TypeTime, value)
	}
	if _u.mutation.PaidAtCleared() {
		_spec.ClearField(paymentexternalorder.FieldPaidAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ProviderModifiedAt(); ok {
		_spec.SetField(paymentexternalorder.FieldProviderModifiedAt, field.TypeTime, value)
	}
	if _u.mutation.ProviderModifiedAtCleared() {
		_spec.ClearField(paymentexternalorder.FieldProviderModifiedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(paymentexternalorder.FieldLastSeenAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentexternalorder.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &PaymentExternalOrder{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentexternalorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
