// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/paymentsyncstate"
)

// PaymentSyncState is the model entity for the PaymentSyncState schema.
type PaymentSyncState struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// ProviderKey holds the value of the "provider_key" field.
	ProviderKey string `json:"provider_key,omitempty"`
	// WebsiteID holds the value of the "website_id" field.
	WebsiteID string `json:"website_id,omitempty"`
	// OauthClientID holds the value of the "oauth_client_id" field.
	OauthClientID string `json:"oauth_client_id,omitempty"`
	// EncryptedOauthCredentials holds the value of the "encrypted_oauth_credentials" field.
	EncryptedOauthCredentials string `json:"-"`
	// EncryptedOauthTokens holds the value of the "encrypted_oauth_tokens" field.
	EncryptedOauthTokens string `json:"-"`
	// TokenVersion holds the value of the "token_version" field.
	TokenVersion int64 `json:"token_version,omitempty"`
	// RotationPhase holds the value of the "rotation_phase" field.
	RotationPhase string `json:"rotation_phase,omitempty"`
	// RotationStartedAt holds the value of the "rotation_started_at" field.
	RotationStartedAt *time.Time `json:"rotation_started_at,omitempty"`
	// NextCursor holds the value of the "next_cursor" field.
	NextCursor string `json:"next_cursor,omitempty"`
	// WindowStart holds the value of the "window_start" field.
	WindowStart *time.Time `json:"window_start,omitempty"`
	// WindowEnd holds the value of the "window_end" field.
	WindowEnd *time.Time `json:"window_end,omitempty"`
	// LastSyncedAt holds the value of the "last_synced_at" field.
	LastSyncedAt *time.Time `json:"last_synced_at,omitempty"`
	// RetryAt holds the value of the "retry_at" field.
	RetryAt *time.Time `json:"retry_at,omitempty"`
	// LastErrorCode holds the value of the "last_error_code" field.
	LastErrorCode string `json:"last_error_code,omitempty"`
	// LeaseOwner holds the value of the "lease_owner" field.
	LeaseOwner string `json:"lease_owner,omitempty"`
	// LeaseUntil holds the value of the "lease_until" field.
	LeaseUntil *time.Time `json:"lease_until,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PaymentSyncState) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case paymentsyncstate.FieldID, paymentsyncstate.FieldTokenVersion:
			values[i] = new(sql.NullInt64)
		case paymentsyncstate.FieldProviderKey, paymentsyncstate.FieldWebsiteID, paymentsyncstate.FieldOauthClientID, paymentsyncstate.FieldEncryptedOauthCredentials, paymentsyncstate.FieldEncryptedOauthTokens, paymentsyncstate.FieldRotationPhase, paymentsyncstate.FieldNextCursor, paymentsyncstate.FieldLastErrorCode, paymentsyncstate.FieldLeaseOwner:
			values[i] = new(sql.NullString)
		case paymentsyncstate.FieldRotationStartedAt, paymentsyncstate.FieldWindowStart, paymentsyncstate.FieldWindowEnd, paymentsyncstate.FieldLastSyncedAt, paymentsyncstate.FieldRetryAt, paymentsyncstate.FieldLeaseUntil, paymentsyncstate.FieldCreatedAt, paymentsyncstate.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PaymentSyncState fields.
func (_m *PaymentSyncState) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case paymentsyncstate.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case paymentsyncstate.FieldProviderKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_key", values[i])
			} else if value.Valid {
				_m.ProviderKey = value.String
			}
		case paymentsyncstate.FieldWebsiteID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field website_id", values[i])
			} else if value.Valid {
				_m.WebsiteID = value.String
			}
		case paymentsyncstate.FieldOauthClientID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field oauth_client_id", values[i])
			} else if value.Valid {
				_m.OauthClientID = value.String
			}
		case paymentsyncstate.FieldEncryptedOauthCredentials:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field encrypted_oauth_credentials", values[i])
			} else if value.Valid {
				_m.EncryptedOauthCredentials = value.String
			}
		case paymentsyncstate.FieldEncryptedOauthTokens:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field encrypted_oauth_tokens", values[i])
			} else if value.Valid {
				_m.EncryptedOauthTokens = value.String
			}
		case paymentsyncstate.FieldTokenVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field token_version", values[i])
			} else if value.Valid {
				_m.TokenVersion = value.Int64
			}
		case paymentsyncstate.FieldRotationPhase:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field rotation_phase", values[i])
			} else if value.Valid {
				_m.RotationPhase = value.String
			}
		case paymentsyncstate.FieldRotationStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field rotation_started_at", values[i])
			} else if value.Valid {
				_m.RotationStartedAt = new(time.Time)
				*_m.RotationStartedAt = value.Time
			}
		case paymentsyncstate.FieldNextCursor:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field next_cursor", values[i])
			} else if value.Valid {
				_m.NextCursor = value.String
			}
		case paymentsyncstate.FieldWindowStart:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field window_start", values[i])
			} else if value.Valid {
				_m.WindowStart = new(time.Time)
				*_m.WindowStart = value.Time
			}
		case paymentsyncstate.FieldWindowEnd:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field window_end", values[i])
			} else if value.Valid {
				_m.WindowEnd = new(time.Time)
				*_m.WindowEnd = value.Time
			}
		case paymentsyncstate.FieldLastSyncedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_synced_at", values[i])
			} else if value.Valid {
				_m.LastSyncedAt = new(time.Time)
				*_m.LastSyncedAt = value.Time
			}
		case paymentsyncstate.FieldRetryAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field retry_at", values[i])
			} else if value.Valid {
				_m.RetryAt = new(time.Time)
				*_m.RetryAt = value.Time
			}
		case paymentsyncstate.FieldLastErrorCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error_code", values[i])
			} else if value.Valid {
				_m.LastErrorCode = value.String
			}
		case paymentsyncstate.FieldLeaseOwner:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field lease_owner", values[i])
			} else if value.Valid {
				_m.LeaseOwner = value.String
			}
		case paymentsyncstate.FieldLeaseUntil:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field lease_until", values[i])
			} else if value.Valid {
				_m.LeaseUntil = new(time.Time)
				*_m.LeaseUntil = value.Time
			}
		case paymentsyncstate.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case paymentsyncstate.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PaymentSyncState.
// This includes values selected through modifiers, order, etc.
func (_m *PaymentSyncState) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this PaymentSyncState.
// Note that you need to call PaymentSyncState.Unwrap() before calling this method if this PaymentSyncState
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PaymentSyncState) Update() *PaymentSyncStateUpdateOne {
	return NewPaymentSyncStateClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PaymentSyncState entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PaymentSyncState) Unwrap() *PaymentSyncState {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PaymentSyncState is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PaymentSyncState) String() string {
	var builder strings.Builder
	builder.WriteString("PaymentSyncState(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("provider_key=")
	builder.WriteString(_m.ProviderKey)
	builder.WriteString(", ")
	builder.WriteString("website_id=")
	builder.WriteString(_m.WebsiteID)
	builder.WriteString(", ")
	builder.WriteString("oauth_client_id=")
	builder.WriteString(_m.OauthClientID)
	builder.WriteString(", ")
	builder.WriteString("encrypted_oauth_credentials=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("encrypted_oauth_tokens=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("token_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.TokenVersion))
	builder.WriteString(", ")
	builder.WriteString("rotation_phase=")
	builder.WriteString(_m.RotationPhase)
	builder.WriteString(", ")
	if v := _m.RotationStartedAt; v != nil {
		builder.WriteString("rotation_started_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("next_cursor=")
	builder.WriteString(_m.NextCursor)
	builder.WriteString(", ")
	if v := _m.WindowStart; v != nil {
		builder.WriteString("window_start=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.WindowEnd; v != nil {
		builder.WriteString("window_end=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastSyncedAt; v != nil {
		builder.WriteString("last_synced_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.RetryAt; v != nil {
		builder.WriteString("retry_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("last_error_code=")
	builder.WriteString(_m.LastErrorCode)
	builder.WriteString(", ")
	builder.WriteString("lease_owner=")
	builder.WriteString(_m.LeaseOwner)
	builder.WriteString(", ")
	if v := _m.LeaseUntil; v != nil {
		builder.WriteString("lease_until=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PaymentSyncStates is a parsable slice of PaymentSyncState.
type PaymentSyncStates []*PaymentSyncState
