// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/paymentexternalrefundjournal"
)

// PaymentExternalRefundJournalCreate is the builder for creating a PaymentExternalRefundJournal entity.
type PaymentExternalRefundJournalCreate struct {
	config
	mutation *PaymentExternalRefundJournalMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetExternalOrderLedgerID sets the "external_order_ledger_id" field.
func (_c *PaymentExternalRefundJournalCreate) SetExternalOrderLedgerID(v int64) *PaymentExternalRefundJournalCreate {
	_c.mutation.SetExternalOrderLedgerID(v)
	return _c
}

// SetCumulativeRefundMinor sets the "cumulative_refund_minor" field.
func (_c *PaymentExternalRefundJournalCreate) SetCumulativeRefundMinor(v int64) *PaymentExternalRefundJournalCreate {
	_c.mutation.SetCumulativeRefundMinor(v)
	return _c
}

// SetDeltaRefundMinor sets the "delta_refund_minor" field.
func (_c *PaymentExternalRefundJournalCreate) SetDeltaRefundMinor(v int64) *PaymentExternalRefundJournalCreate {
	_c.mutation.SetDeltaRefundMinor(v)
	return _c
}

// SetTargetUsdUnits sets the "target_usd_units" field.
func (_c *PaymentExternalRefundJournalCreate) SetTargetUsdUnits(v int64) *PaymentExternalRefundJournalCreate {
	_c.mutation.SetTargetUsdUnits(v)
	return _c
}

// SetDeltaTargetUsdUnits sets the "delta_target_usd_units" field.
func (_c *PaymentExternalRefundJournalCreate) SetDeltaTargetUsdUnits(v int64) *PaymentExternalRefundJournalCreate {
	_c.mutation.SetDeltaTargetUsdUnits(v)
	return _c
}

// SetRecoveredUsdUnits sets the "recovered_usd_units" field.
func (_c *PaymentExternalRefundJournalCreate) SetRecoveredUsdUnits(v int64) *PaymentExternalRefundJournalCreate {
	_c.mutation.SetRecoveredUsdUnits(v)
	return _c
}

// SetNillableRecoveredUsdUnits sets the "recovered_usd_units" field if the given value is not nil.
func (_c *PaymentExternalRefundJournalCreate) SetNillableRecoveredUsdUnits(v *int64) *PaymentExternalRefundJournalCreate {
	if v != nil {
		_c.SetRecoveredUsdUnits(*v)
	}
	return _c
}

// SetDebtUsdUnits sets the "debt_usd_units" field.
func (_c *PaymentExternalRefundJournalCreate) SetDebtUsdUnits(v int64) *PaymentExternalRefundJournalCreate {
	_c.mutation.SetDebtUsdUnits(v)
	return _c
}

// SetNillableDebtUsdUnits sets the "debt_usd_units" field if the given value is not nil.
func (_c *PaymentExternalRefundJournalCreate) SetNillableDebtUsdUnits(v *int64) *PaymentExternalRefundJournalCreate {
	if v != nil {
		_c.SetDebtUsdUnits(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *PaymentExternalRefundJournalCreate) SetStatus(v string) *PaymentExternalRefundJournalCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *PaymentExternalRefundJournalCreate) SetNillableStatus(v *string) *PaymentExternalRefundJournalCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PaymentExternalRefundJournalCreate) SetCreatedAt(v time.Time) *PaymentExternalRefundJournalCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PaymentExternalRefundJournalCreate) SetNillableCreatedAt(v *time.Time) *PaymentExternalRefundJournalCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PaymentExternalRefundJournalCreate) SetUpdatedAt(v time.Time) *PaymentExternalRefundJournalCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PaymentExternalRefundJournalCreate) SetNillableUpdatedAt(v *time.Time) *PaymentExternalRefundJournalCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the PaymentExternalRefundJournalMutation object of the builder.
func (_c *PaymentExternalRefundJournalCreate) Mutation() *PaymentExternalRefundJournalMutation {
	return _c.mutation
}

// Save creates the PaymentExternalRefundJournal in the database.
func (_c *PaymentExternalRefundJournalCreate) Save(ctx context.Context) (*PaymentExternalRefundJournal, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PaymentExternalRefundJournalCreate) SaveX(ctx context.Context) *PaymentExternalRefundJournal {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PaymentExternalRefundJournalCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PaymentExternalRefundJournalCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PaymentExternalRefundJournalCreate) defaults() {
	if _, ok := _c.mutation.RecoveredUsdUnits(); !ok {
		v := paymentexternalrefundjournal.DefaultRecoveredUsdUnits
		_c.mutation.SetRecoveredUsdUnits(v)
	}
	if _, ok := _c.mutation.DebtUsdUnits(); !ok {
		v := paymentexternalrefundjournal.DefaultDebtUsdUnits
		_c.mutation.SetDebtUsdUnits(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := paymentexternalrefundjournal.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := paymentexternalrefundjournal.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := paymentexternalrefundjournal.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PaymentExternalRefundJournalCreate) check() error {
	if _, ok := _c.mutation.ExternalOrderLedgerID(); !ok {
		return &ValidationError{Name: "external_order_ledger_id", err: errors.New(`ent: missing required field "PaymentExternalRefundJournal.external_order_ledger_id"`)}
	}
	if _, ok := _c.mutation.CumulativeRefundMinor(); !ok {
		return &ValidationError{Name: "cumulative_refund_minor", err: errors.New(`ent: missing required field "PaymentExternalRefundJournal.cumulative_refund_minor"`)}
	}
	if _, ok := _c.mutation.DeltaRefundMinor(); !ok {
		return &ValidationError{Name: "delta_refund_minor", err: errors.New(`ent: missing required field "PaymentExternalRefundJournal.delta_refund_minor"`)}
	}
	if _, ok := _c.mutation.TargetUsdUnits(); !ok {
		return &ValidationError{Name: "target_usd_units", err: errors.New(`ent: missing required field "PaymentExternalRefundJournal.target_usd_units"`)}
	}
	if _, ok := _c.mutation.DeltaTargetUsdUnits(); !ok {
		return &ValidationError{Name: "delta_target_usd_units", err: errors.New(`ent: missing required field "PaymentExternalRefundJournal.delta_target_usd_units"`)}
	}
	if _, ok := _c.mutation.RecoveredUsdUnits(); !ok {
		return &ValidationError{Name: "recovered_usd_units", err: errors.New(`ent: missing required field "PaymentExternalRefundJournal.recovered_usd_units"`)}
	}
	if _, ok := _c.mutation.DebtUsdUnits(); !ok {
		return &ValidationError{Name: "debt_usd_units", err: errors.New(`ent: missing required field "PaymentExternalRefundJournal.debt_usd_units"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "PaymentExternalRefundJournal.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := paymentexternalrefundjournal.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PaymentExternalRefundJournal.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PaymentExternalRefundJournal.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PaymentExternalRefundJournal.updated_at"`)}
	}
	return nil
}

func (_c *PaymentExternalRefundJournalCreate) sqlSave(ctx context.Context) (*PaymentExternalRefundJournal, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PaymentExternalRefundJournalCreate) createSpec() (*PaymentExternalRefundJournal, *sqlgraph.CreateSpec) {
	var (
		_node = &PaymentExternalRefundJournal{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(paymentexternalrefundjournal.Table, sqlgraph.NewFieldSpec(paymentexternalrefundjournal.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.ExternalOrderLedgerID(); ok {
		_spec.SetField(paymentexternalrefundjournal.FieldExternalOrderLedgerID, field.TypeInt64, value)
		_node.ExternalOrderLedgerID = value
	}
	if value, ok := _c.mutation.CumulativeRefundMinor(); ok {
		_spec.SetField(paymentexternalrefundjournal.FieldCumulativeRefundMinor, field.TypeInt64, value)
		_node.CumulativeRefundMinor = value
	}
	if value, ok := _c.mutation.DeltaRefundMinor(); ok {
		_spec.SetField(paymentexternalrefundjournal.FieldDeltaRefundMinor, field.TypeInt64, value)
		_node.DeltaRefundMinor = value
	}
	if value, ok := _c.mutation.TargetUsdUnits(); ok {
		_spec.SetField(paymentexternalrefundjournal.FieldTargetUsdUnits, field.TypeInt64, value)
		_node.TargetUsdUnits = value
	}
	if value, ok := _c.mutation.DeltaTargetUsdUnits(); ok {
		_spec.SetField(paymentexternalrefundjournal.FieldDeltaTargetUsdUnits, field.TypeInt64, value)
		_node.DeltaTargetUsdUnits = value
	}
	if value, ok := _c.mutation.RecoveredUsdUnits(); ok {
		_spec.SetField(paymentexternalrefundjournal.FieldRecoveredUsdUnits, field.TypeInt64, value)
		_node.RecoveredUsdUnits = value
	}
	if value, ok := _c.mutation.DebtUsdUnits(); ok {
		_spec.SetField(paymentexternalrefundjournal.FieldDebtUsdUnits, field.TypeInt64, value)
		_node.DebtUsdUnits = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(paymentexternalrefundjournal.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(paymentexternalrefundjournal.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentexternalrefundjournal.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PaymentExternalRefundJournal.Create().
//		SetExternalOrderLedgerID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PaymentExternalRefundJournalUpsert) {
//			SetExternalOrderLedgerID(v+v).
//		}).
//		Exec(ctx)
func (_c *PaymentExternalRefundJournalCreate) OnConflict(opts ...sql.ConflictOption) *PaymentExternalRefundJournalUpsertOne {
	_c.conflict = opts
	return &PaymentExternalRefundJournalUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PaymentExternalRefundJournal.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PaymentExternalRefundJournalCreate) OnConflictColumns(columns ...string) *PaymentExternalRefundJournalUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PaymentExternalRefundJournalUpsertOne{
		create: _c,
	}
}

type (
	// PaymentExternalRefundJournalUpsertOne is the builder for "upsert"-ing
	//  one PaymentExternalRefundJournal node.
	PaymentExternalRefundJournalUpsertOne struct {
		create *PaymentExternalRefundJournalCreate
	}

	// PaymentExternalRefundJournalUpsert is the "OnConflict" setter.
	PaymentExternalRefundJournalUpsert struct {
		*sql.UpdateSet
	}
)

// SetExternalOrderLedgerID sets the "external_order_ledger_id" field.
func (u *PaymentExternalRefundJournalUpsert) SetExternalOrderLedgerID(v int64) *PaymentExternalRefundJournalUpsert {
	u.Set(paymentexternalrefundjournal.FieldExternalOrderLedgerID, v)
	return u
}

// UpdateExternalOrderLedgerID sets the "external_order_ledger_id" field to the value that was provided on create.
func (u *PaymentExternalRefundJournalUpsert) UpdateExternalOrderLedgerID() *PaymentExternalRefundJournalUpsert {
	u.SetExcluded(paymentexternalrefundjournal.FieldExternalOrderLedgerID)
	return u
}

// AddExternalOrderLedgerID adds v to the "external_order_ledger_id" field.
func (u *PaymentExternalRefundJournalUpsert) AddExternalOrderLedgerID(v int64) *PaymentExternalRefundJournalUpsert {
	u.Add(paymentexternalrefundjournal.FieldExternalOrderLedgerID, v)
	return u
}

// SetCumulativeRefundMinor sets the "cumulative_refund_minor" field.
func (u *PaymentExternalRefundJournalUpsert) SetCumulativeRefundMinor(v int64) *PaymentExternalRefundJournalUpsert {
	u.Set(paymentexternalrefundjournal.FieldCumulativeRefundMinor, v)
	return u
}

// UpdateCumulativeRefundMinor sets the "cumulative_refund_minor" field to the value that was provided on create.
func (u *PaymentExternalRefundJournalUpsert) UpdateCumulativeRefundMinor() *PaymentExternalRefundJournalUpsert {
	u.SetExcluded(paymentexternalrefundjournal.FieldCumulativeRefundMinor)
	return u
}

// AddCumulativeRefundMinor adds v to the "cumulative_refund_minor" field.
func (u *PaymentExternalRefundJournalUpsert) AddCumulativeRefundMinor(v int64) *PaymentExternalRefundJournalUpsert {
	u.Add(paymentexternalrefundjournal.FieldCumulativeRefundMinor, v)
	return u
}

// SetDeltaRefundMinor sets the "delta_refund_minor" field.
func (u *PaymentExternalRefundJournalUpsert) SetDeltaRefundMinor(v int64) *PaymentExternalRefundJournalUpsert {
	u.Set(paymentexternalrefundjournal.FieldDeltaRefundMinor, v)
	return u
}

// UpdateDeltaRefundMinor sets the "delta_refund_minor" field to the value that was provided on create.
func (u *PaymentExternalRefundJournalUpsert) UpdateDeltaRefundMinor() *PaymentExternalRefundJournalUpsert {
	u.SetExcluded(paymentexternalrefundjournal.FieldDeltaRefundMinor)
	return u
}

// AddDeltaRefundMinor adds v to the "delta_refund_minor" field.
func (u *PaymentExternalRefundJournalUpsert) AddDeltaRefundMinor(v int64) *PaymentExternalRefundJournalUpsert {
	u.Add(paymentexternalrefundjournal.FieldDeltaRefundMinor, v)
	return u
}

// SetTargetUsdUnits sets the "target_usd_units" field.
func (u *PaymentExternalRefundJournalUpsert) SetTargetUsdUnits(v int64) *PaymentExternalRefundJournalUpsert {
	u.Set(paymentexternalrefundjournal.FieldTargetUsdUnits, v)
	return u
}

// UpdateTargetUsdUnits sets the "target_usd_units" field to the value that was provided on create.
func (u *PaymentExternalRefundJournalUpsert) UpdateTargetUsdUnits() *PaymentExternalRefundJournalUpsert {
	u.SetExcluded(paymentexternalrefundjournal.FieldTargetUsdUnits)
	return u
}

// AddTargetUsdUnits adds v to the "target_usd_units" field.
func (u *PaymentExternalRefundJournalUpsert) AddTargetUsdUnits(v int64) *PaymentExternalRefundJournalUpsert {
	u.Add(paymentexternalrefundjournal.FieldTargetUsdUnits, v)
	return u
}

// SetDeltaTargetUsdUnits sets the "delta_target_usd_units" field.
func (u *PaymentExternalRefundJournalUpsert) SetDeltaTargetUsdUnits(v int64) *PaymentExternalRefundJournalUpsert {
	u.Set(paymentexternalrefundjournal.FieldDeltaTargetUsdUnits, v)
	return u
}

// UpdateDeltaTargetUsdUnits sets the "delta_target_usd_units" field to the value that was provided on create.
func (u *PaymentExternalRefundJournalUpsert) UpdateDeltaTargetUsdUnits() *PaymentExternalRefundJournalUpsert {
	u.SetExcluded(paymentexternalrefundjournal.FieldDeltaTargetUsdUnits)
	return u
}

// AddDeltaTargetUsdUnits adds v to the "delta_target_usd_units" field.
func (u *PaymentExternalRefundJournalUpsert) AddDeltaTargetUsdUnits(v int64) *PaymentExternalRefundJournalUpsert {
	u.Add(paymentexternalrefundjournal.FieldDeltaTargetUsdUnits, v)
	return u
}

// SetRecoveredUsdUnits sets the "recovered_usd_units" field.
func (u *PaymentExternalRefundJournalUpsert) SetRecoveredUsdUnits(v int64) *PaymentExternalRefundJournalUpsert {
	u.Set(paymentexternalrefundjournal.FieldRecoveredUsdUnits, v)
	return u
}

// UpdateRecoveredUsdUnits sets the "recovered_usd_units" field to the value that was provided on create.
func (u *PaymentExternalRefundJournalUpsert) UpdateRecoveredUsdUnits() *PaymentExternalRefundJournalUpsert {
	u.SetExcluded(paymentexternalrefundjournal.FieldRecoveredUsdUnits)
	return u
}

// AddRecoveredUsdUnits adds v to the "recovered_usd_units" field.
func (u *PaymentExternalRefundJournalUpsert) AddRecoveredUsdUnits(v int64) *PaymentExternalRefundJournalUpsert {
	u.Add(paymentexternalrefundjournal.FieldRecoveredUsdUnits, v)
	return u
}

// SetDebtUsdUnits sets the "debt_usd_units" field.
func (u *PaymentExternalRefundJournalUpsert) SetDebtUsdUnits(v int64) *PaymentExternalRefundJournalUpsert {
	u.Set(paymentexternalrefundjournal.FieldDebtUsdUnits, v)
	return u
}

// UpdateDebtUsdUnits sets the "debt_usd_units" field to the value that was provided on create.
func (u *PaymentExternalRefundJournalUpsert) UpdateDebtUsdUnits() *PaymentExternalRefundJournalUpsert {
	u.SetExcluded(paymentexternalrefundjournal.FieldDebtUsdUnits)
	return u
}

// AddDebtUsdUnits adds v to the "debt_usd_units" field.
func (u *PaymentExternalRefundJournalUpsert) AddDebtUsdUnits(v int64) *PaymentExternalRefundJournalUpsert {
	u.Add(paymentexternalrefundjournal.FieldDebtUsdUnits, v)
	return u
}

// SetStatus sets the "status" field.
func (u *PaymentExternalRefundJournalUpsert) SetStatus(v string) *PaymentExternalRefundJournalUpsert {
	u.Set(paymentexternalrefundjournal.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PaymentExternalRefundJournalUpsert) UpdateStatus() *PaymentExternalRefundJournalUpsert {
	u.SetExcluded(paymentexternalrefundjournal.FieldStatus)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PaymentExternalRefundJournalUpsert) SetUpdatedAt(v time.Time) *PaymentExternalRefundJournalUpsert {
	u.Set(paymentexternalrefundjournal.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PaymentExternalRefundJournalUpsert) UpdateUpdatedAt() *PaymentExternalRefundJournalUpsert {
	u.SetExcluded(paymentexternalrefundjournal.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.PaymentExternalRefundJournal.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PaymentExternalRefundJournalUpsertOne) UpdateNewValues() *PaymentExternalRefundJournalUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(paymentexternalrefundjournal.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PaymentExternalRefundJournal.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PaymentExternalRefundJournalUpsertOne) Ignore() *PaymentExternalRefundJournalUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PaymentExternalRefundJournalUpsertOne) DoNothing() *PaymentExternalRefundJournalUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PaymentExternalRefundJournalCreate.OnConflict
// documentation for more info.
func (u *PaymentExternalRefundJournalUpsertOne) Update(set func(*PaymentExternalRefundJournalUpsert)) *PaymentExternalRefundJournalUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PaymentExternalRefundJournalUpsert{UpdateSet: update})
	}))
	return u
}

// SetExternalOrderLedgerID sets the "external_order_ledger_id" field.
func (u *PaymentExternalRefundJournalUpsertOne) SetExternalOrderLedgerID(v int64) *PaymentExternalRefundJournalUpsertOne {
	return u.Update(func(s *PaymentExternalRefundJournalUpsert) {
		s.SetExternalOrderLedgerID(v)
	})
}

// AddExternalOrderLedgerID adds v to the "external_order_ledger_id" field.
func (u *PaymentExternalRefundJournalUpsertOne) AddExternalOrderLedgerID(v int64) *PaymentExternalRefundJournalUpsertOne {
	return u.Update(func(s *PaymentExternalRefundJournalUpsert) {
		s.AddExternalOrderLedgerID(v)
	})
}

// UpdateExternalOrderLedgerID sets the "external_order_ledger_id" field to the value that was provided on create.
func (u *PaymentExternalRefundJournalUpsertOne) UpdateExternalOrderLedgerID() *PaymentExternalRefundJournalUpsertOne {
	return u.Update(func(s *PaymentExternalRefundJournalUpsert) {
		s.UpdateExternalOrderLedgerID()
	})
}

// SetCumulativeRefundMinor sets the "cumulative_refund_minor" field.
func (u *PaymentExternalRefundJournalUpsertOne) SetCumulativeRefundMinor(v int64) *PaymentExternalRefundJournalUpsertOne {
	return u.Update(func(s *PaymentExternalRefundJournalUpsert) {
		s.SetCumulativeRefundMinor(v)
	})
}

// AddCumulativeRefundMinor adds v to the "cumulative_refund_minor" field.
func (u *PaymentExternalRefundJournalUpsertOne) AddCumulativeRefundMinor(v int64) *PaymentExternalRefundJournalUpsertOne {
	return u.Update(func(s *PaymentExternalRefundJournalUpsert) {
		s.AddCumulativeRefundMinor(v)
	})
}

// UpdateCumulativeRefundMinor sets the "cumulative_refund_minor" field to the value that was provided on create.
func (u *PaymentExternalRefundJournalUpsertOne) UpdateCumulativeRefundMinor() *PaymentExternalRefundJournalUpsertOne {
	return u.Update(func(s *PaymentExternalRefundJournalUpsert) {
		s.UpdateCumulativeRefundMinor()
	})
}

// SetDeltaRefundMinor sets the "delta_refund_minor" field.
func (u *PaymentExternalRefundJournalUpsertOne) SetDeltaRefundMinor(v int64) *PaymentExternalRefundJournalUpsertOne {
	return u.Update(func(s *PaymentExternalRefundJournalUpsert) {
		s.SetDeltaRefundMinor(v)
	})
}

// AddDeltaRefundMinor adds v to the "delta_refund_minor" field.
func (u *PaymentExternalRefundJournalUpsertOne) AddDeltaRefundMinor(v int64) *PaymentExternalRefundJournalUpsertOne {
	return u.Update(func(s *PaymentExternalRefundJournalUpsert) {
		s.AddDeltaRefundMinor(v)
	})
}

// UpdateDeltaRefundMinor sets the "delta_refund_minor" field to the value that was provided on create.
func (u *PaymentExternalRefundJournalUpsertOne) UpdateDeltaRefundMinor() *PaymentExternalRefundJournalUpsertOne {
	return u.Update(func(s *PaymentExternalRefundJournalUpsert) {
		s.UpdateDeltaRefundMinor()
	})
}

// SetTargetUsdUnits sets the "target_usd_units" field.
func (u *PaymentExternalRefundJournalUpsertOne) SetTargetUsdUnits(v int64) *PaymentExternalRefundJournalUpsertOne {
	return u.Update(func(s *PaymentExternalRefundJournalUpsert) {
		s.SetTargetUsdUnits(v)
	})
}

// AddTargetUsdUnits adds v to the "target_usd_units" field.
func (u *PaymentExternalRefundJournalUpsertOne) AddTargetUsdUnits(v int64) *PaymentExternalRefundJournalUpsertOne {
	return u.Update(func(s *PaymentExternalRefundJournalUpsert) {
		s.AddTargetUsdUnits(v)
	})
}

// UpdateTargetUsdUnits sets the "target_usd_units" field to the value that was provided on create.
func (u *PaymentExternalRefundJournalUpsertOne) UpdateTargetUsdUnits() *PaymentExternalRefundJournalUpsertOne {
	return u.Update(func(s *PaymentExternalRefundJournalUpsert) {
		s.UpdateTargetUsdUnits()
	})
}

// SetDeltaTargetUsdUnits sets the "delta_target_usd_units" field.
func (u *PaymentExternalRefundJournalUpsertOne) SetDeltaTargetUsdUnits(v int64) *PaymentExternalRefundJournalUpsertOne {
	return u.Update(func(s *PaymentExternalRefundJournalUpsert) {
		s.SetDeltaTargetUsdUnits(v)
	})
}

// AddDeltaTargetUsdUnits adds v to the "delta_target_usd_units" field.
func (u *PaymentExternalRefundJournalUpsertOne) AddDeltaTargetUsdUnits(v int64) *PaymentExternalRefundJournalUpsertOne {
	return u.Update(func(s *PaymentExternalRefundJournalUpsert) {
		s.AddDeltaTargetUsdUnits(v)
	})
}

// UpdateDeltaTargetUsdUnits sets the "delta_target_usd_units" field to the value that was provided on create.
func (u *PaymentExternalRefundJournalUpsertOne) UpdateDeltaTargetUsdUnits() *PaymentExternalRefundJournalUpsertOne {
	return u.Update(func(s *PaymentExternalRefundJournalUpsert) {
		s.UpdateDeltaTargetUsdUnits()
	})
}

// SetRecoveredUsdUnits sets the "recovered_usd_units" field.
func (u *PaymentExternalRefundJournalUpsertOne) SetRecoveredUsdUnits(v int64) *PaymentExternalRefundJournalUpsertOne {
	return u.Update(func(s *PaymentExternalRefundJournalUpsert) {
		s.SetRecoveredUsdUnits(v)
	})
}

// AddRecoveredUsdUnits adds v to the "recovered_usd_units" field.
func (u *PaymentExternalRefundJournalUpsertOne) AddRecoveredUsdUnits(v int64) *PaymentExternalRefundJournalUpsertOne {
	return u.Update(func(s *PaymentExternalRefundJournalUpsert) {
		s.AddRecoveredUsdUnits(v)
	})
}

// UpdateRecoveredUsdUnits sets the "recovered_usd_units" field to the value that was provided on create.
func (u *PaymentExternalRefundJournalUpsertOne) UpdateRecoveredUsdUnits() *PaymentExternalRefundJournalUpsertOne {
	return u.Update(func(s *PaymentExternalRefundJournalUpsert) {
		s.UpdateRecoveredUsdUnits()
	})
}

// SetDebtUsdUnits sets the "debt_usd_units" field.
func (u *PaymentExternalRefundJournalUpsertOne) SetDebtUsdUnits(v int64) *PaymentExternalRefundJournalUpsertOne {
	return u.Update(func(s *PaymentExternalRefundJournalUpsert) {
		s.SetDebtUsdUnits(v)
	})
}

// AddDebtUsdUnits adds v to the "debt_usd_units" field.
func (u *PaymentExternalRefundJournalUpsertOne) AddDebtUsdUnits(v int64) *PaymentExternalRefundJournalUpsertOne {
	return u.Update(func(s *PaymentExternalRefundJournalUpsert) {
		s.AddDebtUsdUnits(v)
	})
}

// UpdateDebtUsdUnits sets the "debt_usd_units" field to the value that was provided on create.
func (u *PaymentExternalRefundJournalUpsertOne) UpdateDebtUsdUnits() *PaymentExternalRefundJournalUpsertOne {
	return u.Update(func(s *PaymentExternalRefundJournalUpsert) {
		s.UpdateDebtUsdUnits()
	})
}

// SetStatus sets the "status" field.
func (u *PaymentExternalRefundJournalUpsertOne) SetStatus(v string) *PaymentExternalRefundJournalUpsertOne {
	return u.Update(func(s *PaymentExternalRefundJournalUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PaymentExternalRefundJournalUpsertOne) UpdateStatus() *PaymentExternalRefundJournalUpsertOne {
	return u.Update(func(s *PaymentExternalRefundJournalUpsert) {
		s.UpdateStatus()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PaymentExternalRefundJournalUpsertOne) SetUpdatedAt(v time.Time) *PaymentExternalRefundJournalUpsertOne {
	return u.Update(func(s *PaymentExternalRefundJournalUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PaymentExternalRefundJournalUpsertOne) UpdateUpdatedAt() *PaymentExternalRefundJournalUpsertOne {
	return u.Update(func(s *PaymentExternalRefundJournalUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PaymentExternalRefundJournalUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PaymentExternalRefundJournalCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PaymentExternalRefundJournalUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PaymentExternalRefundJournalUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PaymentExternalRefundJournalUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PaymentExternalRefundJournalCreateBulk is the builder for creating many PaymentExternalRefundJournal entities in bulk.
type PaymentExternalRefundJournalCreateBulk struct {
	config
	err      error
	builders []*PaymentExternalRefundJournalCreate
	conflict []sql.ConflictOption
}

// Save creates the PaymentExternalRefundJournal entities in the database.
func (_c *PaymentExternalRefundJournalCreateBulk) Save(ctx context.Context) ([]*PaymentExternalRefundJournal, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PaymentExternalRefundJournal, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PaymentExternalRefundJournalMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PaymentExternalRefundJournalCreateBulk) SaveX(ctx context.Context) []*PaymentExternalRefundJournal {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PaymentExternalRefundJournalCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PaymentExternalRefundJournalCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PaymentExternalRefundJournal.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PaymentExternalRefundJournalUpsert) {
//			SetExternalOrderLedgerID(v+v).
//		}).
//		Exec(ctx)
func (_c *PaymentExternalRefundJournalCreateBulk) OnConflict(opts ...sql.ConflictOption) *PaymentExternalRefundJournalUpsertBulk {
	_c.conflict = opts
	return &PaymentExternalRefundJournalUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PaymentExternalRefundJournal.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PaymentExternalRefundJournalCreateBulk) OnConflictColumns(columns ...string) *PaymentExternalRefundJournalUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PaymentExternalRefundJournalUpsertBulk{
		create: _c,
	}
}

// PaymentExternalRefundJournalUpsertBulk is the builder for "upsert"-ing
// a bulk of PaymentExternalRefundJournal nodes.
type PaymentExternalRefundJournalUpsertBulk struct {
	create *PaymentExternalRefundJournalCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PaymentExternalRefundJournal.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PaymentExternalRefundJournalUpsertBulk) UpdateNewValues() *PaymentExternalRefundJournalUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(paymentexternalrefundjournal.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PaymentExternalRefundJournal.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PaymentExternalRefundJournalUpsertBulk) Ignore() *PaymentExternalRefundJournalUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PaymentExternalRefundJournalUpsertBulk) DoNothing() *PaymentExternalRefundJournalUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PaymentExternalRefundJournalCreateBulk.OnConflict
// documentation for more info.
func (u *PaymentExternalRefundJournalUpsertBulk) Update(set func(*PaymentExternalRefundJournalUpsert)) *PaymentExternalRefundJournalUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PaymentExternalRefundJournalUpsert{UpdateSet: update})
	}))
	return u
}

// SetExternalOrderLedgerID sets the "external_order_ledger_id" field.
func (u *PaymentExternalRefundJournalUpsertBulk) SetExternalOrderLedgerID(v int64) *PaymentExternalRefundJournalUpsertBulk {
	return u.Update(func(s *PaymentExternalRefundJournalUpsert) {
		s.SetExternalOrderLedgerID(v)
	})
}

// AddExternalOrderLedgerID adds v to the "external_order_ledger_id" field.
func (u *PaymentExternalRefundJournalUpsertBulk) AddExternalOrderLedgerID(v int64) *PaymentExternalRefundJournalUpsertBulk {
	return u.Update(func(s *PaymentExternalRefundJournalUpsert) {
		s.AddExternalOrderLedgerID(v)
	})
}

// UpdateExternalOrderLedgerID sets the "external_order_ledger_id" field to the value that was provided on create.
func (u *PaymentExternalRefundJournalUpsertBulk) UpdateExternalOrderLedgerID() *PaymentExternalRefundJournalUpsertBulk {
	return u.Update(func(s *PaymentExternalRefundJournalUpsert) {
		s.UpdateExternalOrderLedgerID()
	})
}

// SetCumulativeRefundMinor sets the "cumulative_refund_minor" field.
func (u *PaymentExternalRefundJournalUpsertBulk) SetCumulativeRefundMinor(v int64) *PaymentExternalRefundJournalUpsertBulk {
	return u.Update(func(s *PaymentExternalRefundJournalUpsert) {
		s.SetCumulativeRefundMinor(v)
	})
}

// AddCumulativeRefundMinor adds v to the "cumulative_refund_minor" field.
func (u *PaymentExternalRefundJournalUpsertBulk) AddCumulativeRefundMinor(v int64) *PaymentExternalRefundJournalUpsertBulk {
	return u.Update(func(s *PaymentExternalRefundJournalUpsert) {
		s.AddCumulativeRefundMinor(v)
	})
}

// UpdateCumulativeRefundMinor sets the "cumulative_refund_minor" field to the value that was provided on create.
func (u *PaymentExternalRefundJournalUpsertBulk) UpdateCumulativeRefundMinor() *PaymentExternalRefundJournalUpsertBulk {
	return u.Update(func(s *PaymentExternalRefundJournalUpsert) {
		s.UpdateCumulativeRefundMinor()
	})
}

// SetDeltaRefundMinor sets the "delta_refund_minor" field.
func (u *PaymentExternalRefundJournalUpsertBulk) SetDeltaRefundMinor(v int64) *PaymentExternalRefundJournalUpsertBulk {
	return u.Update(func(s *PaymentExternalRefundJournalUpsert) {
		s.SetDeltaRefundMinor(v)
	})
}

// AddDeltaRefundMinor adds v to the "delta_refund_minor" field.
func (u *PaymentExternalRefundJournalUpsertBulk) AddDeltaRefundMinor(v int64) *PaymentExternalRefundJournalUpsertBulk {
	return u.Update(func(s *PaymentExternalRefundJournalUpsert) {
		s.AddDeltaRefundMinor(v)
	})
}

// UpdateDeltaRefundMinor sets the "delta_refund_minor" field to the value that was provided on create.
func (u *PaymentExternalRefundJournalUpsertBulk) UpdateDeltaRefundMinor() *PaymentExternalRefundJournalUpsertBulk {
	return u.Update(func(s *PaymentExternalRefundJournalUpsert) {
		s.UpdateDeltaRefundMinor()
	})
}

// SetTargetUsdUnits sets the "target_usd_units" field.
func (u *PaymentExternalRefundJournalUpsertBulk) SetTargetUsdUnits(v int64) *PaymentExternalRefundJournalUpsertBulk {
	return u.Update(func(s *PaymentExternalRefundJournalUpsert) {
		s.SetTargetUsdUnits(v)
	})
}

// AddTargetUsdUnits adds v to the "target_usd_units" field.
func (u *PaymentExternalRefundJournalUpsertBulk) AddTargetUsdUnits(v int64) *PaymentExternalRefundJournalUpsertBulk {
	return u.Update(func(s *PaymentExternalRefundJournalUpsert) {
		s.AddTargetUsdUnits(v)
	})
}

// UpdateTargetUsdUnits sets the "target_usd_units" field to the value that was provided on create.
func (u *PaymentExternalRefundJournalUpsertBulk) UpdateTargetUsdUnits() *PaymentExternalRefundJournalUpsertBulk {
	return u.Update(func(s *PaymentExternalRefundJournalUpsert) {
		s.UpdateTargetUsdUnits()
	})
}

// SetDeltaTargetUsdUnits sets the "delta_target_usd_units" field.
func (u *PaymentExternalRefundJournalUpsertBulk) SetDeltaTargetUsdUnits(v int64) *PaymentExternalRefundJournalUpsertBulk {
	return u.Update(func(s *PaymentExternalRefundJournalUpsert) {
		s.SetDeltaTargetUsdUnits(v)
	})
}

// AddDeltaTargetUsdUnits adds v to the "delta_target_usd_units" field.
func (u *PaymentExternalRefundJournalUpsertBulk) AddDeltaTargetUsdUnits(v int64) *PaymentExternalRefundJournalUpsertBulk {
	return u.Update(func(s *PaymentExternalRefundJournalUpsert) {
		s.AddDeltaTargetUsdUnits(v)
	})
}

// UpdateDeltaTargetUsdUnits sets the "delta_target_usd_units" field to the value that was provided on create.
func (u *PaymentExternalRefundJournalUpsertBulk) UpdateDeltaTargetUsdUnits() *PaymentExternalRefundJournalUpsertBulk {
	return u.Update(func(s *PaymentExternalRefundJournalUpsert) {
		s.UpdateDeltaTargetUsdUnits()
	})
}

// SetRecoveredUsdUnits sets the "recovered_usd_units" field.
func (u *PaymentExternalRefundJournalUpsertBulk) SetRecoveredUsdUnits(v int64) *PaymentExternalRefundJournalUpsertBulk {
	return u.Update(func(s *PaymentExternalRefundJournalUpsert) {
		s.SetRecoveredUsdUnits(v)
	})
}

// AddRecoveredUsdUnits adds v to the "recovered_usd_units" field.
func (u *PaymentExternalRefundJournalUpsertBulk) AddRecoveredUsdUnits(v int64) *PaymentExternalRefundJournalUpsertBulk {
	return u.Update(func(s *PaymentExternalRefundJournalUpsert) {
		s.AddRecoveredUsdUnits(v)
	})
}

// UpdateRecoveredUsdUnits sets the "recovered_usd_units" field to the value that was provided on create.
func (u *PaymentExternalRefundJournalUpsertBulk) UpdateRecoveredUsdUnits() *PaymentExternalRefundJournalUpsertBulk {
	return u.Update(func(s *PaymentExternalRefundJournalUpsert) {
		s.UpdateRecoveredUsdUnits()
	})
}

// SetDebtUsdUnits sets the "debt_usd_units" field.
func (u *PaymentExternalRefundJournalUpsertBulk) SetDebtUsdUnits(v int64) *PaymentExternalRefundJournalUpsertBulk {
	return u.Update(func(s *PaymentExternalRefundJournalUpsert) {
		s.SetDebtUsdUnits(v)
	})
}

// AddDebtUsdUnits adds v to the "debt_usd_units" field.
func (u *PaymentExternalRefundJournalUpsertBulk) AddDebtUsdUnits(v int64) *PaymentExternalRefundJournalUpsertBulk {
	return u.Update(func(s *PaymentExternalRefundJournalUpsert) {
		s.AddDebtUsdUnits(v)
	})
}

// UpdateDebtUsdUnits sets the "debt_usd_units" field to the value that was provided on create.
func (u *PaymentExternalRefundJournalUpsertBulk) UpdateDebtUsdUnits() *PaymentExternalRefundJournalUpsertBulk {
	return u.Update(func(s *PaymentExternalRefundJournalUpsert) {
		s.UpdateDebtUsdUnits()
	})
}

// SetStatus sets the "status" field.
func (u *PaymentExternalRefundJournalUpsertBulk) SetStatus(v string) *PaymentExternalRefundJournalUpsertBulk {
	return u.Update(func(s *PaymentExternalRefundJournalUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PaymentExternalRefundJournalUpsertBulk) UpdateStatus() *PaymentExternalRefundJournalUpsertBulk {
	return u.Update(func(s *PaymentExternalRefundJournalUpsert) {
		s.UpdateStatus()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PaymentExternalRefundJournalUpsertBulk) SetUpdatedAt(v time.Time) *PaymentExternalRefundJournalUpsertBulk {
	return u.Update(func(s *PaymentExternalRefundJournalUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PaymentExternalRefundJournalUpsertBulk) UpdateUpdatedAt() *PaymentExternalRefundJournalUpsertBulk {
	return u.Update(func(s *PaymentExternalRefundJournalUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PaymentExternalRefundJournalUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PaymentExternalRefundJournalCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PaymentExternalRefundJournalCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PaymentExternalRefundJournalUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
