// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/paymentexternalorder"
)

// PaymentExternalOrder is the model entity for the PaymentExternalOrder schema.
type PaymentExternalOrder struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// ProviderKey holds the value of the "provider_key" field.
	ProviderKey string `json:"provider_key,omitempty"`
	// WebsiteID holds the value of the "website_id" field.
	WebsiteID string `json:"website_id,omitempty"`
	// ExternalOrderID holds the value of the "external_order_id" field.
	ExternalOrderID string `json:"external_order_id,omitempty"`
	// OrderNumber holds the value of the "order_number" field.
	OrderNumber string `json:"order_number,omitempty"`
	// BindingMethod holds the value of the "binding_method" field.
	BindingMethod string `json:"binding_method,omitempty"`
	// QuoteHash holds the value of the "quote_hash" field.
	QuoteHash string `json:"quote_hash,omitempty"`
	// LocalOrderID holds the value of the "local_order_id" field.
	LocalOrderID *int64 `json:"local_order_id,omitempty"`
	// CheckoutReference holds the value of the "checkout_reference" field.
	CheckoutReference string `json:"checkout_reference,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// TotalMinor holds the value of the "total_minor" field.
	TotalMinor int64 `json:"total_minor,omitempty"`
	// RefundedMinor holds the value of the "refunded_minor" field.
	RefundedMinor int64 `json:"refunded_minor,omitempty"`
	// CreditedUsdUnits holds the value of the "credited_usd_units" field.
	CreditedUsdUnits int64 `json:"credited_usd_units,omitempty"`
	// RefundTargetUsdUnits holds the value of the "refund_target_usd_units" field.
	RefundTargetUsdUnits int64 `json:"refund_target_usd_units,omitempty"`
	// RecoveredUsdUnits holds the value of the "recovered_usd_units" field.
	RecoveredUsdUnits int64 `json:"recovered_usd_units,omitempty"`
	// DebtUsdUnits holds the value of the "debt_usd_units" field.
	DebtUsdUnits int64 `json:"debt_usd_units,omitempty"`
	// PaymentState holds the value of the "payment_state" field.
	PaymentState string `json:"payment_state,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// AnomalyCode holds the value of the "anomaly_code" field.
	AnomalyCode string `json:"anomaly_code,omitempty"`
	// PaidAt holds the value of the "paid_at" field.
	PaidAt *time.Time `json:"paid_at,omitempty"`
	// ProviderModifiedAt holds the value of the "provider_modified_at" field.
	ProviderModifiedAt *time.Time `json:"provider_modified_at,omitempty"`
	// LastSeenAt holds the value of the "last_seen_at" field.
	LastSeenAt time.Time `json:"last_seen_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PaymentExternalOrder) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case paymentexternalorder.FieldID, paymentexternalorder.FieldLocalOrderID, paymentexternalorder.FieldTotalMinor, paymentexternalorder.FieldRefundedMinor, paymentexternalorder.FieldCreditedUsdUnits, paymentexternalorder.FieldRefundTargetUsdUnits, paymentexternalorder.FieldRecoveredUsdUnits, paymentexternalorder.FieldDebtUsdUnits:
			values[i] = new(sql.NullInt64)
		case paymentexternalorder.FieldProviderKey, paymentexternalorder.FieldWebsiteID, paymentexternalorder.FieldExternalOrderID, paymentexternalorder.FieldOrderNumber, paymentexternalorder.FieldBindingMethod, paymentexternalorder.FieldQuoteHash, paymentexternalorder.FieldCheckoutReference, paymentexternalorder.FieldCurrency, paymentexternalorder.FieldPaymentState, paymentexternalorder.FieldStatus, paymentexternalorder.FieldAnomalyCode:
			values[i] = new(sql.NullString)
		case paymentexternalorder.FieldPaidAt, paymentexternalorder.FieldProviderModifiedAt, paymentexternalorder.FieldLastSeenAt, paymentexternalorder.FieldCreatedAt, paymentexternalorder.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PaymentExternalOrder fields.
func (_m *PaymentExternalOrder) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case paymentexternalorder.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case paymentexternalorder.FieldProviderKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_key", values[i])
			} else if value.Valid {
				_m.ProviderKey = value.String
			}
		case paymentexternalorder.FieldWebsiteID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field website_id", values[i])
			} else if value.Valid {
				_m.WebsiteID = value.String
			}
		case paymentexternalorder.FieldExternalOrderID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field external_order_id", values[i])
			} else if value.Valid {
				_m.ExternalOrderID = value.String
			}
		case paymentexternalorder.FieldOrderNumber:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field order_number", values[i])
			} else if value.Valid {
				_m.OrderNumber = value.String
			}
		case paymentexternalorder.FieldBindingMethod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field binding_method", values[i])
			} else if value.Valid {
				_m.BindingMethod = value.String
			}
		case paymentexternalorder.FieldQuoteHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field quote_hash", values[i])
			} else if value.Valid {
				_m.QuoteHash = value.String
			}
		case paymentexternalorder.FieldLocalOrderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field local_order_id", values[i])
			} else if value.Valid {
				_m.LocalOrderID = new(int64)
				*_m.LocalOrderID = value.Int64
			}
		case paymentexternalorder.FieldCheckoutReference:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field checkout_reference", values[i])
			} else if value.Valid {
				_m.CheckoutReference = value.String
			}
		case paymentexternalorder.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case paymentexternalorder.FieldTotalMinor:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_minor", values[i])
			} else if value.Valid {
				_m.TotalMinor = value.Int64
			}
		case paymentexternalorder.FieldRefundedMinor:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field refunded_minor", values[i])
			} else if value.Valid {
				_m.RefundedMinor = value.Int64
			}
		case paymentexternalorder.FieldCreditedUsdUnits:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field credited_usd_units", values[i])
			} else if value.Valid {
				_m.CreditedUsdUnits = value.Int64
			}
		case paymentexternalorder.FieldRefundTargetUsdUnits:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field refund_target_usd_units", values[i])
			} else if value.Valid {
				_m.RefundTargetUsdUnits = value.Int64
			}
		case paymentexternalorder.FieldRecoveredUsdUnits:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field recovered_usd_units", values[i])
			} else if value.Valid {
				_m.RecoveredUsdUnits = value.Int64
			}
		case paymentexternalorder.FieldDebtUsdUnits:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field debt_usd_units", values[i])
			} else if value.Valid {
				_m.DebtUsdUnits = value.Int64
			}
		case paymentexternalorder.FieldPaymentState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payment_state", values[i])
			} else if value.Valid {
				_m.PaymentState = value.String
			}
		case paymentexternalorder.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case paymentexternalorder.FieldAnomalyCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field anomaly_code", values[i])
			} else if value.Valid {
				_m.AnomalyCode = value.String
			}
		case paymentexternalorder.FieldPaidAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field paid_at", values[i])
			} else if value.Valid {
				_m.PaidAt = new(time.Time)
				*_m.PaidAt = value.Time
			}
		case paymentexternalorder.FieldProviderModifiedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field provider_modified_at", values[i])
			} else if value.Valid {
				_m.ProviderModifiedAt = new(time.Time)
				*_m.ProviderModifiedAt = value.Time
			}
		case paymentexternalorder.FieldLastSeenAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_seen_at", values[i])
			} else if value.Valid {
				_m.LastSeenAt = value.Time
			}
		case paymentexternalorder.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case paymentexternalorder.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PaymentExternalOrder.
// This includes values selected through modifiers, order, etc.
func (_m *PaymentExternalOrder) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this PaymentExternalOrder.
// Note that you need to call PaymentExternalOrder.Unwrap() before calling this method if this PaymentExternalOrder
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PaymentExternalOrder) Update() *PaymentExternalOrderUpdateOne {
	return NewPaymentExternalOrderClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PaymentExternalOrder entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PaymentExternalOrder) Unwrap() *PaymentExternalOrder {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PaymentExternalOrder is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PaymentExternalOrder) String() string {
	var builder strings.Builder
	builder.WriteString("PaymentExternalOrder(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("provider_key=")
	builder.WriteString(_m.ProviderKey)
	builder.WriteString(", ")
	builder.WriteString("website_id=")
	builder.WriteString(_m.WebsiteID)
	builder.WriteString(", ")
	builder.WriteString("external_order_id=")
	builder.WriteString(_m.ExternalOrderID)
	builder.WriteString(", ")
	builder.WriteString("order_number=")
	builder.WriteString(_m.OrderNumber)
	builder.WriteString(", ")
	builder.WriteString("binding_method=")
	builder.WriteString(_m.BindingMethod)
	builder.WriteString(", ")
	builder.WriteString("quote_hash=")
	builder.WriteString(_m.QuoteHash)
	builder.WriteString(", ")
	if v := _m.LocalOrderID; v != nil {
		builder.WriteString("local_order_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("checkout_reference=")
	builder.WriteString(_m.CheckoutReference)
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	builder.WriteString("total_minor=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalMinor))
	builder.WriteString(", ")
	builder.WriteString("refunded_minor=")
	builder.WriteString(fmt.Sprintf("%v", _m.RefundedMinor))
	builder.WriteString(", ")
	builder.WriteString("credited_usd_units=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreditedUsdUnits))
	builder.WriteString(", ")
	builder.WriteString("refund_target_usd_units=")
	builder.WriteString(fmt.Sprintf("%v", _m.RefundTargetUsdUnits))
	builder.WriteString(", ")
	builder.WriteString("recovered_usd_units=")
	builder.WriteString(fmt.Sprintf("%v", _m.RecoveredUsdUnits))
	builder.WriteString(", ")
	builder.WriteString("debt_usd_units=")
	builder.WriteString(fmt.Sprintf("%v", _m.DebtUsdUnits))
	builder.WriteString(", ")
	builder.WriteString("payment_state=")
	builder.WriteString(_m.PaymentState)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("anomaly_code=")
	builder.WriteString(_m.AnomalyCode)
	builder.WriteString(", ")
	if v := _m.PaidAt; v != nil {
		builder.WriteString("paid_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ProviderModifiedAt; v != nil {
		builder.WriteString("provider_modified_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("last_seen_at=")
	builder.WriteString(_m.LastSeenAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PaymentExternalOrders is a parsable slice of PaymentExternalOrder.
type PaymentExternalOrders []*PaymentExternalOrder
