// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/paymentexternalrefundjournal"
)

// PaymentExternalRefundJournal is the model entity for the PaymentExternalRefundJournal schema.
type PaymentExternalRefundJournal struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// ExternalOrderLedgerID holds the value of the "external_order_ledger_id" field.
	ExternalOrderLedgerID int64 `json:"external_order_ledger_id,omitempty"`
	// CumulativeRefundMinor holds the value of the "cumulative_refund_minor" field.
	CumulativeRefundMinor int64 `json:"cumulative_refund_minor,omitempty"`
	// DeltaRefundMinor holds the value of the "delta_refund_minor" field.
	DeltaRefundMinor int64 `json:"delta_refund_minor,omitempty"`
	// TargetUsdUnits holds the value of the "target_usd_units" field.
	TargetUsdUnits int64 `json:"target_usd_units,omitempty"`
	// DeltaTargetUsdUnits holds the value of the "delta_target_usd_units" field.
	DeltaTargetUsdUnits int64 `json:"delta_target_usd_units,omitempty"`
	// RecoveredUsdUnits holds the value of the "recovered_usd_units" field.
	RecoveredUsdUnits int64 `json:"recovered_usd_units,omitempty"`
	// DebtUsdUnits holds the value of the "debt_usd_units" field.
	DebtUsdUnits int64 `json:"debt_usd_units,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PaymentExternalRefundJournal) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case paymentexternalrefundjournal.FieldID, paymentexternalrefundjournal.FieldExternalOrderLedgerID, paymentexternalrefundjournal.FieldCumulativeRefundMinor, paymentexternalrefundjournal.FieldDeltaRefundMinor, paymentexternalrefundjournal.FieldTargetUsdUnits, paymentexternalrefundjournal.FieldDeltaTargetUsdUnits, paymentexternalrefundjournal.FieldRecoveredUsdUnits, paymentexternalrefundjournal.FieldDebtUsdUnits:
			values[i] = new(sql.NullInt64)
		case paymentexternalrefundjournal.FieldStatus:
			values[i] = new(sql.NullString)
		case paymentexternalrefundjournal.FieldCreatedAt, paymentexternalrefundjournal.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PaymentExternalRefundJournal fields.
func (_m *PaymentExternalRefundJournal) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case paymentexternalrefundjournal.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case paymentexternalrefundjournal.FieldExternalOrderLedgerID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field external_order_ledger_id", values[i])
			} else if value.Valid {
				_m.ExternalOrderLedgerID = value.Int64
			}
		case paymentexternalrefundjournal.FieldCumulativeRefundMinor:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cumulative_refund_minor", values[i])
			} else if value.Valid {
				_m.CumulativeRefundMinor = value.Int64
			}
		case paymentexternalrefundjournal.FieldDeltaRefundMinor:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field delta_refund_minor", values[i])
			} else if value.Valid {
				_m.DeltaRefundMinor = value.Int64
			}
		case paymentexternalrefundjournal.FieldTargetUsdUnits:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field target_usd_units", values[i])
			} else if value.Valid {
				_m.TargetUsdUnits = value.Int64
			}
		case paymentexternalrefundjournal.FieldDeltaTargetUsdUnits:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field delta_target_usd_units", values[i])
			} else if value.Valid {
				_m.DeltaTargetUsdUnits = value.Int64
			}
		case paymentexternalrefundjournal.FieldRecoveredUsdUnits:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field recovered_usd_units", values[i])
			} else if value.Valid {
				_m.RecoveredUsdUnits = value.Int64
			}
		case paymentexternalrefundjournal.FieldDebtUsdUnits:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field debt_usd_units", values[i])
			} else if value.Valid {
				_m.DebtUsdUnits = value.Int64
			}
		case paymentexternalrefundjournal.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case paymentexternalrefundjournal.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case paymentexternalrefundjournal.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PaymentExternalRefundJournal.
// This includes values selected through modifiers, order, etc.
func (_m *PaymentExternalRefundJournal) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this PaymentExternalRefundJournal.
// Note that you need to call PaymentExternalRefundJournal.Unwrap() before calling this method if this PaymentExternalRefundJournal
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PaymentExternalRefundJournal) Update() *PaymentExternalRefundJournalUpdateOne {
	return NewPaymentExternalRefundJournalClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PaymentExternalRefundJournal entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PaymentExternalRefundJournal) Unwrap() *PaymentExternalRefundJournal {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PaymentExternalRefundJournal is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PaymentExternalRefundJournal) String() string {
	var builder strings.Builder
	builder.WriteString("PaymentExternalRefundJournal(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("external_order_ledger_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExternalOrderLedgerID))
	builder.WriteString(", ")
	builder.WriteString("cumulative_refund_minor=")
	builder.WriteString(fmt.Sprintf("%v", _m.CumulativeRefundMinor))
	builder.WriteString(", ")
	builder.WriteString("delta_refund_minor=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeltaRefundMinor))
	builder.WriteString(", ")
	builder.WriteString("target_usd_units=")
	builder.WriteString(fmt.Sprintf("%v", _m.TargetUsdUnits))
	builder.WriteString(", ")
	builder.WriteString("delta_target_usd_units=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeltaTargetUsdUnits))
	builder.WriteString(", ")
	builder.WriteString("recovered_usd_units=")
	builder.WriteString(fmt.Sprintf("%v", _m.RecoveredUsdUnits))
	builder.WriteString(", ")
	builder.WriteString("debt_usd_units=")
	builder.WriteString(fmt.Sprintf("%v", _m.DebtUsdUnits))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PaymentExternalRefundJournals is a parsable slice of PaymentExternalRefundJournal.
type PaymentExternalRefundJournals []*PaymentExternalRefundJournal
