import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { flushPromises, mount } from '@vue/test-utils'
import SquarespaceReceiptClaim from '../SquarespaceReceiptClaim.vue'
const requestCode = vi.hoisted(() => vi.fn())
const claim = vi.hoisted(() => vi.fn())
vi.mock('vue-i18n', async () => ({ ...(await vi.importActual<typeof import('vue-i18n')>('vue-i18n')), useI18n: () => ({ t: (key: string) => key }) }))
vi.mock('@/api/payment', () => ({ paymentAPI: { requestSquarespaceClaimCode: requestCode, claimSquarespacePayment: claim } }))
function challenge(ttl = 600000) { return { data: { challenge_token: 'opaque-owned-challenge', expires_at: new Date(Date.now() + ttl).toISOString(), resend_after_seconds: 60 } } }
function order(status = 'COMPLETED', id = 42) { return { data: { id, payment_type: 'squarespace', status } } }
async function form() {
  const wrapper = mount(SquarespaceReceiptClaim, { props: { orderId: 42, accountEmail: 'mine@example.com' } })
  await wrapper.get('[data-test="start-receipt-claim"]').trigger('click')
  await wrapper.get('[data-test="receipt-order-number"]').setValue('#1234')
  await wrapper.get('[data-test="receipt-payer-email"]').setValue('payer@example.com')
  return wrapper
}
async function send(wrapper: Awaited<ReturnType<typeof form>>) {
  await wrapper.get('[data-test="request-claim-code"]').trigger('click')
  await flushPromises()
}

describe('Squarespace receipt claim', () => {
  beforeEach(() => {
    vi.useFakeTimers(); vi.setSystemTime(new Date('2026-09-29T12:00:00Z'))
    requestCode.mockReset().mockResolvedValue(challenge())
    claim.mockReset().mockResolvedValue(order())
  })
  afterEach(() => { vi.useRealTimers() })
  it('binds the actual payment email and local order separately from the balance destination without exposing the challenge token', async () => {
    const wrapper = await form()
    await send(wrapper)
    expect(requestCode).toHaveBeenCalledWith(42, '#1234', 'payer@example.com')
    expect(wrapper.get('[data-test="receipt-payer-email"]').element).toHaveProperty('value', 'payer@example.com')
    expect(wrapper.text()).toContain('mine@example.com')
    expect(wrapper.text()).toContain('paymentRetail.claim.codeRequested')
    expect(wrapper.html()).not.toContain('opaque-owned-challenge')
    expect(wrapper.emitted('updated')).toBeUndefined()
    await wrapper.get('[data-test="receipt-claim-code"]').setValue('123456')
    await wrapper.get('[data-test="confirm-receipt-claim"]').trigger('click')
    await flushPromises()
    expect(claim).toHaveBeenCalledWith('opaque-owned-challenge', '123456')
    expect(wrapper.emitted('updated')?.[0]?.[0]).toEqual(order().data)
    wrapper.unmount()
  })
  it('does not silently use the registered account email and requires an actual bare payment email', async () => {
    const wrapper = mount(SquarespaceReceiptClaim, { props: { orderId: 42, accountEmail: 'mine@example.com' } })
    await wrapper.get('[data-test="start-receipt-claim"]').trigger('click')
    await wrapper.get('[data-test="receipt-order-number"]').setValue('#1234')
    expect(wrapper.get('[data-test="receipt-payer-email"]').element).toHaveProperty('value', '')
    expect(wrapper.get('[data-test="request-claim-code"]').attributes('disabled')).toBeDefined()
    await wrapper.get('[data-test="receipt-payer-email"]').setValue('Payer <payer@example.com>')
    expect(wrapper.get('[data-test="request-claim-code"]').attributes('disabled')).toBeDefined()
    await wrapper.get('[data-test="receipt-payer-email"]').setValue('  payer@example.com  ')
    await send(wrapper)
    expect(requestCode).toHaveBeenCalledWith(42, '#1234', 'payer@example.com')
    wrapper.unmount()
  })

  it('invalidates a challenge when the payment email changes and ignores a delayed prior-email challenge', async () => {
    let resolve!: (value: ReturnType<typeof challenge>) => void
    requestCode.mockImplementationOnce(() => new Promise(done => { resolve = done }))
    const wrapper = await form()
    await wrapper.get('[data-test="request-claim-code"]').trigger('click')
    await wrapper.get('[data-test="receipt-payer-email"]').setValue('other-owned@example.com')
    resolve(challenge())
    await flushPromises()
    expect(wrapper.find('[data-test="receipt-claim-code"]').exists()).toBe(false)
    expect(claim).not.toHaveBeenCalled()
    wrapper.unmount()
  })

  it.each(['email mismatch', 'amount mismatch', 'paid outside quote', 'receipt already claimed', 'different product'])('shows the same safe failure for %s without upstream details', async cause => {
    requestCode.mockRejectedValueOnce({ reason: 'SQUARESPACE_CLAIM_UNAVAILABLE', message: `${cause}: someone-else@example.com paid GBP 999` })
    const wrapper = await form()
    await send(wrapper)
    expect(wrapper.text()).toContain('paymentRetail.claim.unavailable')
    expect(wrapper.text()).not.toContain('someone-else@example.com')
    expect(wrapper.text()).not.toContain('999')
    expect(wrapper.emitted('updated')).toBeUndefined()
    wrapper.unmount()
  })
  it('invalidates a challenge when the receipt number changes and ignores a delayed old response', async () => {
    let resolve!: (value: ReturnType<typeof challenge>) => void
    requestCode.mockImplementationOnce(() => new Promise(done => { resolve = done }))
    const wrapper = await form()
    await wrapper.get('[data-test="request-claim-code"]').trigger('click')
    await wrapper.get('[data-test="receipt-order-number"]').setValue('#9999')
    resolve(challenge())
    await flushPromises()
    expect(wrapper.find('[data-test="receipt-claim-code"]').exists()).toBe(false)
    expect(claim).not.toHaveBeenCalled()
    wrapper.unmount()
  })
  it('blocks expired codes while allowing another challenge after the resend cooldown', async () => {
    requestCode.mockResolvedValueOnce(challenge(1000))
    const wrapper = await form()
    await send(wrapper)
    await wrapper.get('[data-test="receipt-claim-code"]').setValue('123456')
    await vi.advanceTimersByTimeAsync(2000)
    expect(wrapper.text()).toContain('paymentRetail.claim.codeExpired')
    expect(wrapper.get('[data-test="confirm-receipt-claim"]').attributes('disabled')).toBeDefined()
    expect(wrapper.get('[data-test="request-claim-code"]').attributes('disabled')).toBeDefined()
    await vi.advanceTimersByTimeAsync(59000)
    await send(wrapper)
    expect(requestCode).toHaveBeenCalledTimes(2)
    expect(claim).not.toHaveBeenCalled()
    wrapper.unmount()
  })
  it('shows rate limiting without sending overlapping requests', async () => {
    requestCode.mockRejectedValueOnce({ reason: 'SQUARESPACE_CLAIM_RATE_LIMITED' })
    const wrapper = await form()
    await send(wrapper)
    await wrapper.get('[data-test="request-claim-code"]').trigger('click')
    expect(requestCode).toHaveBeenCalledTimes(1)
    expect(wrapper.text()).toContain('paymentRetail.claim.rateLimited')
    wrapper.unmount()
  })
  it('does not mark a payment complete when the claim returns PAID', async () => {
    claim.mockResolvedValueOnce(order('PAID'))
    const wrapper = await form()
    await send(wrapper)
    await wrapper.get('[data-test="receipt-claim-code"]').setValue('123456')
    await wrapper.get('[data-test="confirm-receipt-claim"]').trigger('click')
    await flushPromises()
    expect(wrapper.text()).toContain('paymentRetail.creditProcessing')
    expect(wrapper.text()).not.toContain('payment.result.success')
    expect(wrapper.emitted('updated')?.[0]?.[0]).toEqual(order('PAID').data)
    wrapper.unmount()
  })
  it.each(['SQUARESPACE_CLAIM_CODE_INVALID', 'SQUARESPACE_CLAIM_SERVICE_UNAVAILABLE'])('does not credit after %s and refreshes authoritative status', async reason => {
    claim.mockRejectedValueOnce({ reason, message: 'private upstream data' })
    const wrapper = await form()
    await send(wrapper)
    await wrapper.get('[data-test="receipt-claim-code"]').setValue('123456')
    await wrapper.get('[data-test="confirm-receipt-claim"]').trigger('click')
    await flushPromises()
    expect(wrapper.emitted('updated')).toBeUndefined()
    expect(wrapper.emitted('refresh')).toHaveLength(1)
    expect(wrapper.text()).not.toContain('private upstream data')
    wrapper.unmount()
  })
  it('blocks duplicate in-flight verification and rejects a mismatched local order result', async () => {
    let resolve!: (value: ReturnType<typeof order>) => void
    claim.mockImplementationOnce(() => new Promise(done => { resolve = done }))
    const wrapper = await form()
    await send(wrapper)
    await wrapper.get('[data-test="receipt-claim-code"]').setValue('123456')
    await wrapper.get('[data-test="confirm-receipt-claim"]').trigger('click')
    await wrapper.get('[data-test="confirm-receipt-claim"]').trigger('click')
    expect(claim).toHaveBeenCalledTimes(1)
    resolve(order('COMPLETED', 999))
    await flushPromises()
    expect(wrapper.emitted('updated')).toBeUndefined()
    expect(wrapper.text()).toContain('paymentRetail.claim.serviceUnavailable')
    wrapper.unmount()
  })
})
