// Code generated by ent, DO NOT EDIT.

package paymentexternalpayment

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the paymentexternalpayment type in the database.
	Label = "payment_external_payment"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldProviderKey holds the string denoting the provider_key field in the database.
	FieldProviderKey = "provider_key"
	// FieldWebsiteID holds the string denoting the website_id field in the database.
	FieldWebsiteID = "website_id"
	// FieldPaymentID holds the string denoting the payment_id field in the database.
	FieldPaymentID = "payment_id"
	// FieldExternalOrderLedgerID holds the string denoting the external_order_ledger_id field in the database.
	FieldExternalOrderLedgerID = "external_order_ledger_id"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldAmountMinor holds the string denoting the amount_minor field in the database.
	FieldAmountMinor = "amount_minor"
	// FieldRefundedMinor holds the string denoting the refunded_minor field in the database.
	FieldRefundedMinor = "refunded_minor"
	// FieldPaidAt holds the string denoting the paid_at field in the database.
	FieldPaidAt = "paid_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the paymentexternalpayment in the database.
	Table = "payment_external_payments"
)

// Columns holds all SQL columns for paymentexternalpayment fields.
var Columns = []string{
	FieldID,
	FieldProviderKey,
	FieldWebsiteID,
	FieldPaymentID,
	FieldExternalOrderLedgerID,
	FieldCurrency,
	FieldAmountMinor,
	FieldRefundedMinor,
	FieldPaidAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ProviderKeyValidator is a validator for the "provider_key" field. It is called by the builders before save.
	ProviderKeyValidator func(string) error
	// WebsiteIDValidator is a validator for the "website_id" field. It is called by the builders before save.
	WebsiteIDValidator func(string) error
	// PaymentIDValidator is a validator for the "payment_id" field. It is called by the builders before save.
	PaymentIDValidator func(string) error
	// CurrencyValidator is a validator for the "currency" field. It is called by the builders before save.
	CurrencyValidator func(string) error
	// DefaultRefundedMinor holds the default value on creation for the "refunded_minor" field.
	DefaultRefundedMinor int64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the PaymentExternalPayment queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByProviderKey orders the results by the provider_key field.
func ByProviderKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderKey, opts...).ToFunc()
}

// ByWebsiteID orders the results by the website_id field.
func ByWebsiteID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWebsiteID, opts...).ToFunc()
}

// ByPaymentID orders the results by the payment_id field.
func ByPaymentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaymentID, opts...).ToFunc()
}

// ByExternalOrderLedgerID orders the results by the external_order_ledger_id field.
func ByExternalOrderLedgerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExternalOrderLedgerID, opts...).ToFunc()
}

// ByCurrency orders the results by the currency field.
func ByCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrency, opts...).ToFunc()
}

// ByAmountMinor orders the results by the amount_minor field.
func ByAmountMinor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmountMinor, opts...).ToFunc()
}

// ByRefundedMinor orders the results by the refunded_minor field.
func ByRefundedMinor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefundedMinor, opts...).ToFunc()
}

// ByPaidAt orders the results by the paid_at field.
func ByPaidAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaidAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
