// Code generated by ent, DO NOT EDIT.

package paymentexternalpayment

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldLTE(FieldID, id))
}

// ProviderKey applies equality check predicate on the "provider_key" field. It's identical to ProviderKeyEQ.
func ProviderKey(v string) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldEQ(FieldProviderKey, v))
}

// WebsiteID applies equality check predicate on the "website_id" field. It's identical to WebsiteIDEQ.
func WebsiteID(v string) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldEQ(FieldWebsiteID, v))
}

// PaymentID applies equality check predicate on the "payment_id" field. It's identical to PaymentIDEQ.
func PaymentID(v string) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldEQ(FieldPaymentID, v))
}

// ExternalOrderLedgerID applies equality check predicate on the "external_order_ledger_id" field. It's identical to ExternalOrderLedgerIDEQ.
func ExternalOrderLedgerID(v int64) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldEQ(FieldExternalOrderLedgerID, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldEQ(FieldCurrency, v))
}

// AmountMinor applies equality check predicate on the "amount_minor" field. It's identical to AmountMinorEQ.
func AmountMinor(v int64) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldEQ(FieldAmountMinor, v))
}

// RefundedMinor applies equality check predicate on the "refunded_minor" field. It's identical to RefundedMinorEQ.
func RefundedMinor(v int64) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldEQ(FieldRefundedMinor, v))
}

// PaidAt applies equality check predicate on the "paid_at" field. It's identical to PaidAtEQ.
func PaidAt(v time.Time) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldEQ(FieldPaidAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldEQ(FieldUpdatedAt, v))
}

// ProviderKeyEQ applies the EQ predicate on the "provider_key" field.
func ProviderKeyEQ(v string) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldEQ(FieldProviderKey, v))
}

// ProviderKeyNEQ applies the NEQ predicate on the "provider_key" field.
func ProviderKeyNEQ(v string) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldNEQ(FieldProviderKey, v))
}

// ProviderKeyIn applies the In predicate on the "provider_key" field.
func ProviderKeyIn(vs ...string) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldIn(FieldProviderKey, vs...))
}

// ProviderKeyNotIn applies the NotIn predicate on the "provider_key" field.
func ProviderKeyNotIn(vs ...string) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldNotIn(FieldProviderKey, vs...))
}

// ProviderKeyGT applies the GT predicate on the "provider_key" field.
func ProviderKeyGT(v string) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldGT(FieldProviderKey, v))
}

// ProviderKeyGTE applies the GTE predicate on the "provider_key" field.
func ProviderKeyGTE(v string) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldGTE(FieldProviderKey, v))
}

// ProviderKeyLT applies the LT predicate on the "provider_key" field.
func ProviderKeyLT(v string) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldLT(FieldProviderKey, v))
}

// ProviderKeyLTE applies the LTE predicate on the "provider_key" field.
func ProviderKeyLTE(v string) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldLTE(FieldProviderKey, v))
}

// ProviderKeyContains applies the Contains predicate on the "provider_key" field.
func ProviderKeyContains(v string) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldContains(FieldProviderKey, v))
}

// ProviderKeyHasPrefix applies the HasPrefix predicate on the "provider_key" field.
func ProviderKeyHasPrefix(v string) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldHasPrefix(FieldProviderKey, v))
}

// ProviderKeyHasSuffix applies the HasSuffix predicate on the "provider_key" field.
func ProviderKeyHasSuffix(v string) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldHasSuffix(FieldProviderKey, v))
}

// ProviderKeyEqualFold applies the EqualFold predicate on the "provider_key" field.
func ProviderKeyEqualFold(v string) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldEqualFold(FieldProviderKey, v))
}

// ProviderKeyContainsFold applies the ContainsFold predicate on the "provider_key" field.
func ProviderKeyContainsFold(v string) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldContainsFold(FieldProviderKey, v))
}

// WebsiteIDEQ applies the EQ predicate on the "website_id" field.
func WebsiteIDEQ(v string) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldEQ(FieldWebsiteID, v))
}

// WebsiteIDNEQ applies the NEQ predicate on the "website_id" field.
func WebsiteIDNEQ(v string) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldNEQ(FieldWebsiteID, v))
}

// WebsiteIDIn applies the In predicate on the "website_id" field.
func WebsiteIDIn(vs ...string) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldIn(FieldWebsiteID, vs...))
}

// WebsiteIDNotIn applies the NotIn predicate on the "website_id" field.
func WebsiteIDNotIn(vs ...string) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldNotIn(FieldWebsiteID, vs...))
}

// WebsiteIDGT applies the GT predicate on the "website_id" field.
func WebsiteIDGT(v string) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldGT(FieldWebsiteID, v))
}

// WebsiteIDGTE applies the GTE predicate on the "website_id" field.
func WebsiteIDGTE(v string) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldGTE(FieldWebsiteID, v))
}

// WebsiteIDLT applies the LT predicate on the "website_id" field.
func WebsiteIDLT(v string) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldLT(FieldWebsiteID, v))
}

// WebsiteIDLTE applies the LTE predicate on the "website_id" field.
func WebsiteIDLTE(v string) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldLTE(FieldWebsiteID, v))
}

// WebsiteIDContains applies the Contains predicate on the "website_id" field.
func WebsiteIDContains(v string) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldContains(FieldWebsiteID, v))
}

// WebsiteIDHasPrefix applies the HasPrefix predicate on the "website_id" field.
func WebsiteIDHasPrefix(v string) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldHasPrefix(FieldWebsiteID, v))
}

// WebsiteIDHasSuffix applies the HasSuffix predicate on the "website_id" field.
func WebsiteIDHasSuffix(v string) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldHasSuffix(FieldWebsiteID, v))
}

// WebsiteIDEqualFold applies the EqualFold predicate on the "website_id" field.
func WebsiteIDEqualFold(v string) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldEqualFold(FieldWebsiteID, v))
}

// WebsiteIDContainsFold applies the ContainsFold predicate on the "website_id" field.
func WebsiteIDContainsFold(v string) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldContainsFold(FieldWebsiteID, v))
}

// PaymentIDEQ applies the EQ predicate on the "payment_id" field.
func PaymentIDEQ(v string) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldEQ(FieldPaymentID, v))
}

// PaymentIDNEQ applies the NEQ predicate on the "payment_id" field.
func PaymentIDNEQ(v string) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldNEQ(FieldPaymentID, v))
}

// PaymentIDIn applies the In predicate on the "payment_id" field.
func PaymentIDIn(vs ...string) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldIn(FieldPaymentID, vs...))
}

// PaymentIDNotIn applies the NotIn predicate on the "payment_id" field.
func PaymentIDNotIn(vs ...string) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldNotIn(FieldPaymentID, vs...))
}

// PaymentIDGT applies the GT predicate on the "payment_id" field.
func PaymentIDGT(v string) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldGT(FieldPaymentID, v))
}

// PaymentIDGTE applies the GTE predicate on the "payment_id" field.
func PaymentIDGTE(v string) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldGTE(FieldPaymentID, v))
}

// PaymentIDLT applies the LT predicate on the "payment_id" field.
func PaymentIDLT(v string) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldLT(FieldPaymentID, v))
}

// PaymentIDLTE applies the LTE predicate on the "payment_id" field.
func PaymentIDLTE(v string) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldLTE(FieldPaymentID, v))
}

// PaymentIDContains applies the Contains predicate on the "payment_id" field.
func PaymentIDContains(v string) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldContains(FieldPaymentID, v))
}

// PaymentIDHasPrefix applies the HasPrefix predicate on the "payment_id" field.
func PaymentIDHasPrefix(v string) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldHasPrefix(FieldPaymentID, v))
}

// PaymentIDHasSuffix applies the HasSuffix predicate on the "payment_id" field.
func PaymentIDHasSuffix(v string) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldHasSuffix(FieldPaymentID, v))
}

// PaymentIDEqualFold applies the EqualFold predicate on the "payment_id" field.
func PaymentIDEqualFold(v string) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldEqualFold(FieldPaymentID, v))
}

// PaymentIDContainsFold applies the ContainsFold predicate on the "payment_id" field.
func PaymentIDContainsFold(v string) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldContainsFold(FieldPaymentID, v))
}

// ExternalOrderLedgerIDEQ applies the EQ predicate on the "external_order_ledger_id" field.
func ExternalOrderLedgerIDEQ(v int64) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldEQ(FieldExternalOrderLedgerID, v))
}

// ExternalOrderLedgerIDNEQ applies the NEQ predicate on the "external_order_ledger_id" field.
func ExternalOrderLedgerIDNEQ(v int64) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldNEQ(FieldExternalOrderLedgerID, v))
}

// ExternalOrderLedgerIDIn applies the In predicate on the "external_order_ledger_id" field.
func ExternalOrderLedgerIDIn(vs ...int64) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldIn(FieldExternalOrderLedgerID, vs...))
}

// ExternalOrderLedgerIDNotIn applies the NotIn predicate on the "external_order_ledger_id" field.
func ExternalOrderLedgerIDNotIn(vs ...int64) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldNotIn(FieldExternalOrderLedgerID, vs...))
}

// ExternalOrderLedgerIDGT applies the GT predicate on the "external_order_ledger_id" field.
func ExternalOrderLedgerIDGT(v int64) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldGT(FieldExternalOrderLedgerID, v))
}

// ExternalOrderLedgerIDGTE applies the GTE predicate on the "external_order_ledger_id" field.
func ExternalOrderLedgerIDGTE(v int64) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldGTE(FieldExternalOrderLedgerID, v))
}

// ExternalOrderLedgerIDLT applies the LT predicate on the "external_order_ledger_id" field.
func ExternalOrderLedgerIDLT(v int64) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldLT(FieldExternalOrderLedgerID, v))
}

// ExternalOrderLedgerIDLTE applies the LTE predicate on the "external_order_ledger_id" field.
func ExternalOrderLedgerIDLTE(v int64) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldLTE(FieldExternalOrderLedgerID, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldContainsFold(FieldCurrency, v))
}

// AmountMinorEQ applies the EQ predicate on the "amount_minor" field.
func AmountMinorEQ(v int64) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldEQ(FieldAmountMinor, v))
}

// AmountMinorNEQ applies the NEQ predicate on the "amount_minor" field.
func AmountMinorNEQ(v int64) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldNEQ(FieldAmountMinor, v))
}

// AmountMinorIn applies the In predicate on the "amount_minor" field.
func AmountMinorIn(vs ...int64) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldIn(FieldAmountMinor, vs...))
}

// AmountMinorNotIn applies the NotIn predicate on the "amount_minor" field.
func AmountMinorNotIn(vs ...int64) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldNotIn(FieldAmountMinor, vs...))
}

// AmountMinorGT applies the GT predicate on the "amount_minor" field.
func AmountMinorGT(v int64) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldGT(FieldAmountMinor, v))
}

// AmountMinorGTE applies the GTE predicate on the "amount_minor" field.
func AmountMinorGTE(v int64) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldGTE(FieldAmountMinor, v))
}

// AmountMinorLT applies the LT predicate on the "amount_minor" field.
func AmountMinorLT(v int64) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldLT(FieldAmountMinor, v))
}

// AmountMinorLTE applies the LTE predicate on the "amount_minor" field.
func AmountMinorLTE(v int64) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldLTE(FieldAmountMinor, v))
}

// RefundedMinorEQ applies the EQ predicate on the "refunded_minor" field.
func RefundedMinorEQ(v int64) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldEQ(FieldRefundedMinor, v))
}

// RefundedMinorNEQ applies the NEQ predicate on the "refunded_minor" field.
func RefundedMinorNEQ(v int64) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldNEQ(FieldRefundedMinor, v))
}

// RefundedMinorIn applies the In predicate on the "refunded_minor" field.
func RefundedMinorIn(vs ...int64) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldIn(FieldRefundedMinor, vs...))
}

// RefundedMinorNotIn applies the NotIn predicate on the "refunded_minor" field.
func RefundedMinorNotIn(vs ...int64) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldNotIn(FieldRefundedMinor, vs...))
}

// RefundedMinorGT applies the GT predicate on the "refunded_minor" field.
func RefundedMinorGT(v int64) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldGT(FieldRefundedMinor, v))
}

// RefundedMinorGTE applies the GTE predicate on the "refunded_minor" field.
func RefundedMinorGTE(v int64) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldGTE(FieldRefundedMinor, v))
}

// RefundedMinorLT applies the LT predicate on the "refunded_minor" field.
func RefundedMinorLT(v int64) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldLT(FieldRefundedMinor, v))
}

// RefundedMinorLTE applies the LTE predicate on the "refunded_minor" field.
func RefundedMinorLTE(v int64) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldLTE(FieldRefundedMinor, v))
}

// PaidAtEQ applies the EQ predicate on the "paid_at" field.
func PaidAtEQ(v time.Time) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldEQ(FieldPaidAt, v))
}

// PaidAtNEQ applies the NEQ predicate on the "paid_at" field.
func PaidAtNEQ(v time.Time) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldNEQ(FieldPaidAt, v))
}

// PaidAtIn applies the In predicate on the "paid_at" field.
func PaidAtIn(vs ...time.Time) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldIn(FieldPaidAt, vs...))
}

// PaidAtNotIn applies the NotIn predicate on the "paid_at" field.
func PaidAtNotIn(vs ...time.Time) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldNotIn(FieldPaidAt, vs...))
}

// PaidAtGT applies the GT predicate on the "paid_at" field.
func PaidAtGT(v time.Time) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldGT(FieldPaidAt, v))
}

// PaidAtGTE applies the GTE predicate on the "paid_at" field.
func PaidAtGTE(v time.Time) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldGTE(FieldPaidAt, v))
}

// PaidAtLT applies the LT predicate on the "paid_at" field.
func PaidAtLT(v time.Time) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldLT(FieldPaidAt, v))
}

// PaidAtLTE applies the LTE predicate on the "paid_at" field.
func PaidAtLTE(v time.Time) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldLTE(FieldPaidAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PaymentExternalPayment) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PaymentExternalPayment) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PaymentExternalPayment) predicate.PaymentExternalPayment {
	return predicate.PaymentExternalPayment(sql.NotPredicates(p))
}
