// Code generated by ent, DO NOT EDIT.

package paymentexternalrefundjournal

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the paymentexternalrefundjournal type in the database.
	Label = "payment_external_refund_journal"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldExternalOrderLedgerID holds the string denoting the external_order_ledger_id field in the database.
	FieldExternalOrderLedgerID = "external_order_ledger_id"
	// FieldCumulativeRefundMinor holds the string denoting the cumulative_refund_minor field in the database.
	FieldCumulativeRefundMinor = "cumulative_refund_minor"
	// FieldDeltaRefundMinor holds the string denoting the delta_refund_minor field in the database.
	FieldDeltaRefundMinor = "delta_refund_minor"
	// FieldTargetUsdUnits holds the string denoting the target_usd_units field in the database.
	FieldTargetUsdUnits = "target_usd_units"
	// FieldDeltaTargetUsdUnits holds the string denoting the delta_target_usd_units field in the database.
	FieldDeltaTargetUsdUnits = "delta_target_usd_units"
	// FieldRecoveredUsdUnits holds the string denoting the recovered_usd_units field in the database.
	FieldRecoveredUsdUnits = "recovered_usd_units"
	// FieldDebtUsdUnits holds the string denoting the debt_usd_units field in the database.
	FieldDebtUsdUnits = "debt_usd_units"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the paymentexternalrefundjournal in the database.
	Table = "payment_external_refund_journals"
)

// Columns holds all SQL columns for paymentexternalrefundjournal fields.
var Columns = []string{
	FieldID,
	FieldExternalOrderLedgerID,
	FieldCumulativeRefundMinor,
	FieldDeltaRefundMinor,
	FieldTargetUsdUnits,
	FieldDeltaTargetUsdUnits,
	FieldRecoveredUsdUnits,
	FieldDebtUsdUnits,
	FieldStatus,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultRecoveredUsdUnits holds the default value on creation for the "recovered_usd_units" field.
	DefaultRecoveredUsdUnits int64
	// DefaultDebtUsdUnits holds the default value on creation for the "debt_usd_units" field.
	DefaultDebtUsdUnits int64
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the PaymentExternalRefundJournal queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByExternalOrderLedgerID orders the results by the external_order_ledger_id field.
func ByExternalOrderLedgerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExternalOrderLedgerID, opts...).ToFunc()
}

// ByCumulativeRefundMinor orders the results by the cumulative_refund_minor field.
func ByCumulativeRefundMinor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCumulativeRefundMinor, opts...).ToFunc()
}

// ByDeltaRefundMinor orders the results by the delta_refund_minor field.
func ByDeltaRefundMinor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeltaRefundMinor, opts...).ToFunc()
}

// ByTargetUsdUnits orders the results by the target_usd_units field.
func ByTargetUsdUnits(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetUsdUnits, opts...).ToFunc()
}

// ByDeltaTargetUsdUnits orders the results by the delta_target_usd_units field.
func ByDeltaTargetUsdUnits(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeltaTargetUsdUnits, opts...).ToFunc()
}

// ByRecoveredUsdUnits orders the results by the recovered_usd_units field.
func ByRecoveredUsdUnits(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRecoveredUsdUnits, opts...).ToFunc()
}

// ByDebtUsdUnits orders the results by the debt_usd_units field.
func ByDebtUsdUnits(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDebtUsdUnits, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
