// Code generated by ent, DO NOT EDIT.

package paymentexternalrefundjournal

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldLTE(FieldID, id))
}

// ExternalOrderLedgerID applies equality check predicate on the "external_order_ledger_id" field. It's identical to ExternalOrderLedgerIDEQ.
func ExternalOrderLedgerID(v int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldEQ(FieldExternalOrderLedgerID, v))
}

// CumulativeRefundMinor applies equality check predicate on the "cumulative_refund_minor" field. It's identical to CumulativeRefundMinorEQ.
func CumulativeRefundMinor(v int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldEQ(FieldCumulativeRefundMinor, v))
}

// DeltaRefundMinor applies equality check predicate on the "delta_refund_minor" field. It's identical to DeltaRefundMinorEQ.
func DeltaRefundMinor(v int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldEQ(FieldDeltaRefundMinor, v))
}

// TargetUsdUnits applies equality check predicate on the "target_usd_units" field. It's identical to TargetUsdUnitsEQ.
func TargetUsdUnits(v int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldEQ(FieldTargetUsdUnits, v))
}

// DeltaTargetUsdUnits applies equality check predicate on the "delta_target_usd_units" field. It's identical to DeltaTargetUsdUnitsEQ.
func DeltaTargetUsdUnits(v int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldEQ(FieldDeltaTargetUsdUnits, v))
}

// RecoveredUsdUnits applies equality check predicate on the "recovered_usd_units" field. It's identical to RecoveredUsdUnitsEQ.
func RecoveredUsdUnits(v int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldEQ(FieldRecoveredUsdUnits, v))
}

// DebtUsdUnits applies equality check predicate on the "debt_usd_units" field. It's identical to DebtUsdUnitsEQ.
func DebtUsdUnits(v int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldEQ(FieldDebtUsdUnits, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldEQ(FieldStatus, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldEQ(FieldUpdatedAt, v))
}

// ExternalOrderLedgerIDEQ applies the EQ predicate on the "external_order_ledger_id" field.
func ExternalOrderLedgerIDEQ(v int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldEQ(FieldExternalOrderLedgerID, v))
}

// ExternalOrderLedgerIDNEQ applies the NEQ predicate on the "external_order_ledger_id" field.
func ExternalOrderLedgerIDNEQ(v int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldNEQ(FieldExternalOrderLedgerID, v))
}

// ExternalOrderLedgerIDIn applies the In predicate on the "external_order_ledger_id" field.
func ExternalOrderLedgerIDIn(vs ...int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldIn(FieldExternalOrderLedgerID, vs...))
}

// ExternalOrderLedgerIDNotIn applies the NotIn predicate on the "external_order_ledger_id" field.
func ExternalOrderLedgerIDNotIn(vs ...int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldNotIn(FieldExternalOrderLedgerID, vs...))
}

// ExternalOrderLedgerIDGT applies the GT predicate on the "external_order_ledger_id" field.
func ExternalOrderLedgerIDGT(v int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldGT(FieldExternalOrderLedgerID, v))
}

// ExternalOrderLedgerIDGTE applies the GTE predicate on the "external_order_ledger_id" field.
func ExternalOrderLedgerIDGTE(v int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldGTE(FieldExternalOrderLedgerID, v))
}

// ExternalOrderLedgerIDLT applies the LT predicate on the "external_order_ledger_id" field.
func ExternalOrderLedgerIDLT(v int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldLT(FieldExternalOrderLedgerID, v))
}

// ExternalOrderLedgerIDLTE applies the LTE predicate on the "external_order_ledger_id" field.
func ExternalOrderLedgerIDLTE(v int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldLTE(FieldExternalOrderLedgerID, v))
}

// CumulativeRefundMinorEQ applies the EQ predicate on the "cumulative_refund_minor" field.
func CumulativeRefundMinorEQ(v int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldEQ(FieldCumulativeRefundMinor, v))
}

// CumulativeRefundMinorNEQ applies the NEQ predicate on the "cumulative_refund_minor" field.
func CumulativeRefundMinorNEQ(v int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldNEQ(FieldCumulativeRefundMinor, v))
}

// CumulativeRefundMinorIn applies the In predicate on the "cumulative_refund_minor" field.
func CumulativeRefundMinorIn(vs ...int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldIn(FieldCumulativeRefundMinor, vs...))
}

// CumulativeRefundMinorNotIn applies the NotIn predicate on the "cumulative_refund_minor" field.
func CumulativeRefundMinorNotIn(vs ...int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldNotIn(FieldCumulativeRefundMinor, vs...))
}

// CumulativeRefundMinorGT applies the GT predicate on the "cumulative_refund_minor" field.
func CumulativeRefundMinorGT(v int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldGT(FieldCumulativeRefundMinor, v))
}

// CumulativeRefundMinorGTE applies the GTE predicate on the "cumulative_refund_minor" field.
func CumulativeRefundMinorGTE(v int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldGTE(FieldCumulativeRefundMinor, v))
}

// CumulativeRefundMinorLT applies the LT predicate on the "cumulative_refund_minor" field.
func CumulativeRefundMinorLT(v int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldLT(FieldCumulativeRefundMinor, v))
}

// CumulativeRefundMinorLTE applies the LTE predicate on the "cumulative_refund_minor" field.
func CumulativeRefundMinorLTE(v int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldLTE(FieldCumulativeRefundMinor, v))
}

// DeltaRefundMinorEQ applies the EQ predicate on the "delta_refund_minor" field.
func DeltaRefundMinorEQ(v int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldEQ(FieldDeltaRefundMinor, v))
}

// DeltaRefundMinorNEQ applies the NEQ predicate on the "delta_refund_minor" field.
func DeltaRefundMinorNEQ(v int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldNEQ(FieldDeltaRefundMinor, v))
}

// DeltaRefundMinorIn applies the In predicate on the "delta_refund_minor" field.
func DeltaRefundMinorIn(vs ...int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldIn(FieldDeltaRefundMinor, vs...))
}

// DeltaRefundMinorNotIn applies the NotIn predicate on the "delta_refund_minor" field.
func DeltaRefundMinorNotIn(vs ...int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldNotIn(FieldDeltaRefundMinor, vs...))
}

// DeltaRefundMinorGT applies the GT predicate on the "delta_refund_minor" field.
func DeltaRefundMinorGT(v int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldGT(FieldDeltaRefundMinor, v))
}

// DeltaRefundMinorGTE applies the GTE predicate on the "delta_refund_minor" field.
func DeltaRefundMinorGTE(v int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldGTE(FieldDeltaRefundMinor, v))
}

// DeltaRefundMinorLT applies the LT predicate on the "delta_refund_minor" field.
func DeltaRefundMinorLT(v int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldLT(FieldDeltaRefundMinor, v))
}

// DeltaRefundMinorLTE applies the LTE predicate on the "delta_refund_minor" field.
func DeltaRefundMinorLTE(v int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldLTE(FieldDeltaRefundMinor, v))
}

// TargetUsdUnitsEQ applies the EQ predicate on the "target_usd_units" field.
func TargetUsdUnitsEQ(v int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldEQ(FieldTargetUsdUnits, v))
}

// TargetUsdUnitsNEQ applies the NEQ predicate on the "target_usd_units" field.
func TargetUsdUnitsNEQ(v int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldNEQ(FieldTargetUsdUnits, v))
}

// TargetUsdUnitsIn applies the In predicate on the "target_usd_units" field.
func TargetUsdUnitsIn(vs ...int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldIn(FieldTargetUsdUnits, vs...))
}

// TargetUsdUnitsNotIn applies the NotIn predicate on the "target_usd_units" field.
func TargetUsdUnitsNotIn(vs ...int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldNotIn(FieldTargetUsdUnits, vs...))
}

// TargetUsdUnitsGT applies the GT predicate on the "target_usd_units" field.
func TargetUsdUnitsGT(v int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldGT(FieldTargetUsdUnits, v))
}

// TargetUsdUnitsGTE applies the GTE predicate on the "target_usd_units" field.
func TargetUsdUnitsGTE(v int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldGTE(FieldTargetUsdUnits, v))
}

// TargetUsdUnitsLT applies the LT predicate on the "target_usd_units" field.
func TargetUsdUnitsLT(v int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldLT(FieldTargetUsdUnits, v))
}

// TargetUsdUnitsLTE applies the LTE predicate on the "target_usd_units" field.
func TargetUsdUnitsLTE(v int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldLTE(FieldTargetUsdUnits, v))
}

// DeltaTargetUsdUnitsEQ applies the EQ predicate on the "delta_target_usd_units" field.
func DeltaTargetUsdUnitsEQ(v int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldEQ(FieldDeltaTargetUsdUnits, v))
}

// DeltaTargetUsdUnitsNEQ applies the NEQ predicate on the "delta_target_usd_units" field.
func DeltaTargetUsdUnitsNEQ(v int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldNEQ(FieldDeltaTargetUsdUnits, v))
}

// DeltaTargetUsdUnitsIn applies the In predicate on the "delta_target_usd_units" field.
func DeltaTargetUsdUnitsIn(vs ...int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldIn(FieldDeltaTargetUsdUnits, vs...))
}

// DeltaTargetUsdUnitsNotIn applies the NotIn predicate on the "delta_target_usd_units" field.
func DeltaTargetUsdUnitsNotIn(vs ...int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldNotIn(FieldDeltaTargetUsdUnits, vs...))
}

// DeltaTargetUsdUnitsGT applies the GT predicate on the "delta_target_usd_units" field.
func DeltaTargetUsdUnitsGT(v int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldGT(FieldDeltaTargetUsdUnits, v))
}

// DeltaTargetUsdUnitsGTE applies the GTE predicate on the "delta_target_usd_units" field.
func DeltaTargetUsdUnitsGTE(v int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldGTE(FieldDeltaTargetUsdUnits, v))
}

// DeltaTargetUsdUnitsLT applies the LT predicate on the "delta_target_usd_units" field.
func DeltaTargetUsdUnitsLT(v int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldLT(FieldDeltaTargetUsdUnits, v))
}

// DeltaTargetUsdUnitsLTE applies the LTE predicate on the "delta_target_usd_units" field.
func DeltaTargetUsdUnitsLTE(v int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldLTE(FieldDeltaTargetUsdUnits, v))
}

// RecoveredUsdUnitsEQ applies the EQ predicate on the "recovered_usd_units" field.
func RecoveredUsdUnitsEQ(v int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldEQ(FieldRecoveredUsdUnits, v))
}

// RecoveredUsdUnitsNEQ applies the NEQ predicate on the "recovered_usd_units" field.
func RecoveredUsdUnitsNEQ(v int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldNEQ(FieldRecoveredUsdUnits, v))
}

// RecoveredUsdUnitsIn applies the In predicate on the "recovered_usd_units" field.
func RecoveredUsdUnitsIn(vs ...int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldIn(FieldRecoveredUsdUnits, vs...))
}

// RecoveredUsdUnitsNotIn applies the NotIn predicate on the "recovered_usd_units" field.
func RecoveredUsdUnitsNotIn(vs ...int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldNotIn(FieldRecoveredUsdUnits, vs...))
}

// RecoveredUsdUnitsGT applies the GT predicate on the "recovered_usd_units" field.
func RecoveredUsdUnitsGT(v int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldGT(FieldRecoveredUsdUnits, v))
}

// RecoveredUsdUnitsGTE applies the GTE predicate on the "recovered_usd_units" field.
func RecoveredUsdUnitsGTE(v int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldGTE(FieldRecoveredUsdUnits, v))
}

// RecoveredUsdUnitsLT applies the LT predicate on the "recovered_usd_units" field.
func RecoveredUsdUnitsLT(v int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldLT(FieldRecoveredUsdUnits, v))
}

// RecoveredUsdUnitsLTE applies the LTE predicate on the "recovered_usd_units" field.
func RecoveredUsdUnitsLTE(v int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldLTE(FieldRecoveredUsdUnits, v))
}

// DebtUsdUnitsEQ applies the EQ predicate on the "debt_usd_units" field.
func DebtUsdUnitsEQ(v int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldEQ(FieldDebtUsdUnits, v))
}

// DebtUsdUnitsNEQ applies the NEQ predicate on the "debt_usd_units" field.
func DebtUsdUnitsNEQ(v int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldNEQ(FieldDebtUsdUnits, v))
}

// DebtUsdUnitsIn applies the In predicate on the "debt_usd_units" field.
func DebtUsdUnitsIn(vs ...int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldIn(FieldDebtUsdUnits, vs...))
}

// DebtUsdUnitsNotIn applies the NotIn predicate on the "debt_usd_units" field.
func DebtUsdUnitsNotIn(vs ...int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldNotIn(FieldDebtUsdUnits, vs...))
}

// DebtUsdUnitsGT applies the GT predicate on the "debt_usd_units" field.
func DebtUsdUnitsGT(v int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldGT(FieldDebtUsdUnits, v))
}

// DebtUsdUnitsGTE applies the GTE predicate on the "debt_usd_units" field.
func DebtUsdUnitsGTE(v int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldGTE(FieldDebtUsdUnits, v))
}

// DebtUsdUnitsLT applies the LT predicate on the "debt_usd_units" field.
func DebtUsdUnitsLT(v int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldLT(FieldDebtUsdUnits, v))
}

// DebtUsdUnitsLTE applies the LTE predicate on the "debt_usd_units" field.
func DebtUsdUnitsLTE(v int64) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldLTE(FieldDebtUsdUnits, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldContainsFold(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PaymentExternalRefundJournal) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PaymentExternalRefundJournal) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PaymentExternalRefundJournal) predicate.PaymentExternalRefundJournal {
	return predicate.PaymentExternalRefundJournal(sql.NotPredicates(p))
}
